### ISSUE TITLE
Zero config test runs

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#1051]
With the command test runner (#1047) and the new sane default for the `files` array (#665), I think we have everything in place to support zero configuration test runs. I would suggest the following defaults to be added:

* Test runner: `'command'`
* Mutator: ~~The installed mutator (javascript/typescript)~~ `"javascript"`
* Files to mutator: `['src/**/*.js', 'lib/**/*.js']`
* Coverage analysis: `'off'` (it is `'perTest'` now, but the CommandTestRunner does not support it)

With this issue we can also improve our documentation of the main stryker package, to use the [jest](https://jestjs.io/docs/en/configuration.html) style configuration.

We should document the zero config somewhere. I think the quickstart on the website would be a good place.

We should maybe log the stryker configuration that is used for the run _somewhere_

@stryker-mutator/contributors do you agree?

**Comment by mthmulders** [comment]
Getting people started with a minimum of effort sounds like a good idea to me!

**Comment by nicojs** [comment]
I've updated the mutator to being`"javascript"` by default. I think that is a little easier to wrap your head around.
