### ISSUE TITLE
Unicode emoji support in the console reporter

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#1189]
Add unicode emoji support to the console reporter. 

For more info, see #975

**Comment by simondel** [comment]
@JoshuaKGoldberg Do you want to do this during hacktoberfest (starting next week)?

Or @noamyogev84 Do you still have plans to do this?

**Comment by JoshuaKGoldberg** [comment]
All you, go ahead 😁

**Comment by noamyogev84** [comment]
Nop. go ahead :)

**Comment by simondel** [comment]
All right, closing this issue for now.

**Comment by nicojs** [comment]
https://twitter.com/JoshuaKGoldberg/status/1484551399551778826?t=8Gh5U1jI_PxJ7J8UHHuqfA&s=19 👀👀
