### ISSUE TITLE
Add documentation to generated stryker.conf.js (stryker init)

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#1212]
Right now, the `stryker init` command results in a stripped down config file, without any explanation. For example, if you choose "mocha" as your test runner, you'll get an example mocha configuration in your stryker.conf.js, but without any further info. When the `stryker run` command later fails because of miss configuration, you're effectively stuck. 

It would be awesome if the command adds the links to the plugins web page. So people know where to find more options.

* ☕ https://stryker-mutator.io/docs/stryker-js/mocha-runner/
* 🃏 https://stryker-mutator.io/docs/stryker-js/jest-runner/
* 🥒 https://stryker-mutator.io/docs/stryker-js/cucumber-runner/
* 🇰 https://stryker-mutator.io/docs/stryker-js/karma-runner/
* 🟣https://stryker-mutator.io/docs/stryker-js/jasmine-runner/

The `stryker init` commands underwater retrieves the package.json files of the installed plugins in order to get at the `initStrykerConfig` package.json value. We can reuse that to get at the `homepage` value. Example url for package.json is:
https://registry.npmjs.org/stryker-jasmine-runner/latest

**Comment by kmdrGroch** [comment]
I think it can be closed now

**Comment by nicojs** [comment]
Closed with #3817.

Thanks @Giovds ♥
