### ISSUE TITLE
Support TypeScript projects using Babel

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-js#1232]
With Babel 7, you can use Babel together with TypeScript. Our current `stryker-babel-transpiler` plugin does not support this yet because it uses Babel 6. 

I would suggest upgrading the `stryker-babel-transpiler` to use Babel 7 internally. This will be a breaking change for projects that use Babel 6 as the transpilation and/or config may be different.

We should also document Babel projects on the stryker handbook.

**Comment by nicojs** [comment]
A agree whole heatedly. People using babel 6 can use the old version of the stryker-babel-transpiler (RIP for them poor fellows).

**Comment by kmdrGroch** [comment]
Is it still valid? 🤔

**Comment by kmdrGroch** [comment]
I think it can be closed now
