### ISSUE TITLE
Question: New stryker utility

### ISSUE THREAD

**Issue by tverhoken** [stryker-mutator/stryker-js#1457]
Hello,

I did [that utility](https://github.com/tverhoken/stryker-diff-runner) for Stryker that allow to run stryker only for the diff files between current branch and "origin/master" in order to be able to run mutation testing on branches and pull requests without taking too long for the CI build.

Would it be interesting to include it to the stryker-mutator projects ?

Regards.

**Comment by nicojs** [comment]
@tverhoken that is a cool tool 👍 ! I'll discuss it with @simondel. 

In the meantime, feel free to add the tool to the [guides segment of the stryker-handbook](https://github.com/stryker-mutator/stryker-handbook/tree/master/stryker/guides).

**Comment by tverhoken** [comment]
Hi @nicojs ,

I did take a look at Stryker latest versions and I was wondering if the diff runner should stay an utility script alongside Stryker or if it should be a plugin to add that feature to Stryker ?

It seems that plugins are the way to add features to Stryker now.

**Comment by nicojs** [comment]
You might be interested in #3229. I think "ignore plugin" would be great for this. Feedback would be much appreciated
