### ISSUE TITLE
SourceMapConsumers should be destroyed

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-js#1551]
With source-map 0.7.0, a `SourceMapConsumer` should be destroyed by calling `myconsumer.destroy()`

We create a consumer once for every instance of a `SourceMapper`. We could call `destroy` on disposing those instances.

**Comment by nicojs** [comment]
Calling destroy on the source maps would mean that our source map mapper instance should be disposable as well. We should use typed-inject's dispose functionality for this.

**Comment by kmdrGroch** [comment]
Has it been done? Or are we planning to do it?

**Comment by nicojs** [comment]
We've removed the dependency on `SourceMapConsumer` altogether.
