### ISSUE TITLE
Add the ability to add gitignored files inside the config: files

### ISSUE THREAD

**Issue by trollepierre** [stryker-mutator/stryker-js#1593]
### Summary

Here: 
https://github.com/stryker-mutator/stryker/tree/master/packages/core#files-string

I would like to be able to add my translation files that are gitignored. I run a command to update them.

**Comment by nicojs** [comment]
Hi @trollepierre thanks for opening this issue.

I think you linked the correct stryker option. With https://github.com/stryker-mutator/stryker/tree/master/packages/core#files-string you can override the default behavior of ignoring certain files.

Or is there some other feature you're requesting here?

**Comment by trollepierre** [comment]
Can you please give an example how to do add every file, except gitignored files, but with one exception file that is ignored?

**Comment by trollepierre** [comment]
I didn't succeed in doing it. :S

**Comment by nicojs** [comment]
> Can you please give an example how to do add every file, except gitignored files, but with one exception file that is ignored?

I see... this isn't possible at the moment, no. You would need to add glob expressions for all files you want to add explicitly. 

I've added the feature tag to this issue. How would you expect us to support this (without a breaking change)? We could add a flag like `fileResolvingStrategy`... or add a magic string constant that you need to put as first in the `files` array, like `!!gitfiles` or something, both not ideal.

**Comment by trollepierre** [comment]
> I've added the feature tag to this issue. 
Where?

> How would you expect us to support this (without a breaking change)? 
Adding a flag like `fileResolvingStrategy` would be the simplest solution to me.

Optional values would match:
- all files => `all`
- all gitfiles => `gitfiles`
- `custom` (in that case, follow what is inside `files`

What do you think about it?

**Comment by simondel** [comment]
With the exception of your node_modules folder, what is in your .gitignore right now? You could also work by adding all files and then excluding what you don't want.

Also, why would you like to have a file in the sandbox that is not in your git repo? What kind of file (or files) are we talking about?

**Comment by trollepierre** [comment]
I am talking about the translation, that we get from an external service (Phraseapp). 
The en.json and other language json are not committed during development. But are necessary to test the app.

**Comment by nicojs** [comment]
I've got another suggestion. 

NYC has a similair feature. It ignores node_modules by default, even if you override it with an `exclude` property. It than allows you to override this behavior [using --exclude-node-modules=false](https://github.com/istanbuljs/nyc#including-files-within-node_modules).

We can do this as well by providing a `--include-repository-files` flag. @simondel do you agree? This keeps backward compatibility and make it nice and explicit. I'm open for naming suggestions.

**Comment by trollepierre** [comment]
I was happy with the suggestion at first sight, but I wonder how can we implement custom files. 🤔 

Example: I want to test every files in my .gitignore + my translation. (not more)

Moreover I am not a big fan of the naming. Using a script --include-repository-files=translations works, but what if I have other files?

**Comment by trollepierre** [comment]
@simondel : 
>  what is in your .gitignore right now?

In my .gitignore, I have /.idea, *.log, coverage, several dist, .yarn.cache, .env

**Comment by nicojs** [comment]
> Moreover I am not a big fan of the naming. Using a script --include-repository-files=translations works, but what if I have other files?

I'm not sure if you understand me. This is what your stryker.conf.js would look like:

```js
{
  includeRepositoryFiles: true,
  files: ['dist/*.translation.js']
}
```

So it would just be a flag to signal that you also want your repository files to be included.

**Comment by trollepierre** [comment]
@nicojs : ok I understand and i like this idea!

**Comment by nicojs** [comment]
An out of the box idea, based on an older idea. Instead of whitelisting `files`, what about blacklisting? Allowing for a `.strykerignore` file. This is how prettier, eslint and other cool kids do it.

We might be able to use https://www.npmjs.com/package/glob-gitignore to do this.

We wouldn't rely on `git` anymore to do the file listing, which gives much more flexibility. We could still default to `.gitignore`, but enforcing the exact same functionality will be difficult, given that `.gitignore` files can add up (every directory can have one), this doesn't seem to be an out of the box feature of `glob-gitignore`

**Comment by trollepierre** [comment]
that would be better in my opinion!
Or more usable than the config idea

**Comment by kmdrGroch** [comment]
Is it still valid issue? we support `files` and git now.

**Comment by trollepierre** [comment]
I guess yes! (sorry to time to deep dive, in testing it)
Thanks

**Comment by nicojs** [comment]
Pretty sure this issue isn't fixed yet :). But fine for me.

**Comment by trollepierre** [comment]
then I reopen (but it can stay in the deep bottom of the backlog) 😆

**Comment by nicojs** [comment]
I want to implement this feature (`.strykerignore`) for v5
