### ISSUE TITLE
Run only related tests on initial run

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker-js#1655]
With jest testRunner Stryker executes tests for mutations with `--findRelatedTests` flag by default. Maybe initial test run should be with this flag too? This can increase performance for large code base if I mutate few files

**Comment by simondel** [comment]
I don't think the test runners really know if they're running an initial run or not. It's not really a flag.

What makes you think that the setting is not on during the initial run?

**Comment by Djaler** [comment]
Because I see tests count

**Comment by simondel** [comment]
Fair enough 👍  Do you also see that during the first runs while testing mutations? 

Since we copy your files to a sandbox, all files may be 'changed/touched' in the first run. Jest may have to run all tests once to build a new baseline so it can start doing incremental runs in the future.

**Comment by Djaler** [comment]
Hmm, I'll try to debug this case tomorrow

**Comment by Djaler** [comment]
Looks like InitialTestExecutor doesn't provide `mutatedFileName` arg to `sandbox.run`. And because of this initial tests run for all files.

**Comment by nicojs** [comment]
Maybe the jest runner can let all mutate files be injected using typed-inject. The problem is that it would need to be provided as well in Stryker. This is something that can be done.

**Comment by Djaler** [comment]
Dear bot, don't close this, please

**Comment by nicojs** [comment]
@Djaler We've just released StrykerJS 5.5 with this feature, see https://twitter.com/stryker_mutator/status/1463193769126383622
