### ISSUE TITLE
Honor all contributors

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#1921]
**Question**

We have the good fortune to receive wonderfull help from [the Stryker community](https://github.com/stryker-mutator/stryker/graphs/contributors). However, we've been pretty lousy in honoring them 😔. We need to change this 💖!

The question is, how do we want to do that? Who better to ask than our contributors themselves? Please (in no particular order) @JoshuaKGoldberg @ollelauribostrom @bharaninb @simondel @Archcry @mthmulders @brodybits @kmdrGroch @philippw @mshogren @sharikovvladislav @mscharley @tommilligan (and all the people I've forgot to include here (don't hesitate to add more)): How do you want to be honored?

There is a tool out there called [all-contributors-bot](https://github.com/all-contributors/all-contributors-bot#hello-all-contributors-bot-) than can add you're face to a readme file. Would you mind that? Since we have more than 1 readme file (1 per package), I suggest using the main readme file. However, I think we can also choose multiple readme files (or use the CLI tool to do that). So we can choose the main readme and the stryker core readme for example.

Other suggestions are welcome as well!

**Comment by mthmulders** [comment]
Looks cool!

**Comment by kmdrGroch** [comment]
I think we should have a nice group talk all together like we had one day with Nico and Simon :)

**Comment by JoshuaKGoldberg** [comment]
Haha I feel a bit silly being a tagged person here, given I've contributed almost nothing 😉 
. Which is probably why I'm totally fine with the way things are now. The built-in https://github.com/stryker-mutator/stryker/graphs/contributors charts are fine with me.

README.md face mentions seem like a nice thing to do either way!

**Comment by nicojs** [comment]
> Haha I feel a bit silly being a tagged person here, given I've contributed almost nothing

I did it mostly for the future PR you're going to do regarding emoji support in the console reporter #1189 😁

All jokes aside, the bot _is called_ "all-contributors-bot". I think you would qualify, amigo 🤠

**Comment by kmdrGroch** [comment]
Joshua, don't feel silly. My only contribution is doing maintenance stuff with TSLINT and ESLINT which is mostly "save, switch red lines, save, PR" ;D

**Comment by philippw** [comment]
I’d feel honoured.

**Comment by Archcry** [comment]
I have made some contributions years ago but I wouldn't say I am actively contributing towards Stryker at this point in time. I would not feel comfortable being credited for contributing since I haven't made a lot of contributions lately.
