### ISSUE TITLE
Support running Stryker from a subdirectory

### ISSUE THREAD

**Issue by thompsnm** [stryker-mutator/stryker-js#1957]
**Summary**

I have a repo with a `src/` directory and a `test/`. My `test/` directory is treated as its own submodule with a separate `package.json`. I set up Stryker in the `test/` directory and configured it to include files from the `src/` directory with relative paths. When I run the tests from the `test/` directory some mutants survive that I know should be killed. If I reconfigure Stryker to run from the root directory then the mutants that I would expect to be killed are killed.

This may be due to a pathing issue when creating the sandbox. I notice that when I run Stryker from the `test/` subdirectory the `src/` directory is copied into `.stryker-tmp/` rather than `.stryker-tmp/sandboxXXXXXXX/`.

I have filled in the requested information below, but I would also suggest looking at this repo that contains a simplified project for reproducing the issue and my test results: https://github.com/thompsnm/stryker-bug-reproduction

**Stryker config**

```js
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["clear-text", "progress"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off",
    files: [
      './comparator.test.js',
      '../src/comparator.js'
    ],
    mutate: [
      '../src/comparator.js'
    ]
  });
};
```

**Test runner config**

No additional Jest config necessary.

**Stryker environment**

```
+-- @stryker-mutator/core@2.4.0
+-- @stryker-mutator/javascript-mutator@2.4.0
+-- @stryker-mutator/jest-runner@2.4.0
```

```
+-- jest@24.9.0
```

**Test runner environment**

```shell
jest
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v8.11.4
| npm              | 5.6.0
| Operating System | macOS Mojave 10.14.4

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/4041963/stryker.log)

**Comment by simondel** [comment]
Thanks for letting us know! I'll tag this as a feature request.

**Comment by madhurabindu** [comment]
this would be useful, especially for azurefunctions in nodejs

**Comment by nicojs** [comment]
@madhurabindu why would it be useful for azurefunctions?
