### ISSUE TITLE
Mutants in controller functions mapped by swagger-express-mw always survive

### ISSUE THREAD

**Issue by jzeinert-sap** [stryker-mutator/stryker-js#2064]
**Summary**

The package `swagger-express-mw` adds a middleware to an express app with an OpenAPI specification (`swagger.yml`), which allows to map operations to controller functions inside the swagger file.
These may be successfully tested in an integration test with Mocha using the package `supertest`. However, even though tests succeed and fail as expected when mutating the source manually, Stryker always reports all mutants inside the controller as survived.

**Expected Behavior**

The mutant *StringLiteral* deleting the value in the object sent in the response to the get request in `controller.js` should be killed. Mutation score for `controller.js` is greater than 0.

**Observed Behavior**

Mutation score for `controller.js` is 0.

**Reproduction Repo**

[repo on github](https://github.com/jzeinert-sap/stryker-swagger-router-issue)

**Stryker config**

```
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    mutate: [
      'express-app.js',
      'api/controllers/controller.js'
    ],
    packageManager: "npm",
    reporters: ["html"],
    testRunner: "mocha",
    transpilers: [],
    testFramework: "mocha",
    coverageAnalysis: "off"
  });
};
```

**Test runner config**

```
module.exports = {
    spec: ['*.test.js']
}
```

**Stryker environment**

```
stryker-issue-reproduction-repo@1.0.0 /home/dev/stryker-issue-reproduction-repo
├─┬ @stryker-mutator/core@2.5.0
│ ├─┬ @stryker-mutator/api@2.5.0
│ ├── @stryker-mutator/util@2.5.0
├─┬ @stryker-mutator/html-reporter@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
│ ├── @stryker-mutator/util@2.5.0 deduped
├─┬ @stryker-mutator/javascript-mutator@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
├─┬ @stryker-mutator/mocha-framework@2.5.0
│ └── @stryker-mutator/api@2.5.0 deduped
├─┬ @stryker-mutator/mocha-runner@2.5.0
│ ├── @stryker-mutator/api@2.5.0 deduped
```

```
+-- mocha@6.2.2
```

**Test runner environment**

```shell
# Test command
mocha
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 13.6.0
| npm              | 6.13.4
| Operating System | Ubuntu MATE 1.20.1

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/4256837/stryker.log)

**Comment by nicojs** [comment]
Thanks for opening this issue. Could you please add a small example project that reproduces this issue? That would be very helpful. Can be a link to a git repo, or a zip file. Thanks in advance

**Comment by jzeinert-sap** [comment]
Sure, it's linked in the post above.

**Comment by simondel** [comment]
Hi @jzeinert-sap! It seems like the module that you use `app-root-path` is causing some issues. It registers the root of your repo as the current root instead of the sandbox folder. This causes your umutated sourcecode to be executed instead of the mutated code
