### ISSUE TITLE
Support the Alsatian test framework

### ISSUE THREAD

**Issue by ebousse** [stryker-mutator/stryker-js#2106]
**Is your feature request related to a problem? Please describe.**

I am now using the [Alsatian](https://github.com/alsatian-test/alsatian/tree/master/packages/alsatian) test framework to write and run TypeScript test cases. Unfortunately Alsatian is not directly supported by stryker.

**Describe the solution you'd like**

It would be great to have official support for Alsatian in stryker!

**Describe alternatives you've considered**

The `command` test runner can be used, but with lesser performance than with a proper stryker plugin.

**Comment by simondel** [comment]
Thanks for opening this issue! Right now the framework is small enough that I personally won't put time into supporting it, but if you would like to add support, that would be great! We could guide you in how our workflow works :)

PS: I read Atlassian the first couple of times, but now I learned a bit of history 🎉 🐶

**Comment by ebousse** [comment]
> Thanks for opening this issue! Right now the framework is small enough that I personally won't put time into supporting it, but if you would like to add support, that would be great! We could guide you in how our workflow works :)

Could be interesting! If I ever find some time to do that, I'll be sure to post here again.

> PS: I read Atlassian the first couple of times, but now I learned a bit of history

Indeed, I also found the name of the tool quite confusing at first :)

thanks for the fast answer!
