### ISSUE TITLE
Mark unnecessary tests

### ISSUE THREAD

**Issue by Lakitna** [stryker-mutator/stryker-js#2151]
**Question**

I've been using Stryker a lot lately as it allows me to basically test my testing efforts. I love it.

A great secondary effect is that I can find unnecessary source code. This has made many bits of code more readable :)

That leads me to wonder if there is a way to do find unnecessary tests via a similar approach. Removing unnecessary tests would keep the size of the test suite in check. It will also force me, as the person writing the tests, to write a few good tests over many ok tests. Fewer tests make maintenance easier. It makes it easier to find that one failing test. It allows new team members to not be overwhelmed etc.

So the question I have for you here is if Stryker can play a role in this?

**Stryker environment**

any

**Additional context**

I have not thought this through all the way yet. At this point, to me, this is an interesting thought experiment. And since this feels like it's in line with what Stryker is, I wanted to share this experiment with you.

Unnecessary tests in this context are those where you're testing the same thing multiple times. Or, in Stryker terms, multiple tests that kill the same mutations.

**Comment by nicojs** [comment]
Great question! Yes it would be possible. Unnecessary tests are tests that:

1. Never kill a mutant (useless test)
1. Always kill the exact same mutant as other tests (duplicate).

However, we're currently not focusing on this feature. We might do this in the mid-longer term. See https://github.com/stryker-mutator/stryker/wiki/Roadmap to see what we'll be focusing on.

If you want to contribute this feature, I'll be glad to add some thoughts here.

**Comment by Lakitna** [comment]
Ohh interesting. It sounds like you've given this some thought before. Has anyone made a start in working out how this should work for the user?

You know, starting with the high-level questions like:

- Why do we need this?
- How would this affect the user?
- How would this affect the testing process?

My thought process started with the technical stuff, but the meaningfulness of such a feature would not be primarily technical.

If no one has looked at answering these questions yet I'll take a stab at it.

**Comment by nicojs** [comment]
Thanks for closing stalebot 🤖

But, we've actually implemented this in #2868 and it got released with v5 🙇‍♀️
