### ISSUE TITLE
How to run Stryker in a monorepo

### ISSUE THREAD

**Issue by rwalle61** [stryker-mutator/stryker-js#2166]
Firstly thanks for this awesome package!

**Question**
I have [a repo](https://github.com/RuntimeTools/chai-openapi-response-validator) with 100% mutation score, which I want to convert to a monorepo. I've started splitting the existing repo into a `projectA` and a `sharedLogic` npm package. These will go in my `packages` dir (where I will later add `projectB`, `projectC` etc).

Now when I run Stryker from `projectA`, Stryker mutates `sharedLogic` (see my `stryker.conf.js`) but *doesn't kill those mutants*. 

This may be the same issue as https://github.com/stryker-mutator/stryker/issues/1957, in that Stryker is generating mutants in another directory but not killing them.

So how does Stryker the monorepo run Stryker on itself? I couldn't follow your scripts and lerna config, nor could I find much discussion about it. Do you have a simple example/explanation?

**Stryker environment**

```
"@stryker-mutator/core": "^2.0.0",
"@stryker-mutator/javascript-mutator": "^2.0.0",
"@stryker-mutator/mocha-framework": "^2.0.0",
"@stryker-mutator/mocha-runner": "^2.0.0",
```

```
"mocha": "^7.1.1",
```

**Additional context**
My `packageA` does a `require('sharedLogic')` (I do a `npm link` first)

My `stryker.conf.js`:
```
config.set({
    mutate: [
      'lib/**/*.js',
      '../sharedLogic/**/*.js', // this is how I get stryker to mutate `sharedLogic`
    ],
    files: [
      '**/*.js',
      '../sharedLogic/**/*.js',
    ],
```

**Comment by bhadouriyanikhils** [comment]
@rwalle61 have you got any answer yet?
I am also trying to set it up for monrepo.
Thanks in advance!
