### ISSUE TITLE
discovered trailing whitespace again

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker-js#2174]
**Summary**

I just happened to discover trailing whitespace at the end of a source when doing `git log -p` to check my work on something. From some further investigation I discovered trailing whitespace in the following:

- CHANGELOG.md
- e2e/tasks/ts-node-register.js
- packages/api/CHANGELOG.md
- packages/api/report.d.ts
- packages/core/CHANGELOG.md
- packages/core/src/config/OptionsValidator.ts
- packages/core/test/unit/initializer/StrykerInitializer.spec.ts
- packages/jasmine-runner/tsconfig.stryker.json
- packages/mutator-specification/CHANGELOG.md
- tasks/generate-json-schema-to-ts.js

I remember cleaning this up in the past, not sure whether or not this was ever automated.

I would be happy to do this cleanup again but started wondering if this should be part of the linting? (I think Prettier should be able to clean all of these artifacts for us.)

**Stryker config**

N/A

**Test runner config**

N/A

**Stryker environment**

N/A

**Test runner environment**

N/A

**Your Environment**

N/A

**Add stryker.log**

N/A

**Comment by nicojs** [comment]
I think we should add this to prettier configuration, diffently. Feel free to add it if you want. 👍

**Comment by brodybits** [comment]
Unfortunately I am fighting some major deadlines right now, may be able to investigate in the next 1-2 months or so. I wouldn't mind if someone else takes this on. I mostly wanted to raise the issue before it may be forgotten, sorry I am not more helpful right now. Yeah probably everyone is in the same boat:)

**Comment by kmdrGroch** [comment]
@brodybits could you verify if this is still a valid issue or if it can be closed?

**Comment by brodybits** [comment]
`git grep ' $'` shows some results at this point

Fortunately `git grep -P '\t$'` does not show any results (except for binary gif files which would be irrelevant)

**Comment by kmdrGroch** [comment]
If it is for files other than .ts, there is actually no check for it. Only Typescript files are linted for now
