### ISSUE TITLE
Seed for mutant generation

### ISSUE THREAD

**Issue by VaclavObornik** [stryker-mutator/stryker-js#2182]
**Is your feature request related to a problem? Please describe.**
I'd like to add the Stryker to our team CI pipeline, but I'm not doing it, because the Stryker generates the mutators in some random way for each run, so the results are not consistent. Sometimes the tested code passes, sometimes doesn't.

**Describe the solution you'd like**
I'd like to be able to add some "seed" to the configuration file, which would ensure all runs (on the same piece of code) will generate the same mutants consistently.

**Describe alternatives you've considered**
-

**Additional context**
I'm aware that this will cause there can be a potential bug in the tested code which will not be detected because all runs will have the same mutants, so some mutants regularly wouldn't be generated. But many of them would be and much of the value would be added to the quality of the tests.

**Comment by kmdrGroch** [comment]
@VaclavObornik its most likely a bug. Mutation tests should be consistent unless you add some random things. It is (i think) caused because of the number of resources that are used and some memory leaking. I believe most of it will be solved by Nico in mutation switching tho.

**Comment by nicojs** [comment]
Hi @VaclavObornik , as @kmdrGroch stated, Stryker is not doing anything random. Can you explain what appears to be random in the results?
