### ISSUE TITLE
Ignore Already Run Mutant

### ISSUE THREAD

**Issue by maulikhdave9601672767** [stryker-mutator/stryker-js#2242]
I have legacy system with 1000 test.

i run mutant one time and resolve some issues.

now to run second time i want to avoide all mutant which i already solved in
my first run.

**Comment by nicojs** [comment]
Hi @maulikhdave9601672767 👋 Welcome to Stryker.

This is a good idea. I think this is similar to #1980, #322 and https://github.com/stryker-mutator/stryker-net/pull/708. 

Also, I think @Garethp is thinking of this feature as well.

We currently have a feature freeze until we've implemented #1514 .
