### ISSUE TITLE
CICD pipeline Best Practice

### ISSUE THREAD

**Issue by maulikhdave9601672767** [stryker-mutator/stryker-js#2247]
if i have git project and 100 of code check in done in a day.

what is best practice  in this case?

for each check in or code push i should run mutant ?

cos arround 100 code push happened in a day and i have 1000 test cases

**Comment by kmdrGroch** [comment]
Welp, IMO, mutation testing doesn't need to be in CICD pipeline. I usually run them once per version, usually before release to check if there is something that should be refactored, deleted, tested etc.
Mutation testing is kinda slow (at least for now, but generally it is much slower than unit tests) so it just adds unnecessary time spent on waiting until CI gives info.

**Comment by nicojs** [comment]
Great question. @maulikhdave9601672767 . We would love to be able to run stryker in CI/CD, but this is currently only feasible in smaller projects. 

We're thinking of `--diff` mode, where mutation testing in a PR can run only on the changed code. Merges to the main branch can then result in a full mutation test run.  See #322. First want to get mutation switching in #1514 (that will also give a performance boost)
