### ISSUE TITLE
Don't mutate function calls for a given module

### ISSUE THREAD

**Issue by cohen990** [stryker-mutator/stryker-js#2257]
We run lots of logging and telemetry in our code. We also want to set up stryker in our CI pipeline to fail if there are surviving mutants.

We want to prevent stryker from mutating any of the code involved in our logging/telemetry modules

**Describe the solution you'd like**
Our logger library is called `cazoo-logger`. It has function calls like `logger.error("something went wrong")`

It'd be really cool if we could drop into our `stryker.conf.js` something like `ignoredModules: ['cazoo-logger']` and have stryker not try to mutate the string we pass into the error function.

**Describe alternatives you've considered**
The alternative is to let stryker occasionally complain about these log and telemetry lines. The downside would be that we would find ourselves ignoring lots of useful analysis from stryker because noise kills.

I'm aware I can set the thresholds and that would work just fine but in order to get the best use we'd have to frequently adjust the thresholds as we add more logging and we'd just end up with moving goalposts.

**Additional context**
Strongly related to https://github.com/stryker-mutator/stryker/issues/1472 but this perhaps may be a slightly different approach. I'm not sure if this approach would be easier or more difficult to implement.

**Comment by nicojs** [comment]
I think this is related to #1472. 

We're not planning to add smart code analysis as you are suggesting here. For that to work, we would need to dig deep into babel territory I think.

For example:

```js
import logger from 'cazoo-logger'; // calls to `logger` should be ignored by Stryker

logger.debug('foo'); // don't mutate!

function doLog(logger) {
   logger.info('bar'); // mutate? 🤔
}
```

It is virtually impossible to know if `'bar'` needs to be mutated here, without executing the code. 

Would you be OK with the suggested solutions in #1472 ?
