### ISSUE TITLE
Stryker for Angular project with SCSS

### ISSUE THREAD

**Issue by Abhishek-Ankush-git** [stryker-mutator/stryker-js#2265]
**Question**

I am trying to integrate Stryker in my angular project with scss. It keeps giving me error for too many open files.

**Stryker environment**

Stryker 3.3.0

```
+-- @stryker-mutator/core@3.3.0
+-- @stryker-mutator/karma-runner@3.3.0
+--@stryker-mutator/typescript@3.3.0
```

```
+-- karma@3.1.1
+-- angular-cli@7.1.2
![stryker issue](https://user-images.githubusercontent.com/67040759/84861224-2d4bac00-b08e-11ea-9575-d568f8b8969b.PNG)



**Summary**

<!--- Provide a general summary of the issue in the title above -->

**Stryker config**

<!--- Please place your stryker config below. Feel free to change paths in the files and mutate arrays if you cannot share them. -->

```js
module.exports = function(config){
  config.set({
    ....
  });
}
```

**Test runner config**

**Test runner environment**

```shell
# Test command
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             |
| npm              |
| Operating System |

**Add stryker.log**

**Comment by nicojs** [comment]
Hi @Abhishek-Ankush-git 👋

This seems like a bug. Could you please fill in all fields related to a bug report? That way it will be much easier for us to help you.

I've put the template in your issue text, that way you can edit it and add the information.
