### ISSUE TITLE
Default tempDir to `stryker-tmp` instead of `.stryker-tmp` for jest runner

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#2307]
**Is your feature request related to a problem? Please describe.**
Jest doesn't handle hidden directories well. See #2122. A valid workaround is to not load jest in a hidden directory (https://github.com/stryker-mutator/stryker/issues/2122#issuecomment-605783668)

**Describe the solution you'd like**
On `stryker init` override `tempDir` when `jest` runner is chosen.

**Describe alternatives you've considered**
Waiting for jest to fix https://github.com/facebook/jest/issues/9728 but it might take some time.

**Additional context**
This is broken since Jest 25. More and more people are migrating to 25, so this workaround is valid.

We could also change the default dir to not be a hidden dir. But I personally like it to be a hidden dir, so it won't clog up the file explorer.

**Comment by ChrisWillcock** [comment]
Ran into this problem myself and this fixed worked !!

**Comment by kmdrGroch** [comment]
We could make a check, what version of Jest is currently used and based on that determine if `.` can be on the first character or not.
Like,
```js
config.tempDir = jest.version.startsWith('25') && config.tempDir.startsWith('.') ?  config.tempDir.substring(1)   : config.tempDir;
```
