### ISSUE TITLE
Provide option to fail on timeout

### ISSUE THREAD

**Issue by lo1tuma** [stryker-mutator/stryker-js#2447]
**Problem**
We have noticed in one of our projects, that 100% of the mutants have been timed-out, no one was killed or survived. 
The project was configured to fail when we don’t reach a mutations score of 100% and since a timeout is not counted as a survived test our mutation test in the CI pipeline of the project always passed.

When I’ve initially setup the project 10 months ago everything worked fine and I also had a detailed look at the HTML report. But since we reached 100% mutation score we never looked at the report or console output.

So we discovered this today by accident and we are very surprised that mutation testing basically stopped working since a couple of month.

**Possible Solution**
Provide an option that lets stryker fail whenever a timeout (or other kind of unexpected error) is encountered.

**Comment by nicojs** [comment]
Hi @lo1tuma 👋 thanks for opening this issue.

Ai... 100% timeouts is... not good 😰 

A timeout is not seen as "error" by Stryker, it is even counted as a killed mutant (that's why you're getting 100% score). The reason for this is that a timeout can be perfectly valid.

For example:

```js
let i = 10;
while(i > 0) {
   i = i -1; // mutated to i + 1 by Stryker
}
```

The mutant `i + 1` will result in a timeout in this case.

We're counting the timeout as a "killed" mutant because this is something test would have caught... because your test will probably timeout and fail in normal circumstances as well. 

That said, I think we should maybe treat 100% timeouts as a special case and fail. Would that be OK for you?

Curious: did you find out what caused Stryker to end up in timeouts all of a sudden. That should not happen...

**Comment by lo1tuma** [comment]
Hi @nicojs, thanks for your reply 🙂.

I haven’t thought about mutants that will cause an infinite loop, so I think your suggested solution would be better.

> Curious: did you find out what caused Stryker to end up in timeouts all of a sudden. That should not happen...

My assumption is that we have those problems either since the update to v3 (update was done by renovate bot) or since a new big feature was implemented a couple of months ago which increased the total amount of mutants.
We are using the command runner with `ava`, which seems to be problematic since both tools try to utilize all available CPU cores. I’ve now limited the concurrency of `ava` and also added the `fail-fast` option. This already helped, and now I get zero timeouts again (although it is still quite slow, but that is a different problem).

**Comment by nicojs** [comment]
> a new big feature was implemented a couple of months ago which increased the total amount of mutants.

More mutants shouldn't equal more timeouts. The timeout time is calculated per test run, so more code means more time. This is the full formula that is used for the command test runner:

`timeout` = `initialTestRunTime` * `timeoutFactor` + `timeoutMS`

Side question: would you mind trying out the new beta? It might give you a performance improvement and you would help us out a lot with testing this specific AVA use case.

Please see https://stryker-mutator.io/blog/2020-07-13/announcing-stryker-4-beta-mutation-switching for more details.

**Comment by lo1tuma** [comment]
> so more code means more time

This might be the problem then.

> `timeout` = `initialTestRunTime` * `timeoutFactor` + `timeoutMS`

Or this could be the problem as well. In case of `ava` and the `command` runner the initial test run is much faster, since `ava` can utilize all CPU cores and the command runner has not yet started to use multiple threads.. For the actual mutation tests both tools tried to utilize all CPU cores, which might slow down everything due to many context switches of the CPU cores.

> Side question: would you mind trying out the new beta? 

That sound interesting, I will give it a try.

**Comment by lo1tuma** [comment]
> Side question: would you mind trying out the new beta?

FWIW: I’ve just tested the beta with `core@4.0.0-beta.4` and `typescript-checker@4.0.0-beta.4`. Unfortunately the initial test run fails. It seems like one test file errors with `error TS1160: Unterminated template literal.`. All other tests (71) pass.
