### ISSUE TITLE
For a failure case in the final report, have a way to identify the tests that covered that code

### ISSUE THREAD

**Issue by gramster** [stryker-mutator/stryker-js#2464]
In order to know what tests need to be improved, it would be useful to know what tests actually covered a particular mutation.

**Comment by nicojs** [comment]
Yeah! Great request. We're definitely planning to add this in the future. Also: which test killed the mutant.

For now, the clear text reporter actually logs it, so you can use that.

**Comment by nicojs** [comment]
Closed with #2868
