### ISSUE TITLE
require() is not resolving files correctly, and it is really hard to debug

### ISSUE THREAD

**Issue by gramster** [stryker-mutator/stryker-js#2504]
**Summary**

I've been beating my head against this for a couple of days and am stumped. I don't necessarily think this is a Stryker issue, but I need help, and I do have some possible feature requests for things that would make my life easier.

I am running Stryker against the http://github.com/microsoft/vscode-python repository. I get many many errors like:

```
12:39:44 (69635) DEBUG ClearTextReporter #49115. [RuntimeError] ConditionalExpression
12:39:44 (69635) DEBUG ClearTextReporter ^[[36m/home/gram/repos/vscode-python/src/client/workspaceSymbols/parser.ts^[[39m:^[[33m155^[[39m:^[[33m8^[[39m
12:39:44 (69635) DEBUG ClearTextReporter ^[[31m-       if (!fuzzy.test(searchPattern, match.name)) {^[[39m
12:39:44 (69635) DEBUG ClearTextReporter ^[[32m+       if (true) {^[[39m
12:39:44 (69635) DEBUG ClearTextReporter
12:39:44 (69635) DEBUG ClearTextReporter Error message: TypeError: Cannot read property 'FileNotFound' of undefined
TypeError: Cannot read property 'FileNotFound' of undefined
    at /home/gram/repos/vscode-python/.stryker-tmp/sandbox9659821/out/client/common/platform/errors.js:49:51
    at Object.<anonymous> (/home/gram/repos/vscode-python/.stryker-tmp/sandbox9659821/out/client/common/platform/errors.js:83:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/home/gram/repos/vscode-python/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at require.extensions..js (/home/gram/repos/vscode-python/.stryker-tmp/sandbox9659821/out/test/datascience/reactHelpers.js:256:13)
    at Object.newLoader [as .js] (/home/gram/repos/vscode-python/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at Module._load (/home/gram/repos/vscode-python/.stryker-tmp/sandbox9659821/out/test/vscode-mock.js:50:29)
```

The FileNotFound error comes from this code in `src/client/common/platform/errors.ts`:

```
import * as vscode from 'vscode';
...
namespace vscErrors {
  const FILE_NOT_FOUND = vscode.FileSystemError.FileNotFound().name;
```

and the definition of the vscode module comes from `node_modules/@types/vscode`. This is an API that in the real world lives in Visual Studio Code and is accessible to all extensions that it hosts, including the one I am trying to test. In order to be able to run our tests, we have to mock it. The mocked version is in `src/tests/mocks/vsc`, and this is wired up in `src/test/unittest.ts` by modifying require to route through a wrapper defined in `src/test/vscode-mock.ts`. We have one other place where we mess with module loading, namely that `reactTestHelpers` file.

The first question I have is: what is up with the stack above? It isn't complete - something must have called into vscode-mock for this to happen. All the rest may actually be legit, because it looks like it is falling through to the original way of loading modules instead of the wrapper. It seems like this is just the first few levels of the stack, but that is not enough context. Am I right, and is there a way to get full stacks?

Secondly, how can I log stuff so it shows up in the Stryker log or the output? I have tried using console.log but as far as I can see I get nothing output.

Thirdly, when a run-time error like this occurs, can something be put in the output at the same time as the stack trace to tell me what test was running? And ideally provide me some command line argument that I can use to replicate just this single run (ideally under a debugger), and ideally without having to repeat my build command. I realize this would be test runner specific, but it would help enormously (doing a `stryker run` takes a couple of hours and there's so much missing context in the logs that I don't know how to narrow down to the right test, let alone the right set of mutations - although I should note that all the code above that messes with module loading is test helper code and not subject to mutation).
 

**Stryker config**

```js
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "coverageAnalysis": "perTest",
  "mutate": ["src/client/**/*.ts"],
  "buildCommand": "npx gulp prePublishNonBundle",
  "testRunner": "mocha",
  "mochaOptions": {
    "config": "./build/.mocha.unittests.js.json"
  },
  "cleanTempDir": false,
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ]
}
```

**Test runner config**

```
{
    "spec": "./out/test/**/*.unit.test.js",
    "require": ["source-map-support/register", "out/test/unittests.js"],
    "reporter": "mocha-multi-reporters",
    "reporter-option": "configFile=build/.mocha-multi-reporters.config",
    "ui": "tdd",
    "recursive": false,
    "colors": true
}
```

**Stryker environment**

```
├─┬ UNMET PEER DEPENDENCY @stryker-mutator/core@4.0.0-beta.8
│ ├─┬ @stryker-mutator/api@4.0.0-beta.8
│ ├─┬ @stryker-mutator/instrumenter@4.0.0-beta.8
│ │ ├── @stryker-mutator/api@4.0.0-beta.8 deduped
│ │ ├── @stryker-mutator/util@4.0.0-beta.8 deduped
│ ├─┬ @stryker-mutator/util@4.0.0-beta.8
├─┬ @stryker-mutator/mocha-runner@4.0.0-beta.8
│ ├── @stryker-mutator/api@4.0.0-beta.8 deduped
│ ├── @stryker-mutator/util@4.0.0-beta.8 deduped
├─┬ @stryker-mutator/typescript-checker@4.0.0-beta.8
│ ├── @stryker-mutator/api@4.0.0-beta.8 deduped
│ ├── @stryker-mutator/util@4.0.0-beta.8 deduped
```

```
├─┬ mocha@8.1.1```

**Test runner environment**

<!-- Please add your test command here (probably the command you use in `npm test`) command -->

```shell
npm test:unittests
```

```json
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.18.4 |
| npm              | 6.14.6 |
| Operating System | MacOS Catalina |

**Add stryker.log**

Log file is too big.

**Comment by nicojs** [comment]
Hi @gramster thanks for opening this issue!

> The first question I have is: what is up with the stack above? It isn't complete - something must have called into vscode-mock for this to happen

Hmm that is very strange indeed. I don't think this is Stryker's doing. We're using this code to serialize the error:

https://github.com/stryker-mutator/stryker/blob/9c693ee521245e79641d3f89c62812cdb2cdec35/packages/util/src/errors.ts#L5

> Secondly, how can I log stuff so it shows up in the Stryker log or the output? I have tried using console.log but as far as I can see I get nothing output.

The stdout and stderr of the test runner processes are logged at `trace` level. So `--fileLogLevel trace` (or `--logLevel trace` if you're feeling adventurous) should allow you to see them.

> Thirdly, when a run-time error like this occurs, can something be put in the output at the same time as the stack trace to tell me what test was running

Yes, this is something we could add.

> And ideally provide me some command line argument that I can use to replicate just this single run (ideally under a debugger), and ideally without having to repeat my build command. I realize this would be test runner specific

Yes. I think a debugging.md documentation file is the place for this kind of thing.

For now: you can run your unit tests with the specific mutant active using `__STRYKER_ACTIVE_MUTANT__=42 node --inspect-brk ../../node_modules/mocha/bin/mocha --config ./build/.mocha.unittests.js.json` from your sandbox directory.

I hope this helps you. Please see #2505 for more help with debugging.

**Comment by nicojs** [comment]
@gramster Let me try to help you debug further while #2505 isn't finished yet.

1. Open `node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxy.js`
1. Change line 57:
   ```
   - this.worker = child_process_1.fork(require.resolve('./ChildProcessProxyWorker'), [messageProtocol_1.autoStart], { silent: true, execArgv: [] });
   + this.worker = child_process_1.fork(require.resolve('./ChildProcessProxyWorker'), [messageProtocol_1.autoStart], { silent: true, execArgv: [ '--inspect-brk' ] });
   ```
1. Now run Stryker with `--concurrency 1 --timeoutMS 9999999`
1. Attach debugger.

I would suggest setting a breakpoint here: `node_modules/@stryker-mutator/core/src/test-runner/ChildProcessTestRunnerWorker.js` on line 34 (inside the `async mutantRun(options)` method). There you can change the active mutant (on the options). 

Please let me know if you need more insights.
