### ISSUE TITLE
Karma 5.2 incompatible with Stryker

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#2514]
Just a heads up for anyone that uses Stryker with Karma. Karma 5.2 seems to be incompatible with Stryker because of https://github.com/karma-runner/karma/issues/3560

**Comment by simondel** [comment]
This might be fixed with the next release of Karma

**Comment by nicojs** [comment]
It seems to be fixed with `karma@6`. Do we want to add a check in the karma-runner for broken versions?

**Comment by nicojs** [comment]
Since fixed in Karma.
