### ISSUE TITLE
Error in initial test run: "undefinedTypeScript diagnostics"

### ISSUE THREAD

**Issue by awerlang** [stryker-mutator/stryker-js#2560]
**Summary**

`stryker run` generates errors from TypeScript diagnostics that wouldn't otherwise show up in vue-cli or jest. The type definitions are from the vue project, and from what I can tell it doesn't seem possible that there are any type errors.

It's a Vue project and it can be seen at:
* https://github.com/awerlang/sourdough/commit/fd309eb24e396e89ea8f22b350839d680e7fc400
* The parent commit reproduces the error

Alternatives to fix the issue:

* Disable diagnostics in ts-jest for stryker;
* Disable diagnostics in ts-jest for jest (although it doesn't manifest in jest);
* Disable strict checking in tsconfig.json (not a solution, and it doesn't fix the readonly assignment error);
* `disableTypeChecks: ["**/*.{ts,vue}"]` in stryker.conf.js (I noticed the default configuration would exclude the test**s** directory.)

Awesome project btw. Let me know if there's anything more I could do to help fix the issue.

**Stryker config**

```js
{
  _comment:
    "This config was generated using a preset. Please see the handbook for more information: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/vuejs.md#vuejs",
  mutate: [
    "src/**/*.{ts,vue}"
  ],
  testRunner: "jest",
  mutator: {
    plugins: []
  },
  jest: {},
  reporters: ["progress", "clear-text", "html"],
  coverageAnalysis: "off"
}
```

**Test runner config**

```js
module.exports = {
  preset: "@vue/cli-plugin-unit-jest/presets/typescript",
  transform: {
    "^.+\\.vue$": "vue-jest"
  }
};
```

**Stryker environment**

```
├─┬ @stryker-mutator/core@4.0.0
│ ├─┬ @stryker-mutator/api@4.0.0
│ ├─┬ @stryker-mutator/instrumenter@4.0.0
│ ├─┬ @stryker-mutator/util@4.0.0
├─┬ @stryker-mutator/jest-runner@4.0.0
```

```
├─┬ @vue/cli-plugin-unit-jest@4.5.7
│ ├─┬ babel-jest@24.9.0
│ ├─┬ jest@24.9.0
│ ├─┬ jest-environment-jsdom-fifteen@1.0.2
│ ├─┬ jest-serializer-vue@2.0.2
│ ├─┬ ts-jest@24.3.0
│ ├─┬ vue-jest@3.0.7
│ │ ├─┬ jest-worker@25.5.0
└─┬ vue-jest@5.0.0-alpha.4

```

**Test runner environment**

```shell
jest
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.18.2
| npm              | 6.14.5
| Operating System | Linux

**Add stryker.log**

```
21:03:20 (6293) INFO ConfigReader Using stryker.conf.js
21:03:20 (6293) INFO InputFileResolver Found 1 of 43 file(s) to be mutated.
21:03:21 (6293) INFO Instrumenter Instrumented 1 source file(s) with 6 mutant(s)
21:03:21 (6293) INFO ConcurrencyTokenProvider Creating 7 test runner process(es).
21:03:21 (6293) INFO DryRunExecutor Starting initial test run. This may take a while.
21:03:24 (6293) ERROR DryRunExecutor One or more tests resulted in an error:
        undefinedTypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
tests/unit/composables/useModelValue.spec.ts:15:10 - error TS2532: Object is possibly 'undefined'.

15   expect(comp.value.value).toBe(1000);
            ~~~~
tests/unit/composables/useModelValue.spec.ts:15:10 - error TS2532: Object is possibly 'undefined'.

15   expect(comp.value.value).toBe(1000);
            ~~~~~~~~~~
tests/unit/composables/useModelValue.spec.ts:22:3 - error TS2532: Object is possibly 'undefined'.

22   comp.value.value = 500;
     ~~~~
tests/unit/composables/useModelValue.spec.ts:22:3 - error TS2532: Object is possibly 'undefined'.

22   comp.value.value = 500;
     ~~~~~~~~~~
tests/unit/composables/useModelValue.spec.ts:22:14 - error TS2540: Cannot assign to 'value' because it is a read-only property.

22   comp.value.value = 500;
                ~~~~~
21:03:24 (6293) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (/src/sourdough/node_modules/@stryker-mutator/core/src/process/3-DryRunExecutor.js:64:15)
    at DryRunExecutor.timeDryRun (/src/sourdough/node_modules/@stryker-mutator/core/src/process/3-DryRunExecutor.js:72:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DryRunExecutor.execute (/src/sourdough/node_modules/@stryker-mutator/core/src/process/3-DryRunExecutor.js:37:42)
    at async Stryker.runMutationTest (/src/sourdough/node_modules/@stryker-mutator/core/src/Stryker.js:36:53)

```

**Comment by nicojs** [comment]
Thanks for the extensive bug report and praise 😊

> I noticed the default configuration would exclude the tests directory.

I think this is an oversight. The default is to ignore type checks in `lib`, `src` and `test` directory. However, I've noticed that some people are using `tests` as a convention. 

> Let me know if there's anything more I could do to help fix the issue.

Sure 😅

https://github.com/stryker-mutator/stryker/blob/c593f74ee1446875a6993eb0fe2b6e05828ca255/packages/api/schema/stryker-core.json#L364

Adding the `tests` directory here should do the trick.
