### ISSUE TITLE
How to improvise the stryker run time execution as it takes hours to finish compilation

### ISSUE THREAD

**Issue by LokeshGangaiah** [stryker-mutator/stryker-js#2679]
**Question**

How can i get the stryker run time to be improved ? 
Currently when i run the project, it is taking close to and hour to finish scanning/ running the unit test files (say around 2500 files)

**Stryker environment**

```
npm├─┬ UNMET PEER DEPENDENCY @stryker-mutator/core@4.3.1
│ ├─┬ @stryker-mutator/api@4.3.1
│ ├─┬ @stryker-mutator/instrumenter@4.3.1
│ │ ├── @stryker-mutator/api@4.3.1 deduped
│ │ ├── @stryker-mutator/util@4.3.1 deduped
│ ├─┬ @stryker-mutator/util@4.3.1
├─┬ @stryker-mutator/jest-runner@4.3.1
│ ├── @stryker-mutator/api@4.3.1 deduped
│ ├── @stryker-mutator/util@4.3.1 deduped
├─┬ @stryker-mutator/karma-runner@4.3.1
│ ├── @stryker-mutator/api@4.3.1 deduped
│ ├── @stryker-mutator/util@4.3.1 deduped
├─┬ @stryker-mutator/typescript-checker@4.1.2
│ ├─┬ @stryker-mutator/api@4.1.2
│ ├─┬ @stryker-mutator/util@4.1.2
 ERR! peer dep missing: @angular/common@^8.0.0, required by @ng-idle/core@8.0.0-beta.4
npm ERR! peer dep missing: @angular/core@^8.0.0, required by @ng-idle/core@8.0.0-beta.4
npm ERR! peer dep missing: @ngrx/store@8.6.1, required by @ngrx/store-devtools@8.6.1
npm ERR! peer dep missing: @stryker-mutator/core@~4.1.0, required by @stryker-mutator/typescript-checker@4.1.2
npm ERR! peer dep missing: node-sass@^4.0.0, required by sass-loader@8.0.2
npm ERR! peer dep missing: fibers@>= 3.1.0, required by sass-loader@8.0.2
npm ERR! peer dep missing: html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5, required by webpack-subresource-integrity@1.4.0
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.2
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.2
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.4.2
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.4.2
├─┬ stryker-typescript@0.18.1
│ ├── @stryker-mutator/util@0.1.0
│ ├─┬ stryker-api@0.24.1
```

The below are in my package.json, so i selected command line as an option for runner when installing stryker init
```
    "karma": "~5.1.0",
   "jest": "^24.8.0",
    "@angular/cli": "~9.1.11",
```

**Additional context**

**Comment by simondel** [comment]
Is this the timeout you mentioned in #2676 because of the test process having a watch or something else?

**Comment by LokeshGangaiah** [comment]
@simondel it is related to the same project i am working on, was able to resolve the 2676 by commenting the test. But end up with another error which is execution time, because i am using the command option "testRunner: "command"," as a runner in the stryker.config.js file, which gives with a note saying the performance will take a back seat.

But if i am using karma/mocha as a runner, i end up with 
Cause: Cannot load TestRunner plugin "karma"
Cause: Cannot load TestRunner plugin "mocha" or "jest" respectively
which would be the same as 2414 issue? i am not sure.

only option which is working for me is the command line runner option,  but the execution time is a problem

any help here pls

**Comment by nicojs** [comment]
@LokeshGangaiah what are your versions of Stryker and its plugins?

Please execute this command in bash or git bash: `npm ls | grep stryker`

**Comment by LokeshGangaiah** [comment]
> @LokeshGangaiah what are your versions of Stryker and its plugins?
> 
> Please execute this command in bash or git bash: `npm ls | grep stryker`

@nicojs the ver of stryker and its plugins with that command executed is been captured in the above under "Stryker environment"
