### ISSUE TITLE
Implement support for parallelized builds

### ISSUE THREAD

**Issue by tobobo** [stryker-mutator/stryker-js#2707]
**Is your feature request related to a problem? Please describe.**
To save time when running a mutation test in CI, we're interested in being able to parallelize our mutation tests and collect the combined test results afterwards. We have come up with a solution that can combine multiple JSON reports and uses the HTML reporter directly to generate a report for all files, but other Stryker users might be interested in having a built-in solution.

**Describe the solution you'd like**
- A `stryker report` command that accepts one or more JSON report files and can produce reports using any of the existing reporters. This would allow JSON reports that partially cover a codebase to be combined in to a single report.
- It might also be helpful to be able to optionally skip the dry run. This way, you could run the dry run once, and then parallelize the subsequent runs when testing mutations. Currently with our solution we do the dry run in every container, which increases the overall number of CI minutes we're using.

**Describe alternatives you've considered**
We have a custom implementation that we built to allow this. The key is in a script that combines the mutation data from multiple parallel test runs. There are lots of improvements that could be made here—validating that `schemaVersion` and `thresholds` are consistent, for example, and allowing multiple reporters.

```
const fs = require('fs');
const path = require('path');

const { default: HtmlReporter } = require('@stryker-mutator/core/src/reporters/html/html-reporter');
const glob = require('fast-glob');
const { calculateMetrics } = require('mutation-testing-metrics');

const strykerConfig = require('../../../stryker.conf');

const files = glob.sync('./mutation-reports/mutation-container-*.json');

async function run() {
	// Combine data from parallel mutation test runs
	const combinedData = files.reduce((acc, jsonOutputPath) => {
		// eslint-disable-next-line global-require
		const fileData = require(path.resolve(jsonOutputPath, '.'));
		return {
			schemaVersion: fileData.schemaVersion,
			thresholds: fileData.thresholds,
			files: {
				...acc.files,
				...fileData.files,
			},
		};
	}, {});

	// Create HTML report from combined data
	const reporter = new HtmlReporter(
		strykerConfig,
		// fake logger
		{
			info: (...args) => console.log(...args),
			warn: (...args) => console.log(...args),
			debug: (...args) => console.log(...args),
			error: (...args) => console.log(...args),
		},
	);

	reporter.onMutationTestReportReady(combinedData);

	await reporter.wrapUp();

	// Save combined JSON data
	fs.writeFileSync('./mutation-reports/mutation.json', JSON.stringify(combinedData, undefined, 2));

	// Save aggregated metrics data
	const metrics = calculateMetrics(combinedData.files);
	fs.writeFileSync('./mutation-reports/metrics.json', JSON.stringify(metrics, undefined, 2));
}

run();
```

`stryker.conf.js` is configured to put the CircleCI container index in the filename:

```
	jsonReporter: {
		fileName:
			process.env.CI && process.env.CIRCLE_NODE_INDEX
				? `mutation-reports/mutation-container-${process.env.CIRCLE_NODE_INDEX}.json`
				: 'mutation-reports/mutation.json',
	},
```

We've configured CircleCI to run our tests in parallel using `circleci tests split` to mutate a subset of files for each container. (`get-mutation-paths.js` just performs a glob with the `mutate` config value in stryker.conf.js).
```
  mutation-test:
    # ...job container config
    parallelism: 10
    steps:
      # ...setup steps...
      - run:
          name: 'Run mutation test'
          command: |
            npx stryker run \
              --mutate $( \
                node ./.circleci/scripts/mutation-test/get-mutation-paths.js \
                | circleci tests split --split-by=filesize \
                | xargs \
                | sed -e 's/ /,/g' \
              )
      - persist_to_workspace:
          root: ./
          paths:
            - mutation-reports
```

Then we run the above script to combine the reports.

```
  mutation-report:
    # ...job container config
    steps:
      # ...setup steps
      - run:
          name: 'Combine mutation test reports'
          command: node ./.circleci/scripts/mutation-test/combine-mutation-reports.js
      - store_artifacts:
          path: mutation-reports
```

**Additional context**
CircleCI has a total build time limit of 5 hours, so this has been essential for allowing us to run this job in CI, and takes our mutation test run (for nearly 7000 mutations) down to about 45 minutes.

**Comment by nicojs** [comment]
Thanks for opening this issues @tobobo

Merging reports is actually something that we also needed, namely in the Stryker dashboard. You can find our implementation here:

https://github.com/stryker-mutator/stryker-dashboard/blob/eae4f8536eaef3daa89f48df4a00a4b831edefc3/packages/data-access/src/services/MutationTestingReportService.ts#L87-L95

I agree that merging reports is something useful for more people. However, I think it is better suited for mutation-testing-metrics here: https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-metrics

The actual generation of the HTML is something small and simple and that could be part of the mutation testing elements monorepo as well.

**Comment by tobobo** [comment]
Thanks for the reply! If I'm understanding this suggestion correctly, here's what an implementation path might look like—

1. Allow `mutation-testing-metrics` to accept multiple mutation reports as input (maybe something as simple as `calculateMetrics(...mutationTestReports)`, which would be compatible with the existing API
2. Extract HTML generation from the stryker-mutator/stryker reporters directory to a package in stryker-mutator/mutation-testing-elements 
3. Load html generator as dependency in the stryker-mutator/stryker HTML reporter
4. Projects that require parallelism would write a custom script that uses mutation-testing-metrics and the new HTML generation package

This would definitely be a step forward! Do you think there would be a path to include this in a CLI, or do you think it should stay as an option using a custom script? (The above process would definitely be a big improvement!)

**Comment by lbragile** [comment]
I am the same situation where GitHub workflow does not allow me to run for more than 6 hours even with the "timeout-minutes" configuration set to much more.

Would mutating multiple folders in parallel and adjusting the Stryker "module" config parameter accordingly not solve this? It was my understanding from the documentation that each module would be merged in with existing modules in the dashboard.

Thank you for the awesome work.

**Comment by nicojs** [comment]
Yes, the dashboard supports merging, we should move it to `mutation-testing-metrics` see https://github.com/stryker-mutator/mutation-testing-elements/issues/1180
