### ISSUE TITLE
ERROR Stryker Error: Something went wrong in the initial test run in typescript jest project

### ISSUE THREAD

**Issue by ralves20** [stryker-mutator/stryker-js#2730]
Hey guys!

I'm using stryker in a angular typescript project with jest as the test runner, however, when I try to run the "stryker run", I keep getting ts errors and the mutation does not run... what can be wrong?

I'm using stryker 4.4.1

This is my stryker.conf.json
```
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "jest",
  "transpilers": [
    "typescript"
  ],
  "coverageAnalysis": "off",
  "tsconfigFile": "tsconfig.json",
  "mutate": [
    "src/**/*.ts",
    "!src/**/*.spec.ts"
  ],
  "jest": {
    "projectType": "custom",
    "configFile": "jest.config.js",
    "config": {
      "testEnvironment": "jest-environment-jsdom",
      "preset": "ts-jest",
      "resetModules": true
    },
    "enableFindRelatedTests": true
  },
  "disableTypeChecks": "src/**/*.spec.ts",
  "maxConcurrentTestRunners": 10,
  "timeoutMS": 60000
}
```

And this is the error that I'm getting:
```
                                                                  ~~~~~~~~~~~~~~~~~~~
src/app/percentage/percentage.ts:68:122 - error TS2554: Expected 0 arguments, but got 1.

68       percent = percent.replace(stryMutAct_9fa48(5038) ? "" : (stryCov_9fa48(5038), '.'), stryMutAct_9fa48(5039) ? "" : (stryCov_9fa48(5039), ','));
                                                                                                                            ~~~~~~~~~~~~~~~~~~~ 
08:49:58 (25002) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted
```

**Comment by nicojs** [comment]
Hi @ralves20 👋

I see you're using `ts-jest`. For that to work, Stryker needs to disable type checking on the files it mutates, since mutating a file will result in some type errors (as you can see).

Could you try widening your `disabledTypeChecks` to include your files under test? For example `"disableTypeChecks": "src/**/*.ts",`

**Comment by ralves20** [comment]
Hey @nicojs !
I just did this, but I keep getting the errors:
  "disableTypeChecks": "src/**/*.ts",

**Comment by nicojs** [comment]
Be sure to remove the `.stryker-tmp` directory between each attempt (jest might find tests from a previous run there, I've seen that happen).

What version of TypeScript are you using? `node -p "require('typescript/package').version"`. Stryker with TS-jest needs at least TypeScript v3.7.

**Comment by ralves20** [comment]
Hey @nicojs my typescript version was 3.2.2, so I've updated it to 3.72
Now, the error is:

```
    at Resolver._getAbsolutePath (node_modules/jest-resolve/build/index.js:424:14)
    at Resolver.getModuleID (node_modules/jest-resolve/build/index.js:397:31)
    at Runtime._shouldMock (/node_modules/jest-runtime/build/index.js:1417:37)
    at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:823:16)
    at Object.<anonymous> (.stryker-tmp/sandbox403159/src/app/shared/components/xpto.component.ts:49:26)
    at Runtime._execModule (node_modules/jest-runtime/build/index.js:1205:24)
    at Runtime._loadModule (node_modules/jest-runtime/build/index.js:805:12)
    at Runtime.requireModule (node_modules/jest-runtime/build/index.js:662:10)
09:17:28 (27625) ERROR Stryker Error: Something went wrong in the initial test run
```

**Comment by nicojs** [comment]
Owww 3.2 is pretty old.

Yeah, you might need to update a bunch of dependencies, for example, your local `ts-jest` is probably not supporting `typescript@3.7.2` version. Please make sure your normal unit tests work, then Stryker should also work.

**Comment by ralves20** [comment]
Hey @nicojs 
So, I've analyzed here in the project that I work, and we need to keep the version 3.2.2 of TS...
Is there any workardound that I could make to be able to run stryker on this project?

Thanks!

**Comment by nicojs** [comment]
>  and we need to keep the version 3.2.2 of TS...

Wow, that is scary. Try to upgrade it as soon as possible. More tools will get stuck on older versions if you're not carful.

> Is there any workardound that I could make to be able to run stryker on this project?

Well, you could try to remove `ts-jest` from the project and let jest transpile your files using `babel`. You can still run `tsc --noEmit` in your build pipeline to make sure you're not adding any type errors.

See https://jestjs.io/docs/en/getting-started#using-typescript

Make sure normal unit testing works first (without ts-jest), before trying to run Stryker.

**Comment by ralves20** [comment]
Hey @nicojs thanks!

But, does stryker@3 works with jest? I thought that was not supported

**Comment by nicojs** [comment]
Yes it does, just doesn't support coverage analysis (so set `"coverageAnalysis": "off"`)
