### ISSUE TITLE
Can you help me with this error? DryRunExecutor One or more tests resulted in an error

### ISSUE THREAD

**Issue by HeussGH** [stryker-mutator/stryker-js#2735]
I'm running stryker for the first time in an Angular project. 

some relevant project info:
```
"@stryker-mutator/core": "^4.4.1",
"@stryker-mutator/karma-runner": "^4.4.1",
"karma": "~5.0.0",
"@angular/cli": "~10.1.2",
```

stryker.conf:
```
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker/guides/angular",
  "mutate": [
    "src/**/*.ts",
    "!src/**/*.spec.ts",
    "!src/test.ts",
    "!src/environments/*.ts"
  ],
  "dryRunTimeoutMinutes": 15,
  "disableTypeChecks": "{test,src,lib}/**/*.{js,jsx,tsx,vue}",
  "testRunner": "karma",
  "karma": {
    "configFile": "karma.conf.js",
    "projectType": "angular-cli",
    "config": {
      "browsers": [
        "ChromeHeadless"
      ]
    }
  },
  "reporters": [
    "progress",
    "clear-text",
    "html"
  ],
  "concurrency": 2,
  "concurrency_comment": "Recommended to use about half of your available cores when running stryker with angular",
  "coverageAnalysis": "perTest"
}
```
I have been experimenting with the dryruntimeoutms setting and the disabletypechecks because stryker reports a ping timeout and at some point there was a type checking issue with an html file. I believe the rest is still the default settings I got when setting up Stryker.

When running stryker with 'npx stryker run --fileLogLevel trace --logLevel debug' it succesfully finds files and creates mutations. When it starts running tests however, I get hundreds of errors, most of which look something like this:

```
src/app/core/user-profile/user-profile.module.ts:62:19 - error TS2554: Expected 0 arguments, but got 1.
62     stryCov_9fa48(1563);
```

Then it reports 
```
15:16:21 (19936) DEBUG KarmaTestRunner karma run done with  1
15:16:21 (15324) ERROR DryRunExecutor One or more tests resulted in an error:
	DisconnectedClient disconnected from CONNECTED state (ping timeout)
```

Now to my question: how do I begin solving this? I don't have any idea what could be causing this problem. Can you give me any hints? I would be happy to provide the full log file to the devs in confidence if that helps.

**Comment by nicojs** [comment]
Are you by any change using TS<3.7?

**Comment by HeussGH** [comment]
Yes, my typescript version was quite outdated (below 3.7). I updated it and still got the same (or similar) errors. At the end it now says this:

`20:14:30 (22512) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (C:\Users\heuss\VSCodeProjects\kbsp\kbsp-private\node_modules\@stryker-mutator\core\src\process\3-dry-run-executor.js:59:15)
    at DryRunExecutor.timeDryRun (C:\Users\heuss\VSCodeProjects\kbsp\kbsp-private\node_modules\@stryker-mutator\core\src\process\3-dry-run-executor.js:69:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MergeMapSubscriber.project (C:\Users\heuss\VSCodeProjects\kbsp\kbsp-private\node_modules\@stryker-mutator\core\src\concurrent\pool.js:62:28)`

**Comment by nicojs** [comment]
Sorry for the late response. 

The error message seems cropped somehow. I'm missing the details about the failed test or another error message. Without more information, I cannot help you. Is there any way you could recreate your project setup in a clean repo and attach that here?

**Comment by SuperDrew** [comment]
If you're still getting type errors there's some info on that in the [troubleshooting guide](https://stryker-mutator.io/docs/stryker-js/troubleshooting#initial-test-run-fails). You may have source files that are outside the default folder locations that have type-checking disabled.
