### ISSUE TITLE
Custom tsconfig path throw "Cannot find module" error (compilerOptions.paths)

### ISSUE THREAD

**Issue by nya1** [stryker-mutator/stryker-js#2736]
**Question**

Hello,
I'm trying to add stryker to my current typescript project, but I'm unable to run the tests, it seems that the custom compilerOptions.paths present in my tsconfig.json is ignored.

this is the error

```
14:16:01 (21772) INFO DryRunExecutor Starting initial test run. This may take a while.
14:16:03 (21772) ERROR DryRunExecutor One or more tests resulted in an error:
	Error: MODULE_NOT_FOUND (undefined) Error: Cannot find module '@server/services'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/test/project/.stryker-tmp/sandbox1527714/test/testlib/onboarding.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/test/project/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/test/project/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
14:16:03 (21772) ERROR Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (/home/test/project/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:59:15)
    at DryRunExecutor.timeDryRun (/home/test/project/node_modules/@stryker-mutator/core/src/process/3-dry-run-executor.js:69:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Stryker environment**

```
├─┬ @stryker-mutator/core@4.4.1
│ ├─┬ @stryker-mutator/api@4.4.1
│ ├─┬ @stryker-mutator/instrumenter@4.4.1
│ │ ├── @stryker-mutator/api@4.4.1 deduped
│ │ ├── @stryker-mutator/util@4.4.1 deduped
│ ├─┬ @stryker-mutator/util@4.4.1
├─┬ @stryker-mutator/mocha-runner@4.4.1
│ ├── @stryker-mutator/api@4.4.1 deduped
│ ├── @stryker-mutator/util@4.4.1 deduped
├─┬ @stryker-mutator/typescript-checker@4.4.1
│ ├── @stryker-mutator/api@4.4.1 deduped
│ ├── @stryker-mutator/util@4.4.1 deduped
```

```
"mocha": "^7.1.2"
"ts-mocha": "^7.0.0"
"typescript": "^3.8.3"
```

**Additional context**

I'm using ts-mocha to run the tests with this command:

```
 "test:unit": "ts-mocha --project test/tsconfig.json -r tsconfig-paths/register 'test/**/*.spec.ts' --exit --timeout 15000",
```

test/tsconfig.json contains the following

```
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@server": ["../src"],
      "@server/*": ["../src/*"]
    }
  },
  "include": [ "." ]
}
```

this is my stryker config

```
{
  packageManager: "yarn",
  reporters: ["html", "clear-text", "progress"],
  testRunner: "mocha",
  commandRunner: {
    command: "yarn test:unit",
  },
  coverageAnalysis: "off",
  mutate: ["src/**/*.ts"],
  mochaOptions: {
    spec: ["test/**/*.spec.ts"],
    require: ["ts-node/register", "tsconfig-paths/register"]
  },
  tsconfigFile: "test/tsconfig.json"
};
```

**Comment by nicojs** [comment]
Hi nya1, you probably want to use [`--inPlace`](https://stryker-mutator.io/docs/stryker/configuration/#inplace-boolean) mode, since you're heavily relying on exact paths, this is why we added this new feature.

When you've got it working, you're probably unhappy with the performance at first (dependent on the size of your project). Speed thinks up drastically by enabling the `mocha` test runner. I see you already have some configuration for it. However, you're using `mocha-ts` in your normal unit test flow, which is currently, so you should try to recreate that with regular old `mocha` (which shouldn't be too dificult).

**Comment by EmmanuelRoux** [comment]
Hi @nicojs,
I'm encoutering the same issue. 

I have some *generated* code placed inside a specific directory at project root. Those files are excluded from git (and as such are not copied into Stryker sandbox directory).

It would be nice to have an option to copy **additional** files into sandbox (instead of the existing *files* option which would overwrite default - and require to have a very long list...)

Do you think it would be possible?

Thank you!

**Comment by nicojs** [comment]
Thanks. Does the current workaround (`--inPlace`) help you for now?

**Comment by nya1** [comment]
> Thanks. Does the current workaround (`--inPlace`) help you for now?

I've tried with `--inPlace` but I get the same error, it seems that my `test/tsconfig.json` configuration is ignored, because the '@server' imports are done in my test files but the path alias is not loaded

**Comment by Zialus** [comment]
Same problem here. Using `--inPlace` doesn't help.

**Comment by Zialus** [comment]
I just realized that the issue is actually module lazy loading

https://angular.io/guide/lazy-loading-ngmodules

The line

```typescript
    loadChildren: () => import('./items/items.module').then(m => m.ItemsModule)
```

is the problematic one.

If tell stryker not to mutate `app-routing.module.ts` then everything works fine!

**Comment by InfoSec812** [comment]
`inPlace` did not resolve this for me either... I have the following in my `tsconfig.json`:

```
"paths": {"@api/*": ["src/openapi/*"]}
```

When I run Stryker I get an error that modules starting with `@api/` cannot be resolved in the initial test run. So I am not even getting to the point of being able to mutate "in place".

**Comment by InfoSec812** [comment]
**SOLVED** Here's an update... In my Angular project we have a set of code under `src/openapi` which contains angular services. Stryker was not including that directory in the sandbox, and by adding a `files` config to include it this issue went away.

**Comment by InfoSec812** [comment]
Ahhh... Now I have dug in more deeply I realize it was because my generated code under `src/openapi` was being ignore via `.gitignore`. By default, Stryker will not copy ignored items into the mutation sandbox.

**Comment by nicojs** [comment]
@InfoSec812  @EmmanuelRoux  
Thanks for your comments. As of StrykerJS@5.0.0 we no longer rely on `.gitignore` files (they caused a bunch of edge cases to "not work"). So please, try to upgrade and let me know if it worked. See https://stryker-mutator.io/blog/announcing-stryker-js-5-brave-new-dimension.md

@Zialus thanks for your remark about module lazy loading

@nya1 can you confirm that (1) upgrading to v5 solves this issue? Or (2) you can confirm that this has to do with lazyloading?

**Comment by InfoSec812** [comment]
@nicojs Thanks for letting us know... I am not sure when I will have time to get back to testing this, but I will try to remember to report back here with my results.

**Comment by Zialus** [comment]
@nicojs files with module lazy loading are still able to make stryker fail

**Comment by nicojs** [comment]
@Zialus would you be able to create a small reproduction project? Would love to take a look! Please upload it in a new issue

**Comment by Zialus** [comment]
@nicojs I created the new issues with the reproduction example. Let me know if you need anything else ;)
