### ISSUE TITLE
Add an option to include additional files

### ISSUE THREAD

**Issue by EmmanuelRoux** [stryker-mutator/stryker-js#2739]
**Is your feature request related to a problem? Please describe.**

Related to: #2736

When some files ignores by git are needed to run Stryker, there are currently two workarounds:
- use the `inPlace` option to avoid using the sandbox
- use the `files` option to list **all** files that should be copied to sandbox

**Describe the solution you'd like**

Another nice option would be to have an option similar to `files` but allowing to specify only **additional** files.

**Comment by nicojs** [comment]
Would you be helped by a custom `.strykerignore` file as well? I prefer that solution myself (decoupling Stryker from git). https://github.com/stryker-mutator/stryker/issues/1593#issuecomment-605602494

**Comment by EmmanuelRoux** [comment]
@nicojs Yes, I think it would be a good option!

**Comment by nicojs** [comment]
I want to add this (breaking) change to Stryker v5

**Comment by nicojs** [comment]
(I mean #1593)

**Comment by nicojs** [comment]
@EmmanuelRoux I've opened #2848, please take a look. I think that should solve your issue.

I didn't want to go as far as to allow `.strykerignore` files, as that would add a lot of complexity (multiple `.strykerignore` files in multiple directories). Instead you can specify `ignorePatterns` in your stryker.conf.json.

**Comment by nicojs** [comment]
Closed with #2848

**Comment by EmmanuelRoux** [comment]
> @EmmanuelRoux I've opened #2848, please take a look. I think that should solve your issue.
> 
> I didn't want to go as far as to allow `.strykerignore` files, as that would add a lot of complexity (multiple `.strykerignore` files in multiple directories). Instead you can specify `ignorePatterns` in your stryker.conf.json.

@nicojs Thank you very much for this update, I’ll check that in a few weeks !
