### ISSUE TITLE
feature(instrumentor): Define specific mutants to instrument and don't mutate other mutants

### ISSUE THREAD

**Issue by Garethp** [stryker-mutator/stryker-js#2740]
**Is your feature request related to a problem? Please describe.**
What I want to be able to do is to rerun specific mutants that survived on the last run, and only those mutants. By doing this I can get a faster feedback loop when looking for mutants in my project.

**Describe the solution you'd like**
I'd like to be able to define mutants to be instrumented with the following specificity:
 * What file(s) to mutate (Yes, the `--mutate` command already serves this purpose, but I think specifying the file path will be necessary for creating an identity of the mutant that I desire
 * What character range(s) I want mutated. This would be in the format of defining a `startLine` and `startCharacterOffset` as well as `endLine` and `endCharacterOffset`. This should be a strict match, where any mutants who are *inside* those offsets without *matching* those offsets should be ignored

As an extra, if it were possible to specify:
 * What kind of mutation you want
 * What the mutation result is

That would allow greater control over specifying *which* mutants survived such as 
 * `const a = "default string"`
 * `const a = "";` (killed)
 * ` const a = "Stryker Was Here";` (survived)

I'm not sure how this data would be passed into the CLI command. With the level of specificity I'm looking for perhaps passing in a JSON string would be good, if user unfriendly. Perhaps there should be a user-friendly option where they just pass in locations such as `--specificMutants src/filename.ts::1:3::1:5,src/filename.ts::2:1::2:2` where the format would be `[filename]::[line:column]::[line:column]` and then a more tool-oriented input for JSON like `--specificMutantsJson`?
 
**Describe alternatives you've considered**
I considered creating a separate plugin that would act as a mutant filtering plugin, but it was suggested that this would be much better as a core functionality that might then be re-used for future incremental build functionality. I think that's a better idea and integrating it at the instrumentor level as opposed to post-instrumentation would also save some work since there would be less code to mutate over all.

**Additional context**
The overall context is that I have a IDE plugin that can run mutations, keep track of surviving mutants and when it comes to a "Rerun surving mutants" functionality can also keep track of the positions of the surviving mutants *after the source file has been edited*. This tool should hopefully be able to provide as much specificity as is needed in order to pinpoint the exact mutants that should be re-run.

**Comment by nicojs** [comment]
Hmm this is interesting. How about trying to keep it simple

`--mutate file:fromLine:Column:toLine:toColumn`

For example:

* `--mutate foo.js:1:0:5:0` would mutate foo.js from line 1 to line 5 (exclusive).
* `--mutate bar.js:1:4:1:20` would mutate bar.js only on line 1 between characters 4 and 20 (exclusive).

We would need to do some parsing magic to make sure [globbing still works as expected](https://github.com/isaacs/node-glob#glob)

**Comment by Garethp** [comment]
I think specifying mutants and using globs should be mutually exclusive. If you're specifying what mutants you want, does it make sense to be specifying text ranges for a non-specific file pattern? If we can detect if a filestring is a glob, we could throw an error if there's also lines/columns. On the other hand it's not like it'd hurt to let the user specify lines/columns for globs, I just don't see it as being a desirable effect

What do you think of having another interface for the more specific information such as mutation type and output?

**Comment by nicojs** [comment]
> On the other hand it's not like it'd hurt to let the user specify lines/columns for globs

Actually, it kind of does, since you could specify a position in the source file that doesn't exist. For example

```ts
/* 1 */ import foo from 'foo';
/* 2 */ 
/* 3 */ foo()
```

in this example line, 3 doesn't exist. Neither does line 3 column 9. It would be useful if we can give a clear error message, so users know that they did something wrong. 

I think not allowing glob expressions and locations to be mixed makes a lot of sense.

> What do you think of having another interface for the more specific information such as mutation type and output?

You mean mutator name and replacement 😉. If we would really want to provide those, then we would need something linke `--specificMutantsJson`. I personally don't see the need really. 

Maybe you can explain your exact use case. I have a hunch that it has to do with your IntelliJ plugin 😏, but maybe you want to elaborate a bit more?

**Comment by Garethp** [comment]
> Maybe you can explain your exact use case. I have a hunch that it has to do with your IntelliJ plugin 😏, but maybe you want to elaborate a bit more?

You're absolutely right! I put this in the context of the ticket, but I'll elaborate a bit

The idea of this feature in the intellij plugin is to imitate a feature for regular test frameworks where you can Re-run only failed tests. Implemented well, it could allow a user to run stryker over a set of files to see what mutations exist in the first place and then re-run only those mutants that have survived while they explore ways to write good tests to bust those mutants.

My personal workflow, and I suspect one that others use, is to go on "mutant busting" sessions once in a while over the whole codebase to see what I've missed over a couple weeks worth of development. Doing this means I tend to re-run my mutation tests **very** often, so being able to pinpoint only the mutants I'm focusing on can save a **lot** of time.

As for the specific use-case of `--specificMutantsJson` to allow for more information, I want to be able to make my "Re run surviving mutants" a rather smart command that *only* the mutants that survived, not other mutations of the same code that's already been busted. In the example that I posted for more specific options: 

```
const a = "default string"

Becomes:
Mutant 1: const a = ""; (killed)
Mutant 2: const a = "Stryker Was Here"; (survived)
```

If the user hits a "Re run surviving mutants button" the expected result would be that *only* Mutant 2 would run, because Mutant 1 is already dead. Having more control over exactly *which* mutants are generated for a given node, rather than just disabling nodes altogether, I can provide a smarter and more intuitive feature to the user.

If I were a user and a feature called "Re-run surviving mutants" ran both Mutant 1 and Mutant 2, I'd assume it was bug in the tool rather than an implementation detail to keep interfaces simple.

**Comment by nicojs** [comment]
If you only want to rerun the survived mutants, why don't we make that specific use case possible in that case?

This could use the `json` reporter. We can read the json file in and determine exactly which mutants survived the last time. We can then load the input files to verify if nothing changed, if it did, we can just decide to rerun all mutants for that file.

This is beginning to sound like `--diff` mode, except that one only reruns changed files (ignoring any tests that might have changed).

**Comment by Garethp** [comment]
> If you only want to rerun the survived mutants, why don't we make that specific use case possible in that case?

I'm happy to build that as a feature too, but with my plugin I also want to support the case of re-running only the failed mutants if the file *has* changed

**Comment by nicojs** [comment]
I see. Yes, rerunning on all `--survived` mutants is different than using `--diff` mode.

Maybe we could add a flag called `--survived`? It would rerun both survived and no-coverage mutants. It would have to rely on the `json` file format. You could then combine it with `--mutate` to be sure to only run survived mutants on a given file.

@simondel @hugo-vrijswijk do you have thoughts on this?

**Comment by wmeints** [comment]
I would love this feature for several reasons:

* Shorter feedback loop, since I need to mutate less files and less segments.
* More focused feedback. When I'm running mutation tests, I am essentially running around trying to splat them all. The less stuff I need to look at, the easier it becomes to splat them. Currently, I have to recheck the full report to see what mutants I need to splat next. That's really time consuming.

**Comment by HonzaMac** [comment]
Whole topic sounds to me like mutants cache or stryker cache. I can imagine, that just 'stryker run' would be enough to repeat with cache when I change only tests. When code, then run all.

**Comment by simondel** [comment]
@nicojs I think a --survived flag sounds very good. I would however only run survived mutants in source files that haven't changed since the last run. If the source files did change, they should all be tested again in my opinion.

By only changing your tests you could cause other mutants to survive which were previously killed, but this is not the case when you're adding tests.

**Comment by nicojs** [comment]
> Whole topic sounds to me like mutants cache or stryker cache. I can imagine, that just 'stryker run' would be enough to repeat with cache when I change only tests.

That's an interesting idea. I think we currently don't want to add that. We could add the `json` reporter to the default list of reporters, that way running `stryker run` would work.

Note: the JSON report currently _doesn't have enough information_ to do a proper diff run, nor is this feature request about a true "diff" run. It only contains info about the files under test, _not_ the test files. We're slowly adding that support, but it will take some time. I will create an issue for `--diff` mode when I have some time.
