### ISSUE TITLE
Warning about missing .gitignore despite not missing

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/stryker-js#2779]
**stryker init in $gitWorkingCopyDir/someSubDir/**

`stryker` seems to expect to be executed in the repository root, next to `.gitignore`, or have a local `.gitignore` available. 

Ideally it should use the same logic as git (look in parent directories for file) AND if not found, just create a `.gitignore` file in the current directory. It is valid to have multiple ignorefiles in subdirs in git.

**Comment by nicojs** [comment]
Yeah, I agree it would be helpful, however, it now works as intended. The warning specifies that you can add it yourself:

> No .gitignore file could be found. Please add the following to your .gitignore file: *.stryker-tmp
