### ISSUE TITLE
Plugin API to custom mutators

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker-js#2794]
**Is your feature request related to a problem? Please describe.**
For example, I want to try to write a mutator for vue template. As I can see, there are no way no do this as same as for JS/TS.

**Describe the solution you'd like**
For JS/TS code mutator plugin can simply provide a `NodeMutator[]` list that will be merged with default mutators.
For Vue template code this is more complex task. Now template is completely ignored (only scripts are extracted).

**Comment by nicojs** [comment]
I might like a custom mutator API in the future, but I'm hesitant to also open-up our parser and mutant-placer APIs here. I would rather take a babel approach, i.e. keep the parsing and instrumenting close to our chest and (maybe) support custom mutators.

As for vue file specific mutators, a couple of questions:

1. Would these mutators only work on `.vue` files, or also `.html` files and even `.ts`, `.tsx`, `.js` and `.jsx` files?
2. Would it be safe to enable these mutators by default? I.e. would they only work on `v-xxx` directives?

The current implementation of the instrumenter is heavily inspired by [prettier](https://github.com/prettier/prettier). They seem to work with any language/tool. Probably they are already parsing and formatting vue expressions for all file types (I know they do this for angular applications at least). We might be able to "steal" their solution of identifying and parsing vue expressions.
