### ISSUE TITLE
Bug: Cannot find module ... core/dist/bin/stryker within yarn workspaces repository

### ISSUE THREAD

**Issue by HonzaMac** [stryker-mutator/stryker-js#2802]
**Summary**

[Yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) seems to be not supported yet. 
I am having trouble to use "stryker run" on root package.json.

I've received this error:
```
$ stryker run
Cannot find module '/Users/user/projects/stryker/e2e/node_modules/@stryker-mutator/core/dist/bin/stryker'
Require stack:
- /Users/user/.nvm/versions/node/v12.18.4/lib/node_modules/stryker-cli/src/NodeWrapper.js
- /Users/user/.nvm/versions/node/v12.18.4/lib/node_modules/stryker-cli/src/stryker-cli.js
- /Users/user/.nvm/versions/node/v12.18.4/lib/node_modules/stryker-cli/bin/stryker-cli
```

**Stryker config**

See [e2e test for replication](https://github.com/stryker-mutator/stryker/pull/2803).

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 12.18.4
| npm              | 6.14.6
| Operating System |

**Add stryker.log**

**Comment by chris-grabcad** [comment]
I too am having this issue and use yarn workspaces - I have the following error: -

```
PS C:\Users\...> stryker init
Cannot find module 'C:\...\node_modules\@stryker-mutator\core\dist\bin\stryker'
Require stack:
- C:\Users\chris\AppData\Roaming\nvm\v12.14.1\node_modules\stryker-cli\src\NodeWrapper.js
- C:\Users\chris\AppData\Roaming\nvm\v12.14.1\node_modules\stryker-cli\src\stryker-cli.js
- C:\Users\chris\AppData\Roaming\nvm\v12.14.1\node_modules\stryker-cli\bin\stryker-cli
```

I'm using node 12.14.1 & yarn 1.22.10

**Comment by rob893** [comment]
I am also having this issue (except I chose npm instead of yarn for stryker init).
```
stryker init
Cannot find module 'F:\Projects\typescript-lru-cache\node_modules\@stryker-mutator\core\dist\bin\stryker'
Require stack:
- C:\Users\rwher\AppData\Roaming\npm\node_modules\stryker-cli\src\NodeWrapper.js
- C:\Users\rwher\AppData\Roaming\npm\node_modules\stryker-cli\src\stryker-cli.js
- C:\Users\rwher\AppData\Roaming\npm\node_modules\stryker-cli\bin\stryker-cli
111

**Comment by danielnoliveira** [comment]
Me to.
Cannot find module '/home/daniel/Code Universe/NodeJS/MutationTest/node_modules/@stryker-mutator/core/dist/bin/stryker'
Require stack:
- /home/daniel/.nvm/versions/node/v15.2.0/lib/node_modules/stryker-cli/src/NodeWrapper.js
- /home/daniel/.nvm/versions/node/v15.2.0/lib/node_modules/stryker-cli/src/stryker-cli.js
- /home/daniel/.nvm/versions/node/v15.2.0/lib/node_modules/stryker-cli/bin/stryker-cli

**Comment by kenzhemir** [comment]
The same issue with npm as well

```
Cannot find module '/Users/miraskenzhegaliyev/.../node_modules/@stryker-mutator/core/dist/bin/stryker'
Require stack:
- /Users/miraskenzhegaliyev/.nvm/versions/node/v12.16.0/lib/node_modules/stryker-cli/src/NodeWrapper.js
- /Users/miraskenzhegaliyev/.nvm/versions/node/v12.16.0/lib/node_modules/stryker-cli/src/stryker-cli.js
- /Users/miraskenzhegaliyev/.nvm/versions/node/v12.16.0/lib/node_modules/stryker-cli/bin/stryker-cli
```

**Comment by gss-patricia** [comment]
The same issue with yarn as well

Cannot find module '/home/patricia/_projects/admin-portal-pim-mfe/app/node_modules/@stryker-mutator/core/dist/bin/stryker'
Require stack:
- /home/patricia/_projects/admin-portal-pim-mfe/app/node_modules/stryker-cli/src/NodeWrapper.js
- /home/patricia/_projects/admin-portal-pim-mfe/app/node_modules/stryker-cli/src/stryker-cli.js
- /home/patricia/_projects/admin-portal-pim-mfe/app/node_modules/stryker-cli/bin/stryker-cli

**Comment by nicojs** [comment]
@Garethp pointed out to me that the issue was with `stryker-cli`, you are all using it (and installed it globally). We've restructured our packages as part of our 4.5 release and forgot to update `stryker-cli` (sorry 😢)

I think this issue is solved with https://github.com/stryker-mutator/stryker-cli/pull/42

Could you all try to update `stryker-cli` to `1.0.1`? That should fix it.

```shell
npm uninstall -g stryker-cli
npm install -g stryker-cli
# OR
yarn global remove stryker-cli
yarn global add stryker-cli
```

**Comment by nicojs** [comment]
I'm pretty sure this is solved with `stryker-cli@1.0.1`, feel free to comment if this is not the case, so I can reopen.

**Comment by HonzaMac** [comment]
Thank you @nicojs , it works now - I am able to run stryker!

**Comment by gss-patricia** [comment]
Same to me! Than you @nicojs
