### ISSUE TITLE
Generate mutant only for the changed lines in a range of commits

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [stryker-mutator/stryker-js#2843]
**Is your feature request related to a problem? Please describe.**
The mutation test is very expensive and time-consuming in medium and large projects, and its execution in all Pull Requests is not feasible. That is why we have adopted the following strategy:
1. We perform a complete mutation test once a day.
2. We perform mutation testing only on changed files using the stryker-diff-runner library (https://www.npmjs.com/package/stryker-diff-runner).

The problem is that even selecting which files to run the mutation test ends up being time consuming and it also forces the disabling of the break threshold, as it generates mutants for the entire file, and not for the changed lines.
Something that would help users of the Striker library to use it routinely, in every code change, would be to have an option to _generate mutation test only for the changed lines in a given range of commits_.

**Describe the solution you'd like**
Provide an option via CLI to pass the range of commits, like `--range`.

Example (default branch is `main`):
```json
"scripts": {
  "test:mutation": "stryker run",
  "test:mutation:diff:last-commit": "stryker run --range 'HEAD'",
  "test:mutation:diff:actual-branch-to-default": "stryker run --range 'origin/main..HEAD'"
}
```

**Describe alternatives you've considered**
This solution came to mind when I saw this comment from @nicojs: https://github.com/stryker-mutator/stryker-js/issues/2740#issuecomment-776714344

**Additional context**
N/A

**Comment by rene-leanix** [comment]
Would something like this work for you in the meantime?

```bash
npx stryker run --mutate $(git diff --name-only HEAD $(git merge-base HEAD origin/main) -- "*.ts" ":(exclude)*.spec.ts" | tr '\n' ',' | sed 's/,$//')
```

The downside of this approach is that the path globs specified in the Stryker config file would need to be replicated here. Alternatively one could create a short NodeJS script to execute this command based on those path globs.

The best long-term solution seems to be the incremental-mode suggested in #2753.

**Comment by PauloGoncalvesBH** [comment]
@rene-leanix this solution makes it generate mutant for the entire file, and what I'm looking for is that it generates mutant only for the changed lines in certain commits.
This suggestion you provided is similar to what the stryker-diff-runner library does.
https://github.com/tverhoken/stryker-diff-runner/blob/e2ecb3d15cc5093c981c1d26891f53cf8f7165e1/src/index.ts#L32

**Comment by nicojs** [comment]
We've recently added support to mutate a specific range only, see https://stryker-mutator.io/docs/stryker-js/configuration#mutate-string

Example: `stryker run --mutate foo.js:25-30`
