### ISSUE TITLE
stryker stay stuck for a very little project

### ISSUE THREAD

**Issue by sarahBuisson** [stryker-mutator/stryker-js#2924]
I've install stryker on a boiler plate angular , and when I launch it, it stay stuck

There is almost no test nor file to mutate:

```
ng new stryker-test
cd stryker-test
npm install --save-dev @stryker-mutator/core
stryker init
npm install
npx stryker run
```

the logs : 
15:26:11 (1504) INFO ConfigReader Using stryker.conf.json
15:26:11 (1504) INFO InputFileResolver Found 4 of 33 file(s) to be mutated.
15:26:11 (1504) INFO Instrumenter Instrumented 4 source file(s) with 5 mutant(s)
15:26:11 (1504) INFO ConcurrencyTokenProvider Creating 8 test runner process(es).

**Comment by nicojs** [comment]
I've tried to reproduce it, but couldn't. I've ran `npx stryker run
