### ISSUE TITLE
Mutants that should be killed, aren't

### ISSUE THREAD

**Issue by SuperDrew** [stryker-mutator/stryker-js#2933]
**Summary**

Some mutants that cause test failures when manually inserted into the code aren't killed by running mutation.

If you attempt to manually see if the mutants are killed by the tests you'll find they are. For example, replacing
```
if (value != 'true' && value != 'false') {
```
with
```
if (true) {
```
fails the tests, however in the report this mutant isn't killed:
![image](https://user-images.githubusercontent.com/11270002/120636866-17352800-c466-11eb-9c07-1e67bed4e381.png)

Apologies if I'm missing something obvious and this isn't a bug 🙈 If there's any other information I can provide please let me know!

**Reference**

I created [a branch](https://github.com/SuperDrew/typescript-base/tree/stryker-example) with the simplest possible reproduction of the issue. You should be able to check it out, `npm i` and `npm run mutate`. The files below are copies from that repo.

**Stryker config**
```javascript
module.exports = {
  packageManager: "npm",
  mutate: ['src/main/*.ts'],
  reporters: ["html", "clear-text", "progress"],
  testRunner: "jest",
  jest: {
    enableFindRelatedTests: true,
    configFile: './jest.config.js'
  },
  coverageAnalysis: 'perTest'
};

```

**Test runner config**

```javascript
module.exports = {
    testEnvironment: 'node',
    roots: ['<rootDir>/src/test'],
    transform: {
      '^.+\\.tsx?$': 'ts-jest',
    },
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  }
```

**Stryker environment**

```
    "@stryker-mutator/core": "^5.0.1",
    "@stryker-mutator/jest-runner": "^5.0.1",
```

Test runner

```
    "jest": "^25.1.0",
```

**Test runner environment**

```shell
npm start
```

The test config is the same as `jest.config.js` above.

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v12.22.1
| npm              | v6.14.12
| Operating System | Ubuntu 20.04.2 LTS

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker-js/files/6591249/stryker.log)

**Comment by nicojs** [comment]
Thanks for the extensive bug report! Something strange is going on here. It seems to be related to `enableFindRelatedTests`. If you disable that setting, you will get the expected result.

I'm investigating this issue now.

**Comment by nicojs** [comment]
I think I found the issue.

I've tried to run the `--findRelatedTests` feature from the command line and that doesn't work either:

```shell
~/github/typescript-base (stryker-example)$ npx jest --findRelatedTests src/main/example.ts
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in /home/nicojs/github/typescript-base.
...
Pattern: src/main/example.ts - 0 matches
```

The reason for this seems to be your _roots_ setting (`roots: ['<rootDir>/src/test']`). Apparently, `--findRelatedTests` only works when the targetted file is inside one of the roots. 

Changing `roots` to something like this works:

```diff
-    roots: ['<rootDir>/src/test'],
+    roots: ["<rootDir>/src/main", "<rootDir>/src/test/"],
```

**Comment by nicojs** [comment]
I've reported this to the jest team, hopefully we can fix it in their code base: https://github.com/facebook/jest/issues/11527

**Comment by SuperDrew** [comment]
Awesome, thank you for figuring this out @nicojs ! I've tried your solution in the example repo and it fixes it. I'll try it out in our production repo and see if the fix translates. Thank you again 👍🏼

**Comment by SuperDrew** [comment]
Done in our prod repo and it works too. I saw a strange oddity where sometimes the result flips back to the previous state, without any code changes, but I've been unable to reproduce it reliably.

@nicojs I'm not sure of the etiquette, I think this issue is complete, can I close it?

**Comment by nicojs** [comment]
No, I think Stryker should support your use case out of the box. I'm working on a fix 👷‍♂️.

**Comment by SuperDrew** [comment]
Many thanks @nicojs !
