### ISSUE TITLE
Unable to kill any mutant with simple code

### ISSUE THREAD

**Issue by blephy** [stryker-mutator/stryker-js#2938]
# Question

I,

I'm unable to kill any mutant in my codebase. I tryed a lot of stryker configuration and this does not change anything. I think my test runner don't report any coverage to stryker or something like this.

I'm running styker on a large codebase but i only selected one folder to tests. I'm using Angular with Jest.

1. First of all, with the configuration below, stryker mutate only files in this folder but is running jest in all the codebase. Is it normal ?
2. Running stryker without `inPlace` result on a timeout for the initial tests run.
3. With `inPlace` option, initial tests runs but all of them are reporting 0% coverage.

The Striker stdout without `inPlace` option

```bash
14:59:04 (1696) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
15:04:03 (8124) DEBUG TimeoutDecorator Timeout expired, restarting the process and reporting timeout
15:04:05 (8124) DEBUG ChildProcessProxy Disposing of worker process 16364
15:04:07 (8124) DEBUG ChildProcessProxy Kill 16364
15:04:07 (8124) DEBUG ChildProcessProxy Started ChildProcessTestRunnerWorker in child process 6004
15:04:10 (8124) ERROR DryRunExecutor Initial test run timed out!
```

### My Stryker configuration

```js
module.exports = {
    mutate: ["src/app/@core/store/json-api/utils/sort/**/*.ts", "!src/**/*.routes.ts", "!src/**/*.spec.ts", "!src/environments/*.ts"],
    ignorePatterns: [".vscode/**/*", "coverage/**/*", "dist/**/*", "cypress/**/*", "reports/**/*", "documentation/**/*"],
    testRunner: "jest",
    jest: {
        configFile: "jest.config.js",
        projectType: "custom"
    },
    reporters: ["progress", "clear-text", "html", "json", "dots"],
    htmlReporter: { baseDir: "reports/stryker" },
    jsonReporter: { fileName: "reports/stryker/mutation.json" },
    coverageAnalysis: "perTest",
    checkers: ["typescript"],
    tsconfigFile: "config/stryker/tsconfig.stryker.json",
    concurrency: 4,
    // dryRunTimeoutMinutes: 20,
    tempDirName: "stryker-tmp",
    inPlace: true,
    fileLogLevel: "trace",
    logLevel: "debug",
};
```

### My Jest configuration

```js
require("jest-preset-angular/ngcc-jest-processor");

module.exports = {
    verbose: true,
    preset: "jest-preset-angular",
    rootDir: ".",
    roots: ["<rootDir>/src"],
    setupFilesAfterEnv: ["<rootDir>/config/jest/after-env.setup.ts"],
    moduleNameMapper: {
        "^@core/(.*)$": "<rootDir>/src/app/@core/$1",
        "^@shared/(.*)$": "<rootDir>/src/app/@shared/$1",
        "^@environments/(.*)$": "<rootDir>/src/environments/$1"
    },
    collectCoverageFrom: [
        "<rootDir>/src/app/**/*.{ts,js}",
        "!**/node_modules/**",
        "!<rootDir>/src/main.ts",
        "!<rootDir>/src/polyfills.ts",
        "!<rootDir>/src/environments/**",
        "!<rootDir>/src/**/*.routes.ts",
        "!<rootDir>/src/**/*.interface.ts",
        "!<rootDir>/src/**/*.mock.ts"
    ],
    coverageReporters: ["json", "lcov", "text", "clover", "cobertura"],
    coverageDirectory: "<rootDir>/reports/jest",
    testPathIgnorePatterns: ["/node_modules/"],
    globals: {
        "ts-jest": {
            tsconfig: "<rootDir>/tsconfig.spec.json"
        }
    },
    displayName: {
        name: "PMSI",
        color: "blue"
    }
};
```

## Some simple code

Code to test

```ts
/**
 * Separator
 */
export const serparator = ",";
```

Related spec tests

```ts
describe("Separator constant", () => {
    it("should be truthy", () => {
        expect.assertions(1);
        expect(serparator).toBeTruthy();
    });

    it("should be egual to `,`", () => {
        expect.assertions(1);
        expect(serparator).toStrictEqual(",");
    });
});
```

The stryker result

```bash
# every jest tests are resulting like
# 
      ✘ Categories errors Filter should have a `CATEGORIES_ERRORS_FILTER_KEY` constant [line 4287] (covered 0)
      ✘ Categories errors Filter should have a `CATEGORIES_ERRORS_FILTER_PLACEHOLDER` constant [line 4287] (covered 0)
      ✘ SearchValue should have a `NDA_SSR` constant [line 4287] (covered 0)
      ✘ SearchValue should have a `PATIENT_NAME` constant [line 4287] (covered 0)

#0. [Survived] StringLiteral
src/app/@core/store/json-api/utils/sort/sort.constants.ts:12:27
-   export const serparator = ",";
+   export const serparator = "";
Ran all tests for this mutant.

# stryker coverage
# 
Ran 0.00 tests per mutant on average.
-------------------|---------|----------|-----------|------------|----------|---------|
File               | % score | # killed | # timeout | # survived | # no cov | # error |
-------------------|---------|----------|-----------|------------|----------|---------|
All files          |    0.00 |        0 |         0 |         17 |        0 |       4 |
 sort.constants.ts |    0.00 |        0 |         0 |          2 |        0 |       0 |
 sort.ts           |    0.00 |        0 |         0 |         15 |        0 |       4 |
-------------------|---------|----------|-----------|------------|----------|---------|
```

## Some additionnal jest configuration in package.json

```json
"jest-junit": {
        "outputDirectory": "reports/jest",
        "outputName": "junit.xml",
        "classNameTemplate": "{classname}",
        "titleTemplate": "{title}"
    },
"jest": {
    "testResultsProcessor": "jest-sonar-reporter"
},
"jestSonar": {
    "reportPath": "reports/jest",
    "reportFile": "unit-test-execution-report.xml",
    "indent": 4
},
```

## What did i tried

- Not using `inPlace` option (timeout in initial jest run). Same by adding `dryRunTimeoutMinutes` to `20`
- Changing the `tempDirName` option with `stryker-tmp` (same result)
- Add `enableFindRelatedTests: false` in stryker custom jest config (same result)
- All `coverageAnalysis` options (same result)
- Forcing stryker to run jest with `ng test` to use @angular-builders/jest with `commandRunner` options (same result). With `ng test --collect-coverage --reporters=default` changed nothing

## Stryker environment

├── @stryker-mutator/core@5.0.1
├── @stryker-mutator/jest-runner@5.0.1
├── @stryker-mutator/typescript-checker@5.0.1
├── jest@26.6.3
├── @angular/cli@11.2.11
├── @angular-builders/jest@11.2.0
├── jest-preset-angular@8.4.0
├── ts-jest@26.5.5
├── typescript@4.1.5
├── ts-node@8.3.0

Regards,

**Comment by blephy** [comment]
I finally get it working with this Stryker configuration (running with `npx stryker run`) : 

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
    mutate: [
        "src/app/@core/store/json-api/utils/sort/**/*.ts",
        "!src/**/*.routes.ts",
        "!src/**/*.mock.ts",
        "!src/**/*.spec.ts",
        "!src/environments/*.ts"
    ],
    ignorePatterns: [".vscode/**/*", "coverage/**/*", "dist/**/*", "cypress/**/*", "reports/**/*", "documentation/**/*"],
    testRunner: "jest",
    jest: {
        configFile: "jest.config.js",
        projectType: "custom",
        enableFindRelatedTests: false
    },
    // commandRunner: {
    //     command: "ng test --collect-coverage"
    // },
    reporters: ["progress", "clear-text", "html", "json", "dots"],
    htmlReporter: { baseDir: "reports/stryker" },
    jsonReporter: { fileName: "reports/stryker/mutation.json" },
    coverageAnalysis: "perTest",
    checkers: ["typescript"],
    tsconfigFile: "config/stryker/tsconfig.stryker.json",
    concurrency: 4,
    dryRunTimeoutMinutes: 15,
    // tempDirName: "stryker-tmp",
    // inPlace: true,
    fileLogLevel: "trace",
    logLevel: "debug"
};
```

Do you have any explication to this behavior ?

**Comment by nicojs** [comment]
This might have the same cause as #2933, although it does seem that you have your roots correctly configured, because `["<rootDir>/src"]` includes your tests as well. 

Could you try the `jest` command with `--findRelatedTests`?

Something like this for example: `npx jest --findRelatedTests src/app/@core/store/json-api/utils/sort/path/to/a/file.ts`, does that work?

**Comment by blephy** [comment]
Hi @nicojs 

Thanks for your answer.

Yeah i read this issue. And many other ones before opening this one.
Yes, my jest unit test are in the same folders as the application codebase. Pattern is `app.component.ts` | `app.component.spec.ts` in the same folder.

Results of my tests based on your request :  

- ` npx jest --findRelatedTests src/app/app.module.ts` : Result is ok. Jest is testing 2 files, app.module.ts and app.component.ts. But time for the test are increadibly long ! 117 second for app.module.spec.ts and 121 second for app.component.spec.ts
- `npx jest --findRelatedTests src/app/@core/store/json-api/utils/sort/sort.ts` failed. i don't understand why because there is a sort.spec.ts near to it. The stdout :  

```bash
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\xxxxx\Projects\xxxxxxxxxxxxxx
  977 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 333 matches
  testPathIgnorePatterns: \\node_modules\\ - 977 matches
  testRegex:  - 0 matches
Pattern: src\\app\\@core\\store\\json-api\\utils\\sort\\sort.ts - 0 matches
```

- `npx jest --findRelatedTests src/app/@core/store/json-api/utils/sort/**`. Jest don't understand and start to launch all tests instead `Invalid testPattern src\\app\\@core\\store\\json-api\\utils\\sort\\** supplied. Running all tests instead.` 
- `npx jest --findRelatedTests src/app/@core/store/json-api/utils/sort/*.ts`. Jest understand the pattern but don't find any tests in the folder, which is not right. I'm sure about the path.

```bash
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\xxxxxx\Projects\xxxxxxxxxxxxxx
  977 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 333 matches
  testPathIgnorePatterns: \\node_modules\\ - 977 matches
  testRegex:  - 0 matches
Pattern: src\\app\\@core\\store\\json-api\\utils\\sort\\*.ts - 0 matches
```

- `npx jest --findRelatedTests src/app/@core/store/store.ts` is the same. no related spec file found.

I think our folder pattern name are causing jest to fail to find related spec files when there is special charaters in the path.
I tryed  with single quote or double quote and this is the same behavior.

Should we open an issue in jest repository ?

**Comment by blephy** [comment]
@nicojs  Waiting your expertise ;)

https://github.com/facebook/jest/issues/11534#issuecomment-855450673

**Comment by blephy** [comment]
I think we can close it now :)

**Comment by nicojs** [comment]
Maybe keep it open until `jest@27.0.5` (or `jest@27.1.0`) releases

**Comment by nicojs** [comment]
@blephy  `jest@27.0.5` got released yesterday. Could you please confirm that it now works out-of-the box with Stryker?

**Comment by blephy** [comment]
@nicojs yes I will test it this week !

**Comment by blephy** [comment]
@nicojs sorry for the delay.

Here is an update of the repository which help us to demonstrate the issue. I'm linking you the CI which runs on multiple OS and node versions.

- https://github.com/blephy/jest-path-bug
- https://github.com/blephy/jest-path-bug/actions/runs/1011664944

The bug is fixed but it seems that `--findRelatedTests` with special character like `(` needs to be encapsulated in quote.

Thanks for the work. We can close the issue.

**Comment by nicojs** [comment]
Thanks! Closing issues is my specialty, always makes me happy 😉
