### ISSUE TITLE
Non-matching peerDependency `jest-runner` -> `core` in 5.1.0

### ISSUE THREAD

**Issue by lauraseidler** [stryker-mutator/stryker-js#2955]
**Summary**

The `jest-runner` package declares a peer dependency on `"@stryker-mutator/core": "~5.0.0"`: 

https://github.com/stryker-mutator/stryker-js/blob/5c1390982dad85c401c39151e2ce0767f28c6e49/packages/jest-runner/package.json#L55

This doesn't allow to install `jest-runner` and `core` with v5.1.0, as the `~` only allows patch updates. I assume this should either be a fixed version and updated via lerna for new releases, or a `^` to also allow for minor version releases.

Happy to provide a PR if someone can tell me which way to go :) (tho a maintainer will probably be quicker with this)

**Comment by nicojs** [comment]
yeah, you're right. Updating peer deps is still a manual process which I forget sometimes... Fixing now.

**Comment by nicojs** [comment]
Fixed in  v5.1.1

**Comment by lauraseidler** [comment]
@nicojs thanks a bunch!
