### ISSUE TITLE
How to se propper configuration for stryker

### ISSUE THREAD

**Issue by SDolnutu** [stryker-mutator/stryker-js#2958]
**Question**

Does stryker always run the karma runner regardless if it is declared as test runner in the stryker configuration file, i am using jest configuration?

I am receiving the following messages:

`14:15:46 (4404) INFO ConfigReader Using stryker.conf.js
14:15:46 (4404) WARN PluginLoader Cannot find plugin "C:\Users\myUser\IdeaProjects\solution-builder\node_modules\@stryker-mutator\karma-runner".
  Did you forget to install it ?
  npm install C:\Users\myUser\IdeaProjects\solution-builder\node_modules\@stryker-mutator\karma-runner --save-dev
14:15:49 (4404) WARN InputFileResolver Glob pattern "src/**/*.ts" did not result in any files.
14:15:49 (4404) WARN InputFileResolver Glob pattern "!=src/**/*.spec.ts" did not exclude any files.
14:15:49 (4404) WARN InputFileResolver Glob pattern "!src/test.ts" did not exclude any files.
14:15:49 (4404) WARN InputFileResolver Glob pattern "!src/environments/*.ts" did not exclude any files.
14:17:00 (4404) WARN InputFileResolver No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your config file (or use `--mutate` via command line
).
`
and the lines for the karma runner are being repeated for several minutes until i get error for the initial test run (presumably the default time of 5 minutes):

`14:23:15 (4404) ERROR DryRunExecutor Initial test run timed out!
14:23:15 (4404) ERROR Stryker Unexpected error occurred while running Stryker Error: Something went wrong in the initial test run
`
**I think this might have something to do with the fact that stryker is performing a dry-run!**

My configuration file looks like this ->

`/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  _comment:
    "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/angular",
  mutate: [
    "src/**/*.ts",
    "!=src/**/*.spec.ts",
    "!src/test.ts",
    "!src/environments/*.ts",
  ],
  testRunner: "jest",
  "jest": {
    "projectType": "custom",
    "configFile": "jest.config.js",
    "config": {
      "testEnvironment": "jest-environment-jsdom-sixteen"
    },
    "enableFindRelatedTests": true,
  },
  reporters: ["progress", "clear-text", "html"],
  concurrency: 4,
  concurrency_comment:
    "Recommended to use about half of your available cores when running stryker with angular",
  coverageAnalysis: "perTest",
};
`

**Stryker environment**

Im trying to run stryker mutation tests again angular/cli

```
"@stryker-mutator/core": "^5.1.1",
"@stryker-mutator/jest-runner": "^5.1.1",
"@stryker-mutator/karma-runner": "^5.1.1",
"jest-environment-jsdom-sixteen": "^2.0.0",
```

``
+-- jest@5.1.1
```

**Additional context**

Our system uses jest as a testing framework, thats the reason behind the fact that i want to use jest. 
Also i have tried deleting my package-lock.json and install karma, but it still not found, plus im not sure if it should be triggered when im using jest.

**Comment by nicojs** [comment]
Hi @SDolnutu . Stryker will always try to load all installed Stryker plugins by default (nodejs modules within `node_modules/@stryker-mutator/` directory). Since you have the `@stryker-mutator/karma-runner` installed, it will also try to load that. The reason why Stryker fails to load it is probably that it cannot `require('karma')`. You remove the runner from your project:

```shell
npm uninstall @stryker-mutator/karma-runner
# OR
yarn remove @stryker-mutator/karma-runner
```

The reason why you see this error multiple times, is that worker processes also load all Stryker plugins. So it will fail with the same error there. I agree that this is a strange error we can improve on.

The jest test runner is actually used n this case (because you configured it with `testRunner: 'jest'`). So this won't solve your initial test runner timeout.

How long does a normal jest run take in your project with `--runInBand`? Is it longer than 5 minutes?

**Comment by SDolnutu** [comment]
@nicojs Thanks for the quick reply!
I uninstalled the karma-runner, but i would say that it seems a bit counter intuitive for the behavior to be as such, because i didnt have the option to select which testing framework i wanted, karma was installed by default. 
Nevertheless now the karma-runner dependency is not present and the warning message no longer appears.
**However i keep on getting the dry runner as show below:**

```
14:50:30 (23816) WARN InputFileResolver No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your config file (or use `--mutate` via command lin
e).
14:50:30 (23816) INFO Instrumenter Instrumented 0 source file(s) with 0 mutant(s)
14:50:40 (23816) INFO ConcurrencyTokenProvider Creating 4 test runner process(es).
```
What might be the cause of this? 

"How long does a normal jest run take in your project with --runInBand? Is it longer than 5 minutes?" - yes my project is a commercial one and it has a pretty substantial amount of test cases, so the runtime for the test would be quite longer than 5 minutes!
And yes i keep on getting the ERROR DryRunExecutor Initial test run timed out! Does the dry runner always run before the real test or just in my case because stryker does not manage to mutate anything?

**Comment by frankm** [comment]
Just solved this issue for me. This is not a helpful message: **WARN InputFileResolver No files marked to be mutated**

This might be more helpful, "Source code cannot be found in default mutate-string directory: src". None of the documentation or tutorials mentioned putting the code inside a directory named "src".

Once you know that, you can fix it or customize the name and path of the directory using this link: https://stryker-mutator.io/docs/stryker-js/configuration#mutate-string

**Comment by nicojs** [comment]
Good point. We should improve this error message. 

Did you have a look at our [troubleshooting guide](https://stryker-mutator.io/docs/stryker-js/troubleshooting/)? I notice that this problem is missing there, should be an easy fix to add it there as well.
