### ISSUE TITLE
Support only run the initial test run (dry run)

### ISSUE THREAD

**Issue by karfau** [stryker-mutator/stryker-js#3088]
**Question**

Since our stryker run takes around 2 hours to complete we currently only run it on the default branch.
It would be nice if we could still execute just the initial test run in branches to avoid that it fails on master and we need to figure out why it broke/revert...

**Stryker environment**

```
+-- @stryker-mutator/core@^5.2.2
```

```
+-- jest@^27.0.6
```

**Additional context**

**Comment by nicojs** [comment]
My hopes are that running unit tests normally is enough. You generally want to share the test runner configuration with stryker using `jest.config.js`, `.mocharc.json`, etc. That way, Stryker should have no issues running your tests.

That being said, there are still slight differences for Stryker vs your test runner. I think this will work: `npx stryker run -m not-exists.js`.

We might want to add a `--dry-run` in the future, to only run the dry run.

**Comment by karfau** [comment]
Ok, i just checked what `-m` means and it refers to https://stryker-mutator.io/docs/stryker-js/configuration#mutate-string
So it would also work yo have an additional config file with `"mutate": []`, right?
I wonder if we can pass an "empty glob/list" from the cli instead of a non existing file?
Most likely will experiment with this very soon.

As a side note: maybe it's worth documenting this behavior of the option? Something like
> Passing a glob that matches no files will cause a "dryrun": The configuration will be read and the tests will be run once, but no files will be mutated.

(I'm very curios about the expected exit code when using this approach...)

**Comment by nicojs** [comment]
Great, that's what I was afraid of. Please open an issue for the instrumentation error, we'll use this issue to track progress on the dry-run feature

**Comment by nicojs** [comment]
We probably still want this feature.
