### ISSUE TITLE
Disallow running mutants on lines containing a specific pattern

### ISSUE THREAD

**Issue by edi9999** [stryker-mutator/stryker-js#3090]
**Is your feature request related to a problem? Please describe.**

Kindof, in my code, I know that some parts of my code are not tested as they are messages that I don't really care that much of, and testing them would be more hassle than what's worth.

Specifically, my code is like this : 

```
// App code 
function throwXmlInvalid(content, offset) {
	const err = new XTTemplateError("An XML file has invalid xml");
	err.properties = {
		id: "file_has_invalid_xml",
		content,
		offset,
		explanation: "The docx contains invalid XML, it is most likely corrupt",
	};
	throw err;
}
// Test code
try {
    throwXmlInvalid("abc", 10);
} catch (e) {
   myError = e;
}
expect(myError.id).to.equal("file_has_invalid_xml");
expect(myError.content).to.equal("abc");
```

I don't really care that my test will still succeed if the code is mutated to the following : 

```
function throwXmlInvalid(content, offset) {
	const err = new XTTemplateError("An XML file has invalid xml");
	err.properties = {
		id: "file_has_invalid_xml",
		content,
		offset,
		explanation: "",
	};
	throw err;
}
```

**Describe the solution you'd like**
It would be cool to be able to disallow to aplly mutations on lines matching a given pattern.

Ideally, one could write : 

```
module.exports = {
	ignoreLines: [/explanation:/],
}
```

**Comment by nicojs** [comment]
We're currently implementing the ignore proposal: #1472 

Would you be helped by that?

**Comment by edi9999** [comment]
Yes, more specifically the third point from there :

> 
>    1. // stryker-mutator disable next or /* stryker-mutator disable next */: this would disable all mutators Stryker on the next AST node (statement)
>    2. // stryker-mutator disable next ['StringLiteral'] or /*stryker-mutator disable next ['StringLiteral']*/: this would only disable the StringLiteral mutator for the next AST node (statement).
>    **3. We might also want to allow people to exclude some patterns via stryker configuration. First, we would need to implement basic ignoring.**

Because I have this "explanation:" part for about 50 times, and I don't want to add `/* stryker-mutator disable next */` 50 times in the same file.

**Comment by edi9999** [comment]
I'm closing this since this is really the same as : https://github.com/stryker-mutator/stryker-js/issues/2966
