### ISSUE TITLE
Takes about 2x the time running stryker after this change in code.

### ISSUE THREAD

**Issue by dominikzogg** [stryker-mutator/stryker-js#3136]
**Question**

Running jest takes a few seconds, but infection testing takes very long.

It seems its cause the following change, but i have no idea why

from

```ts
public async process(
    request: ServerRequestInterface,
    handler: RequestHandlerInterface,
): Promise<ResponseInterface> {
    try {
        return await handler.handle(request);
    } catch (e) {
        return this.handleError(e);
    }
}
```

to

```ts
public async process(
    request: ServerRequestInterface,
    handler: RequestHandlerInterface,
): Promise<ResponseInterface> {
    return new Promise((resolve) => {
        handler
            .handle(request)
            .then((response) => {
                resolve(response);
            })
            .catch((error) => {
                resolve(this.handleError(error));
            });
    });
}
```

Do you have any idea why?

**Stryker environment**

```
+-- @stryker-mutator/core@5.4.0
```

```
+-- jest@27.2.0
```

**Comment by simondel** [comment]
Thanks for opening this issue! How many mutants are generated in both cases?

**Comment by dominikzogg** [comment]
Its not 3x time in this run, but close to 2x

await: killed 37, timeout: 2 (27 Seconds)
promise: killed 27, timeout: 13 (47 Seconds)

**Comment by dominikzogg** [comment]
13x timeout is probably the reason

**Comment by kmdrGroch** [comment]
It is most likely yes. During performance testing some time ago we have noticed during timeout process is being restarted which gives some overhead, and timeout means it couldn't finish work in given time (which means it was stuck for that time),

So if we assume you run 30tests,
Good takes .1s and timeout 3s:
20good/10timeout - 32s
10good/20timeout - 61s

Unfortunately the only thing we/you could do is reduce timeout time

**Comment by dominikzogg** [comment]
@kmdrGroch thanks for clarification

**Comment by kmdrGroch** [comment]
I can't remember the option on top of my head, but try looking for timeout configuration in Stryker. Change value there and see results in both cases :)
