### ISSUE TITLE
TypeScript checker performance cost

### ISSUE THREAD

**Issue by ThierryRietveld** [stryker-mutator/stryker-js#3137]
When this plugin is enabled it comes with a big performance hit. This is a known issue for the Stryker team. I can't assign people to this issue, but a colleague and I are working on a solution.

**Comment by blephy** [comment]
If you are running jest with ts-jest, did you try `transpileOnly` property in your jest `tsconfig` ? 

tsconfig.jest.json

```json
{
    "extends": "tsconfig.json",
    "compilerOptions": {
        ...
    },
    "ts-node": {
        "transpileOnly": true
      },
}
```
