### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/api' is not defined by "exports"

### ISSUE THREAD

**Issue by amiceli** [stryker-mutator/stryker-js#3143]
**Summary**

I'm using stryker in my Vue/Typescript project. When in run stryker I've following error : 

    [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/api' is not defined by "exports

**Stryker config**

```js
module.exports = function (config) {
    config.set({
        mutate: [
            "src/Application/Pagination.ts",
        ],
        mutator: "vue",
        testRunner: "jest",
        tsconfigFile: './tsconfig.json',
        reporters: ['progress', 'clear-text', 'html'],
        coverageAnalysis: 'off',
        files : [
            'src/**/*',
            'tests/**',
            './babel.config.js'
        ]
    })
}

```

**Test runner config**

My Jest config file : 

~~~js
const aliasConfig = require('./alias.config')

module.exports = {
    moduleFileExtensions : [
        'js',
        'jsx',
        'json',
        'vue',
        'ts',
        'tsx',
    ],
    coverageReporters : ['html'],
    transform : {
        '^.+\\.vue$' : 'vue-jest',
        '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$' : 'jest-transform-stub',
        '^.+\\.tsx?$' : 'ts-jest',
    },
    moduleNameMapper : {
        ...aliasConfig.jest,
        '^@/(.*)$' : '<rootDir>/src/$1',
        '^#/(.*)$' : '<rootDir>/tests/$1',
    },
    snapshotSerializers : [
        'jest-serializer-vue',
    ],
    testMatch : [
        '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)',
    ],
    testURL : 'http://localhost/',
    globals : {
        'ts-jest' : {
            babelConfig : true,
        },
    },
    coveragePathIgnorePatterns : [
        'src/i18n.ts',
    ],
    setupTestFrameworkScriptFile : '<rootDir>/tests/setup.ts',
}
~~~

For information Jest test works fine.

**Stryker environment**

```
├─┬ @stryker-mutator/core@1.3.1
│ ├─┬ @stryker-mutator/api@1.3.1
│ ├── @stryker-mutator/util@1.3.1
├─┬ @stryker-mutator/html-reporter@1.3.1
│ ├── @stryker-mutator/api@1.3.1 deduped
│ ├── @stryker-mutator/util@1.3.1 deduped
├─┬ @stryker-mutator/jest-runner@1.3.1
│ ├── @stryker-mutator/api@1.3.1 deduped
├─┬ @stryker-mutator/typescript@1.3.1
│ ├── @stryker-mutator/api@1.3.1 deduped
│ ├── @stryker-mutator/util@1.3.1 deduped
├─┬ @stryker-mutator/vue-mutator@1.3.1
│ └── @stryker-mutator/api@1.3.1 deduped
```

```
jest@22.0.0
```

**Test runner environment**

```shell
npm run build:alias && vue-cli-service test:unit --silent # for jest
cross-env VUE_CLI_BABEL_TARGET_NODE=true VUE_CLI_BABEL_TRANSPILE_MODULES=true stryker run # for stryker
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.17.0
| npm              | 6.14.13
| Operating System | MacOS

**Add stryker.log**

internal/modules/cjs/loader.js:443
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/api' is not defined by "exports" in node_modules/mutation-testing-report-schema/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/antoine/www/letsignit/cloud-v2/node_modules/@stryker-mutator/api/report.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:1068:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED

**Comment by simondel** [comment]
Thanks for opening this issue! Could you create a small reproduction app?

**Comment by amiceli** [comment]
I can try.
I will post github link if I reproduce same error.

**Comment by amiceli** [comment]
Good news, I fix it by upgrading some dependencies : 

- @stryker-mutator/core from 1.2.0 to 5.4.0
- @stryker-mutator/jest-runner from 1.2.0 to 5.4.0

I also remove some packages (it can help someone with same problem) : 

- @stryker-mutator/typescript
- @stryker-mutator/vue-mutator
