### ISSUE TITLE
Are some of the pages in the docs no longer required

### ISSUE THREAD

**Issue by ebh** [stryker-mutator/stryker-js#3158]
**Question**

I suspect, but am not sure, that some pages in the docs are no longer required. Specifically these pages:
* https://stryker-mutator.io/docs/stryker-js/typescript-checker
* https://stryker-mutator.io/docs/stryker-js/guides/react

I wanted to add Stryker to my React/TypeScript app and started off following the [guide for React](https://stryker-mutator.io/docs/stryker-js/guides/react) and quickly ran into errors and deprecation warnings.

Next, I started off the [TypeScript Checker page](https://stryker-mutator.io/docs/stryker-js/typescript-checker), here too I ran into issues (Note: I now suspect that this something to do with my project, I mention it only to explain my journey).

So then I decided to create a branch new React/TypeScript app using `create-react-app` and following the various guides to installing StrykerJS. With the view that I would raise a pull-request to update the docs.

That's when I discovered that it seems all I need to do was run `stryker init`, I'm running `v5.4.0`, and follow the prompts.

So you can see exactly what I've done, I've created a repo with 3 branches, one for each of the processes I followed:
1. [StrykerJs->Guides->React](https://github.com/ebh/stryker-js-create-react-app-typescript/tree/stryker-js--guides--react)
2. [Getting started & TypeScript Checker](https://github.com/ebh/stryker-js-create-react-app-typescript/tree/stryker-js--getting-started--typescript-checker)
3. [Getting started only](https://github.com/ebh/stryker-js-create-react-app-typescript/tree/stryker-js--getting-started)

If I'm on the right track, as in those 2 pages are not required (maybe not all of them) then let me know, and I'll raise a PR :)

**Comment by nicojs** [comment]
Hi @ebh thanks for raising this issue and the detailed analysis 💛


> 1. StrykerJs->Guides->React

Yes, this one seems to be outdated. Should be updated to be in sync with `stryker init`.

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/react",
  "testRunner": "jest",
  "reporters": [
    "progress",
    "clear-text",
    "html"
  ],
  "coverageAnalysis": "off",
  "jest": {
    "projectType": "create-react-app"
  }
}
```

> 2. Getting started & TypeScript Checker

This isn't working for me. I get this error

```
3:43:10 (25475) INFO ConcurrencyTokenProvider Creating 4 checker process(es) and 3 test runner process(es).
13:43:13 (25475) ERROR Stryker Unexpected error occurred while running Stryker Error: Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
    at HybridFileSystem.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120127:68)
    at /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120126:12)
    at startWatching (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120148:17)
Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
    at HybridFileSystem.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
```

I'm pretty sure this is a new issue with `typescript@4.4`. Downgrading to 4.3 seems to work fine. I've opened #3176 for this. Good catch 💙

```
yarn add --dev typescript@4.3
npx stryker run
```

Results in:

```
--------------------|---------|----------|-----------|------------|----------|---------|
File                | % score | # killed | # timeout | # survived | # no cov | # error |
--------------------|---------|----------|-----------|------------|----------|---------|
All files           |    0.00 |        0 |         0 |          4 |        0 |       5 |
 App.tsx            |     NaN |        0 |         0 |          0 |        0 |       1 |
 index.tsx          |    0.00 |        0 |         0 |          1 |        0 |       0 |
 reportWebVitals.ts |    0.00 |        0 |         0 |          3 |        0 |       4 |
--------------------|---------|----------|-----------|------------|----------|---------|
```

> 3. Getting started only

Yes, this is the way you should configure it 👍
