### ISSUE TITLE
Json reporter: wrong test id under killedBy

### ISSUE THREAD

**Issue by JSmits-utwente** [stryker-mutator/stryker-js#3168]
**Summary**

When using the json reporter a wrong test id is placed in the `killedBy` list of several mutants in the report. Instead of a number such as `"1"` it shows `" should have the correct name"`, see screenshot below. No test with id `" should have the correct name"` exists. This was found when running StrykerJS on the [instrumenter package](https://github.com/stryker-mutator/stryker-js/tree/master/packages/instrumenter) of StrykerJS itself (master branch).
![image](https://user-images.githubusercontent.com/65605651/135119017-7cef64d5-d7d0-478a-9224-04fb82fd6be1.png)

**Stryker config**

Stryker's parent config file for running Stryker (with adjustments):
```json
{
  "$schema": "./packages/core/schema/stryker-schema.json",
  "coverageAnalysis": "perTest",
  "testRunner": "mocha",
  "reporters": [
    "progress",
    "html",
    "json"
  ],  
  "plugins": [
    "../mocha-runner",
    "../typescript-checker"
  ],
  "checkers": ["typescript"],
  "dashboard": {},
  "buildCommand": "tsc -b",
  "mochaOptions": {
    "spec": ["dist/test/unit/**/*.js"]
  },
  "disableBail": true,
  "timeoutMS": 60000,
  "concurrency": 7,
  "fileLogLevel": "trace"
}
```
Instrumenter specific Stryker config (unchanged from online version):
```javascript
const path = require('path');
const settings = require('../../stryker.parent.conf');
const moduleName = __dirname.split(path.sep).pop();
delete settings.mochaOptions.spec;
delete settings.files;
settings.plugins = settings.plugins.map(p => path.resolve(p));
settings.dashboard.module = moduleName;
module.exports = settings;
```

**Stryker environment**

Unchanged from defaults. Stryker uses itself on itself, so it should be the latest version of everything (?):
```
+-- @stryker-mutator/core@5.4.0
+-- @stryker-mutator/test-helpers@5.4.0
+-- mocha@9.1.2
```

**Test runner environment**

```shell
# npm test
```

Mocha config (unchanged from online version):
```json
{
  "require": ["dist/test/setup.js"],
  "spec": [
    "dist/test/unit/**/*.js",
    "dist/test/integration/**/*.js"
  ],
  "timeout": 10000
}
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.17.1
| npm              | 6.14.13
| Windows 10 | 21H1 (OS Build 19043.1237)

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/7245671/stryker.log)

**Comment by nicojs** [comment]
Once I opened the test file, the issue seemed kind of obvious

![image](https://user-images.githubusercontent.com/1828233/135479209-63c33452-212a-4ae4-bae8-4094668d0951.png)

🤦‍♀️

The string value being mutated was used in the test name. #3177 fixes that issue.

**Comment by nicojs** [comment]
I don't think we can prevent this from happening in Stryker... the test matching is best effort I guess... 🤷‍♀️
