### ISSUE TITLE
Add node-tap support

### ISSUE THREAD

**Issue by EvgenyOrekhov** [stryker-mutator/stryker-js#325]
It would be nice to be able to use Stryker with [node-tap](https://github.com/tapjs/node-tap) test framework.

**Comment by simondel** [comment]
Hi! How does node-tap differ from tape?

**Comment by EvgenyOrekhov** [comment]
@simondel I guess they are unrelated projects. The only thing that is common is that they both use the [Test Anything Protocol (TAP)](https://testanything.org/) to produce output.

**Comment by nicojs** [comment]
Just a heads up. Stryker recently released with the `'command'` test runner. This is also the default if you don't specify a test runner. It just runs your `npm test` command. Exit code 0 means the tests succeeded. Exit code != 0 means failed. @EvgenyOrekhov would that work for you?

**Comment by EvgenyOrekhov** [comment]
@nicojs Sorry, I don't use node-tap or Stryker anymore.

**Comment by nicojs** [comment]
Ok, please don't forget about us. 👋

**Comment by nicojs** [comment]
I want to try to implement this

**Comment by nicojs** [comment]
Thanks for the patience everyone, Node Tap support is released in v7 ♥, see docs here: https://stryker-mutator.io/docs/stryker-js/tap-runner/

**Comment by nicojs** [comment]
Blog article here: https://stryker-mutator.io/blog/announcing-stryker-js-7/
