### ISSUE TITLE
Ability to glob folders and then run them in separate instances

### ISSUE THREAD

**Issue by rodoabad** [stryker-mutator/stryker-js#3301]
**Is your feature request related to a problem? Please describe.**

We basically have a component library and each folder is a component completely independent of other components and in this case, other folders.

**Describe the solution you'd like**

I'd like to be able to glob programmatically inside the config so I can send Stryker a list of folders and it'll run mutations per folder as opposed to the whole suite.

```js
module.exports = {
    jest: {
        config: require('./jest.config.unit'),
        projectType: 'custom'
    },
    mutate: ['src/**/*.ts?(x)'],
    reporters: ['dots', 'clear-text', 'html'],
    testRunner: 'jest',
    thresholds: {
        break: 100,
        high: 100,
        low: 100
    },
    tsconfigFile: 'tsconfig.json'
};
```

This is what I have right now which pretty much says mutate the whole `src` as opposed to, if you are in `/accordion`, only mutate files in `/accordion`.

**Describe alternatives you've considered**

Not sure if there are any other alternatives since running from root takes forever in very large code bases.

**Additional context**

Any alternative is much appreciated.

**Comment by JoaoGFarias** [comment]
These would be great.
I have the same situation and it would decrease the run time.
