### ISSUE TITLE
Do not wipe (HTML) reports directory when creating a new mutation report

### ISSUE THREAD

**Issue by ericcornelissen** [stryker-mutator/stryker-js#3337]
**Is your feature request related to a problem?**
I sometimes want to compare two mutation reports (e.g. to see which mutants I killed after adding a test) but unfortunately I can't put the copied report in the same directory because [the HTML reporter wipes the directory before writing the new report](https://github.com/stryker-mutator/stryker-js/blob/67ee8976cde7ea53664238276f001f25aec50e71/packages/core/src/reporters/html/html-reporter.ts#L35) (I don't use nor did I check other reporters that write to disk).

**Describe the solution you'd like**
Don't clean the reports directory, leave any files in the directory and only _replace_ the report file(s). Whether that's overwriting (in place) or replacing (removing-then-adding) is irrelevant to me.

**Describe alternatives you've considered**
None.

**Additional context**
I did some minor investigation before opening this issue. All I was able to find is that this was written (effectively) as it is currently found in the source code, in https://github.com/stryker-mutator/stryker-js/pull/290 and (the behaviour) hasn't changed since. Unfortunately I didn't see an explanation for why the entire folder is wiped in that Pull Request or any of its commits. If I had to guess why it is this way I'd guess it is because this is the most straightforward way to implement this.

**Comment by nicojs** [comment]
Good point. The reason for it to delete the entire dir is for historic reasons, since we used to have an HTML report that existed out of multiple HTML files.

For v6, I want to get rid of the directory entirely. Instead writing directly to `reports/mutation/mutation.html` (or something like that).

Timeline for v6 is March / April. Feel free to send in a PR if you want it fixed sooner.

**Comment by nicojs** [comment]
It's implemented and ready to go with StrykerV6 release. Closing in order to keep track.
