### ISSUE TITLE
Add way to see mutants with their result before the end of the stryker command (maybe using --partial-report)

### ISSUE THREAD

**Issue by edi9999** [stryker-mutator/stryker-js#3338]
**Is your feature request related to a problem? Please describe.**

I have tests running in about 4 seconds using all CPUS (thus multiple tests cannot be run at the same time) with a lot of mutants (about 3000), so I need to wait for a long time to get results (at least 4 hours), and using 100% CPU so my laptop would be unusable.

**Describe the solution you'd like**

I'd be happy if there was a way to see the report before the completion of the stryker command. For example, a flag like `--partial-report` that would generate a partial HTML report with mutants already run and their results.
For example, one implementation might update the partial HTML report every minute.

**Describe alternatives you've considered**
Haven't found any, the usage of the "mutate" filter option still makes most of my stryker commands run in over 30 minutes.

**Comment by edi9999** [comment]
@nicojs is this something that you would accept as a new feature ?

**Comment by nicojs** [comment]
That sounds awesome! But it will be a big one. I've thought about this already and dicided to create a graduation assignment out of it:

https://carriere.infosupport.com/vacatures/afstudeeropdracht-real-time-reporting-voor-stryker-mutator/

My current thoughts:

We could change the html reporter to update a HTML report every x seconds. It would write a report json and mark mutants without status with a new "unknown" status (does not exist yet). It can also print a "time left" and progress bar at the top, together with a reload button and refresh timer (reload the file each 10 secs).

What do you think about this?

**Comment by edi9999** [comment]
> We could change the html reporter to update a HTML report every x seconds

Yes, making this the default (not having to add a specific flag), would make sense.

The unknown or "pending" status would make sense, and the time-left/progress bar could be shown.

The HTML should not `window.location.reload()` by itself in my opinion, but the underlying HTML would update by itself and one could F5 to reload the file.

**Comment by nicojs** [comment]
That would even be better yes. Technically it's not that hard, rebinding the report json should update the report. And opening a web socket isn't that hard either.

The `pending` name is better yes  You could misuse the `Ignore` status for now, or simply not show those mutants. The reason adding a status might take time is because that should be added in the mutation testing elements repository: https://github.com/stryker-mutator/mutation-testing-elements. For prototyping, we could temporary use `Ignore`

**Comment by nicojs** [comment]
Hmm if you want to make it 100% reactive, you can also add a the functionality directly to mutation testing elements by adding a `srcSocket` attribute to point to a web socket address where you retrieve the realtime data from. Updating the screen on the fly. 

Might be a lot of work though 😉. Mutation testing elements is a native web component library using lit.dev . Do you know your way around that stack?

**Comment by edi9999** [comment]
I don't think I will have time for a large project like this anytime soon. I will concentrate on smaller tasks first, also to avoid "losing time" because it requires a lot of commitment to start a huge task.
