### ISSUE TITLE
Avoid using "true" condition replacement in "||" statements, and avoid using "false" replacement in "&&" statements

### ISSUE THREAD

**Issue by edi9999** [stryker-mutator/stryker-js#3339]
**Is your feature request related to a problem? Please describe.**

I have some code like this : 

```
if (part.type === "content" || part.type === "tag") {
    return part;
}
```

And there are 3 applied mutants : 

```
if (true) {
    return part;
}

if (true || part.type === "tag") {
    return part;
}
if (part.type === "content" || true) {
    return part;
}
```

I think it would make sense to just run one of the mutants in this case.

**Comment by edi9999** [comment]
Could you pinpoint a point in the code where we have access to all mutants on one file for example to see if we could check for those cases ?

**Comment by nicojs** [comment]
Having all mutants available for one file is too late imo. You won't have access to the last anymore, which is what you need. Seeing as all these get created by the same mutator, we should try to simply not make the similar mutants at all. So I would suggest looking at the mutator implementation.

Please change the title of this issue, equivalent mutants is something entirely different, see https://stryker-mutator.io/docs/mutation-testing-elements/equivalent-mutants
