### ISSUE TITLE
Potential type bug in expression-mutant-placer

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker-js#3350]
https://github.com/stryker-mutator/stryker-js/blob/master/packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts#L15
![image](https://user-images.githubusercontent.com/28489774/148961462-14bc0b60-c74d-4632-b050-f52ba7300a05.png)

it says it will return `types.Expression | undefined` but it always returns undefined - it is side-effect function

![image](https://user-images.githubusercontent.com/28489774/148961643-a8939234-2a37-4370-ab6a-44eda7971ea8.png)
it is used later as such

**Comment by nicojs** [comment]
Wow! Great find 🤗

I've added early returns in #3387
