### ISSUE TITLE
Add support for jest projects

### ISSUE THREAD

**Issue by thirionlogan** [stryker-mutator/stryker-js#3367]
**Is your feature request related to a problem? Please describe.**
I have to `stryker run` for each separate project in my mono-repository. This generates a separate report for each project as well.

**Describe the solution you'd like**
I would like to be able to define separate config files for different projects , as Jest's [projects feature](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig).
I would like to have the stats of all of the projects in one report.

**Comment by nicojs** [comment]
Thanks for opening this issue. We're thinking of ways to improve, but for now I've added a section to stryker-mutator/mutation-testing-elements. It explains how to merge multiple report JSON files together:

https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/metrics/README.md#use-case-merging-multiple-json-reports

The idea is that you run StrykerJS multiple times (per module) and then use that script to merge the reports together. Please let me know if you need more help with this.
