### ISSUE TITLE
[TS] empty import type declaration makes initial test run fail

### ISSUE THREAD

**Issue by m-ronchi** [stryker-mutator/stryker-js#3386]
**Summary**

if a file contains an import in the form
```typescript
import type { } from "some module";
```

then stryker generates an invalid import statement in the mutated ts file:
```typescript
import type from "some module";
```

which fails to compile with the error
```log
TSError: ⨯ Unable to compile TypeScript:
src/index.ts(65,13): error TS1005: '=' expected.
```

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "mocha",
  "coverageAnalysis": "perTest",
  "checkers": [
    "typescript"
  ],
  "tsconfigFile": "tsconfig.json"
}

```

**Test runner config**

mocharc.json
```
{
    "$schema": "https://json.schemastore.org/mocharc",
    "require": [
        "ts-node/register",
        "source-map-support/register"
    ],
    "spec": [
        "test/**/*.spec.ts"
    ]
}
```

**Stryker environment**

```
├── @stryker-mutator/core@5.6.1
├── @stryker-mutator/mocha-runner@5.6.1
├── @stryker-mutator/typescript-checker@5.6.1
```

```
+-- mocha@9.2.0
```

**Test runner environment**

```shell
mocha
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16
| npm              | 8
| Operating System | mac

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker-js/files/7952036/stryker.log)

[code-mutated.zip](https://github.com/stryker-mutator/stryker-js/files/7952053/code-mutated.zip)
[code-original.zip](https://github.com/stryker-mutator/stryker-js/files/7952054/code-original.zip)

**Comment by nicojs** [comment]
A small correction

```ts
import type { } from 'some-module';
```

Gets instrumented to:

```ts
import type 'some-module';
```

Which indeed cannot be compiled with `tsc`. 

Will have to investigate further.

**Comment by nicojs** [comment]
It seems that both code examples have the exact same AST. So I'm not sure if there is anything we can do about it. @m-ronchi what exactly is your use case for `import type {} from 'some-module'`?

**Comment by m-ronchi** [comment]
it contains an external module augmentation, plus other code that is injected at an upper layer. I need to import the type declarations when I just include the code (for unit tests, external module is mocked).

more specifically, it is a [fastify plugin](https://www.npmjs.com/package/fastify-plugin) with
```typescript
import fp from "fastify-plugin";

declare module "fastify" {
    interface FastifyInstance { // add myPlugin to external type declaration
        myPlugin: Foo;
    }
}

export const plugin = fp(function (fastify) {
    fastify.decorate("myPlugin", foo); // add myPlugin to runtime instance
});
```

`import type` declarations are seen by tsc but stripped at runtime, while `import "module"` is retained for runtime side effects

**Comment by nicojs** [comment]
I see. No easy solution I'm afraid. I've opened https://github.com/babel/babel/issues/14250

**Comment by nicojs** [comment]
Some traction there, hopefully a fix soon

**Comment by kmdrGroch** [comment]
supposedly fixed in https://github.com/babel/babel/releases/tag/v7.17.7 https://github.com/babel/babel/pull/14309
it seems we are using 7.18 now, so it should be working now. Could you check if issue still persists?

**Comment by m-ronchi** [comment]
looks like it's fixed
