### ISSUE TITLE
Avoid mutating `?? true`  to `&& true`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3395]
**Summary**

![image](https://user-images.githubusercontent.com/1828233/151612327-a8e42f4f-d8e5-41a5-9336-d3a300d84712.png)

The above mutation always survives, we should not make it. I think.

Similar to #3339

**Comment by nicojs** [comment]
@edi9999 maybe you want a go at this one again 😅

**Comment by nicojs** [comment]
Never mind. It's getting late I think. This is clearly not a mutation that always survives.

**Comment by edi9999** [comment]
`??` can be converted to `&&` in some occasions and change the behavior.

If for example I have this code : 

```
function xxx(options) {
    const param = options.param ?? true;
    return param;
}
```

If I call `xxx({param: 10})` it would return `10` before the mutation and `true` after the mutation
