### ISSUE TITLE
Implement hot reload for jest

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3455]
**Is your feature request related to a problem? Please describe.**
Hot reload could be added to our jest-runner plugin. I'm not sure if it is even possible.

**Describe the solution you'd like**
We would need to request a proper public API in Jest.

**Describe alternatives you've considered**
We can _not implement this feature_. That's definitely easier. 

**Additional context**
Please up-vote (👍) this issue if you want it.

**Comment by kstephen314159** [comment]
This is very important to me. My stryker runs on good days take about an hour to 90 mins. Sometimes, I add more testcases, and this ends up causing I/O that goes beyond my storage capacity and then my runs take 8 hours or more. And then I have to increase my storage limits. Its been an ever increasing climb towards the storage limits of my cloud provider and its no fun.

If this is not a feature that is feasible, then atleast supporting a distributed (on multiple machines with a collector that merges results to a single report) would be great.
