### ISSUE TITLE
Test the `CheckerFacade`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3459]
We've merged #3450 early so we could release the beta. Please add unit tests for `src/checker/checker-facade.ts` as well as at least 1 integration test.

@danny12321 @ThierryRietveld do you think one of you can pick this up?

**Comment by danny12321** [comment]
I have started adding tests in the branch [fix/test-checker-facade](https://github.com/stryker-mutator/stryker-js/tree/fix/test-checker-facade). Currently I have (unit) tested if the facade returns the mutants it was given or else throw an error. I hope I can create the integration test(s) tomorrow.
