### ISSUE TITLE
Progress reporter shows more mutants are done then there are available

### ISSUE THREAD

**Issue by danny12321** [stryker-mutator/stryker-js#3461]
**Summary**
When running Stryker beta 6.0.0 the progress reporter shows that there are more mutants done then there are available (see image below). Sometimes it will still complete the run with no other issues but other times it will get stuck. 

![image](https://user-images.githubusercontent.com/15829978/157405316-60d062b9-175a-4138-9d64-0a63a3d59f86.png)

**Stryker environment**

```
+-- @stryker-mutator/core@6.0.0-beta.0
```

```
+-- mocha@6.0.0-beta.0
```

**Test runner environment**

```shell
# cd packages/core/ && node bin/stryker.js run -m src/checker/checker-facade.ts
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16.14.0
| npm              | 8.3.1
| Operating System | Windows 10

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/8213080/stryker.log)

**Comment by simondel** [comment]
@danny12321 Can you still reproduce this issue?

**Comment by danny12321** [comment]
Same here. 😕

**Comment by nicojs** [comment]
I was able to reproduce it. Not on the master branch (because the checker-facade doesn't have tests there), but on the `fix/test-checker-facade` branch. I found the issue and created a PR for it.

**Comment by nicojs** [comment]
Also found #3473 during the fixing of this issue, so 2 bugs for the price of one. 😅
