### ISSUE TITLE
StrykerJS + vitest

### ISSUE THREAD

**Issue by lbenie** [stryker-mutator/stryker-js#3465]
**Is your feature request related to a problem? Please describe.**
I've been slowly migrating my projects to use `vite` as the config bundler. With that they recently introduced [vitest](https://vitest.dev/) which allows to _share a common transformation pipeline during dev, build, and test time_.  I don't believe with the current mutators that it would work with `vitest` as there are no runners for `vitest`.

**Describe the solution you'd like**
I don't know if it would be feasible to work with the `vitest` core dev team and allow a `stryker-js` configuration using vitest?

**Describe alternatives you've considered**
unfortunately I don't see any

**Additional context**
none

**Comment by nicojs** [comment]
No, it is [on the roadmap](https://github.com/stryker-mutator/stryker-js/wiki/Roadmap), but it will take some time to implement. Feel free to implement this feature if you want it to work sooner 😅

**Comment by TeunLamers** [comment]
We are working on possible solution! Please help us and upvote this issue https://github.com/vitest-dev/vitest/issues/2167

**Comment by silverbackdan** [comment]
Will be great to have this support, love mutation testing and your work here on Stryker, thanks.

**Comment by rqbazan** [comment]
Hey @lbenie ✋ do you are working on this? I would love to help

**Comment by lbenie** [comment]
> Hey @lbenie ✋ do you are working on this? I would love to help

Hey man, no unfortunately I haven't had time to work on this. Seems like the stryker team took a job at it though

**Comment by silverbackdan** [comment]
Hi @lbenie do you happen to have any links to their attempts so we can keep an eye on progress and perhaps others who find this issue could jump in and help too?

**Comment by silverbackdan** [comment]
@rqbazan I think @TeunLamers looks like the person to ping if you're looking to help, looks like they were working on a prototype in October last year.

**Comment by nicojs** [comment]
Yes. @TeunLamers was a graduate student implementing Svelte support. Which is almost implemented (see PR). Unfortunately he had to drop Vitest support, because it was to much work to finish during his graduation assignment period. We still have support planned, I hope we can start on it in February

**Comment by silverbackdan** [comment]
Thanks for the update @nicojs :) Good luck @TeunLamers with your work for graduation

**Comment by SemSnel** [comment]
Hi there,

Any updates on vite support? Planning to implement it early on in a new project.

Thanks! :)

**Comment by TeunLamers** [comment]
Hey, you should keep an eye on this [pull request](https://github.com/stryker-mutator/stryker-js/pull/4043) for vitest support! :)

**Comment by SemSnel** [comment]
@TeunLamers Thank you! Does this also work with typescript? Hope your graduation went well! :)

**Comment by TeunLamers** [comment]
I succesfully graduated in late January and recently started working in mid March! Depending on your stack it will most likely work.
The Vitest runner should work with Typescript projects because Typescript support is already build in StrykerJS. For Svelte projects Typescript does not work at the moment but is planned at a later date. This [Pull request](https://github.com/stryker-mutator/stryker-js/pull/3929) needs te be merged first for Svelte integration and Typescript support comes at a later date for that!

**Comment by SemSnel** [comment]
@TeunLamers Good to hear! I also need to graduate this year. ^^ 

Even though I really like Svelte, I want to keep the Tech Stack more average with Vue, Storybook and .NET as backend. Not sure if or when we need to scale this project, so this setup will be probably the best for us.

**Comment by TeunLamers** [comment]
@SemSnel Good luck with your graduation! ^^

That seems like a solid stack! If you choose a different test runner StrykerJS will for sure work with Vue and Typescript. I have no clue how good testrunner integrations are with Vite besides Vitest so it might be worth the wait.

**Comment by DanielRamosAcosta** [comment]
Hey! I've seen that [the PR for adding support for vitest](https://github.com/stryker-mutator/stryker-js/pull/4043) has been merged. How is the status of this issue? Thanks!

**Comment by silverbackdan** [comment]
@DanielRamosAcosta how cool! I will try to implement and report back

**Comment by nicojs** [comment]
Thanks, everyone, for your patients.

🎉 The vitest runner is released: in v7.0.0 

See https://github.com/stryker-mutator/stryker-js/releases/tag/v7.0.0

For the docs, see https://stryker-mutator.io/docs/stryker-js/vitest-runner/

If you have any issues, please let us know. A blog article about this release will be published following Monday.

**Comment by silverbackdan** [comment]
Amazing news, I'll see about adding this into a project :)

**Comment by nicojs** [comment]
Blog article here: https://stryker-mutator.io/blog/announcing-stryker-js-7/
