### ISSUE TITLE
improve detection of missing config file

### ISSUE THREAD

**Issue by bodote** [stryker-mutator/stryker-js#3466]
**Is your feature request related to a problem? Please describe.**
 I'm frustrated when I try to run stryker on a new project with `npx stryker run` but forgot to run the `npx stryker init` before.
Because you get some weird error messages, none of them seem to be releated to a missing config file.

example: 

```
ng new stryker-angular-test
cd stryker-angular-test/
npm install
ng serve
ng test
ng test --no-watch --code-coverage
npx stryker run
```
>you get some weird error messages

**Describe the solution you'd like**
I would like , that `npx stryker run` would check if there is a config file, and if not, stops running and complains about missing config and gives the hint to the user that she should start `npx stryker init` first.
 
**Describe alternatives you've considered**
none

**Additional context**
It's especially problematic for beginners (of stryker) because for them , stryker should be easier to use.

**Comment by nicojs** [comment]
Hi @bodote thanks for opening this issue.

I want to note that running Stryker without a config file is a deliberate feature which is useful for smaller (nodejs based) projects. To help with your use case,. Stryker already logs when it is missing a config file:

```
nicojs@NicoJ01 ~/github/tmp $ npx stryker run
08:32:01 (2874) INFO ConfigReader No config file specified. Running with command line arguments.
08:32:01 (2874) INFO ConfigReader Use `stryker init` command to generate your config file.
```

Would it help if we log it again after a failing run?

```
nicojs@NicoJ01 ~/github/tmp $ npx stryker run
08:32:01 (2874) INFO ConfigReader No config file specified. Running with command line arguments.
08:32:01 (2874) INFO ConfigReader Use `stryker init` command to generate your config file.
[...]
08:32:02 (2874) ERROR DryRunExecutor One or more tests failed in the initial test run:
        All tests

> tmp@1.0.0 test
> echo "Error: no test specified" && exit 1


Error: no test specified

08:32:02 (2874) ERROR Stryker There were failed tests in the initial test run.
08:32:02 (2874) ERROR DryRunExecutor Hint: Stryker did not detect a config file, did you forget to provide one?
```

**Comment by bodote** [comment]
the problem is, that the message "No config file specified" is logged as Info (instead of at least a warning) and you don't see this right away, because for some reason the `npx stryker run` opens a new browser window with karma and shows this error message: 
<img width="1179" alt="karma-error" src="https://user-images.githubusercontent.com/8531026/160410105-269d83e6-d95d-4698-9760-2c92d5456e49.png">

**Comment by kmdrGroch** [comment]
it surely would be possible, but at the same time, it would add lots of complexity to, in some places, already complex codebase.  (especially config checking stuff :D) We coould check `package.json` for `angular` and throw error if there is no config, or even try providing some default config for angular...
Maybe there is other way to check tho? @nicojs @bodote what are your thoughts?
