### ISSUE TITLE
Doesn't work with jest.config.ts

### ISSUE THREAD

**Issue by saiichihashimoto** [stryker-mutator/stryker-js#3476]
Everything works perfectly with jest.config.js, however, changing it to jest.config.ts (and making sure the [`jest.configFile`](https://stryker-mutator.io/docs/stryker-js/jest-runner#jestconfigfile-string) points to the typescript file. Doesn't work.

**Comment by ricardani** [comment]
I had a similar issue and what I did to solve it was to use the jest.config (with `require`) instead of jest.configFile and replaced `export default` with `module.exports = ` in the jest.config file

**Comment by nicojs** [comment]
Ah yes, should be an easy fix. We're happy to accept a PR for this

**Comment by nicojs** [comment]
Fixed with #3761

**Comment by nicojs** [comment]
Released in v6.3 🎉. Just a headsup, `jest.config.ts` files will only work when using `jest@>=29.2`
