### ISSUE TITLE
Migrate away from lerna

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3484]
See 
https://twitter.com/tomasz_ducin/status/1519436453729734657?s=20&t=gf2YzbUwSThzRuXIJSdc0Q

Possible alternatives:
- [nx](https://nx.dev/)
- [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)

I would prefer to try npm workspaces first.

TODO:
- [ ] Figure out dev setup
- [ ] Figure out how to auto-generate changelogs from commit log
- [ ] Figure out new release script

... .😢

**Comment by LayZeeDK** [comment]
Alternative toolchains:
- Nrwl Nx
- Google Wireit
- Google Bazel
- Microsoft Lage
- Microsoft Rush.js
- Turborepo
- npm Workspaces
- Yarn Workspaces
- pnpm Workspaces

**Comment by LayZeeDK** [comment]
Changelog toolchains:
- GitHub automated release notes
- JSCutlery SemVer
- Semantic Releases

**Comment by LayZeeDK** [comment]
Leena to Nx migration guide https://nx.dev/guides/lerna-and-nx

**Comment by blephy** [comment]
A nice comparaison of monorepo tools : https://monorepo.tools/

To auto-generate changelogs / release, `semantic-release` with [some plugins](https://github.com/oleg-koval/semantic-release-npm-github-publish#readme) ?

**Comment by LayZeeDK** [comment]
[Monorepo.tools guide](https://monorepo.tools/)

**Comment by LayZeeDK** [comment]
https://github.com/lerna/lerna/issues/3121

**Comment by nicojs** [comment]
Yep. Seems like we can keep using Lerna. I'll close this as soon as all deprecation warnings are actually gone :D
