### ISSUE TITLE
Equivalent mutant created for `if(x) return undefined`

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-js#3502]
Stryker-js creates a mutant that is equivalent to the original code:

![image](https://user-images.githubusercontent.com/10114577/168231500-d5a9eebe-2ea1-475e-b312-f1239d7a51bc.png)

**Comment by kmdrGroch** [comment]
Actually it is hard to say if it is equivalent... it removes `return` statement from there, meaning that it can possibly return something else or return undefined later
see:

case: we always get response.status = 404
```js
function test() {
  if(response.status === 404) {
    return undefined;
  } else {
    return true;
   } 
   const res = doSomethingWithResponse();
   
   if(res.error) {
     return undefined;
    }
   return res;
}```

now mutating it:
```js
function test() {
  if(response.status === 404) { // passes through
  } else {
    return true;
   } 
   const res = doSomethingWithResponse();
   
   if(res.error) { // if error - we still return `undefined`. From what i remember, we want to kill mutatans - tests should fail... if our test asserts result to be `undefined` test passes..
     return undefined;
    }
   return res; // unless there was error in `res.error` and goes here, then test fails which is good i believe
}```

so i think the result "might" be equivalent mutant, but its not necessarily always true

correct me if i am wrong

**Comment by nicojs** [comment]
Yeah, I asked @hugo-vrijswijk to create this issue. I thought it had to do with mutating undefined in this way:

```diff
- return undefined;
+ return;
```

This would most definitely be an equivalent mutant. But seeing as it's the block statement mutator, it would probably be impossible to detect deterministically.

You either have to refactor the code to not use this return, or [disable the mutant with a comment](https://stryker-mutator.io/docs/stryker-js/disable-mutants/#using-a--stryker-disable-comment)
