### ISSUE TITLE
Broken Badges

### ISSUE THREAD

**Issue by davidebasile** [stryker-mutator/stryker-js#3503]
Dear all,
 I don't know whether this is the right place to post this issue but I noticed today that the GitHub badges for stryker mutator are broken.

Best

**Comment by nicojs** [comment]
Thanks for reporting ♥. 

It seems like all badges are broken. The reports behind their links still work. @rouke-broersma will investigate this further.

**Comment by nicojs** [comment]
We've fixed it today. Enjoy your badges!
