### ISSUE TITLE
StrykerJS error when running with jest ^28.0.0

### ISSUE THREAD

**Issue by nicolas-sicard-adeo** [stryker-mutator/stryker-js#3505]
**Summary**

Mutation tests fail to run when using `jest` version `^28.0.0` and `ts-jest` version `^28.0.0`.

Works fine with `jest 27.5.1` and `ts-jest 27.1.4`.

See joined file for details.

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": ["html", "clear-text", "progress", "dashboard"],
  "testRunner": "jest",
  "coverageAnalysis": "perTest",
  "ignorePatterns": [
    "*.module.ts",
    "coverage",
    "dist",
    "load-env.ts",
    "src/**/test/**/*",
    "src/main.ts",
    "src/tracer.ts"
  ],
  "thresholds": {
    "high": 100,
    "low": 90,
    "break": null
  },
  "tsconfigFile": "tsconfig.json"
}

```

**Test runner config**

**Stryker environment**

```
+-- "@stryker-mutator/core": "6.0.2",
+-- "@stryker-mutator/jest-runner": "6.0.2",
+-- "@stryker-mutator/typescript-checker": "6.0.2",
```

```
+-- "jest": "28.1.0",
+-- "jest-extended": "2.0.0",
+-- "ts-jest": "28.0.2",
```

**Test runner environment**

```shell
# Test command
npx jest
```

```json
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "setupFiles": [
      "../jest-config.ts"
    ],
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!(uuid)/)"
    ],
    "collectCoverageFrom": [
      "**/*.ts",
      "!**/*.mock.ts",
      "!**/*.module.ts",
      "!**/main.ts",
      "!load-env.ts",
      "!app.config.ts",
      "!tracer.ts",
      "!**/index.ts"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node",
    "coveragePathIgnorePatterns": [
      "/test/"
    ],
    "setupFilesAfterEnv": [
      "jest-extended/all"
    ],
    "preset": "@shelf/jest-mongodb"
  }
```

and also from jest.config.ts:

```ts
import crypto from "crypto";

process.env.SOME_VAR = "test";
process.env.ENV = "test";
process.env.MONGO_DATABASE = "dbname-test";

Object.defineProperty(global, "crypto", {
  value: {
    getRandomValues: (arr: Array<unknown>) => crypto.randomBytes(arr.length),
  },
});

```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             |v16.14.0
| npm              |8.3.1
| Operating System |macos 12.3.1

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/8709221/stryker.log)

**Comment by nicojs** [comment]
Hi @nicolas-sicard-adeo 🙋‍♂️, thanks for opening this issue.

Interesting... What version of `jest-environment-node` are you using?

```
npm why jest-environment-node
```

I think that should be version 28.1.0.

If that is the case, would it be possible for you to attach a small reproduction project? It should be pretty straightforward, as the actual test files and source files are not needed in this case. There seems to be an issue with the project setup itself.

**Comment by nicolas-sicard-adeo** [comment]
Hi @nicojs , thanks for answering.

It seems that the `jest-environment-node` was held back to `27.x.x` by `"@shelf/jest-mongodb": "2.2.2"`. An issue is opened on their side.

I upgraded `jest-environment-node` to `28.x.x` and everything works fine.

Thank you very much!
