### ISSUE TITLE
Which configuration to use to run Stryker with Jest when the code base includes dynamic imports?

### ISSUE THREAD

**Issue by SmashingQuasar** [stryker-mutator/stryker-js#3563]
**Question**

I currently have a code base using dynamic import such as:

```ts
const { MyClass }: { MyClass: typeof MyClassType } = await import('./MyClass.js');
```

These imports are **necessary to my code to avoid circular imports situations**. There are no dynamic imports inside my tests.

I am running 1006 unit tests through Jest. Those tests all succeed without error nor warning.

When I try to run Stryker, it timeouts during the `INFO DryRunExecutor Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.` step.
I set the `logLevel` to `trace`. It turns out, this steps triggers the following error in Jest:
`ReferenceError: You are trying to 'import' a file after the Jest environment has been torn down.`.
There are hundreds of those errors. It targets specifically the statement provided above.

My question is: What kind of configuration do I need to make Jest behave inside Stryker so it does not fail with dynamic imports?

**Stryker environment**

```
│     ├─ @stryker-mutator/core@npm:^6.0.2 → npm:6.0.2
│     ├─ @stryker-mutator/jest-runner@npm:^6.0.2 → npm:6.0.2 [9a58f]
│     ├─ @stryker-mutator/typescript-checker@npm:^6.0.2 → npm:6.0.2 [9a58f]
├─ @stryker-mutator/core@npm:6.0.2
│  │  └─ stryker
│     ├─ @stryker-mutator/api@npm:6.0.2 → npm:6.0.2
│     ├─ @stryker-mutator/instrumenter@npm:6.0.2 → npm:6.0.2
│     ├─ @stryker-mutator/util@npm:6.0.2 → npm:6.0.2
├─ @stryker-mutator/jest-runner@npm:6.0.2
│     ├─ @stryker-mutator/api@npm:6.0.2 → npm:6.0.2
│     ├─ @stryker-mutator/util@npm:6.0.2 → npm:6.0.2
├─ @stryker-mutator/typescript-checker@npm:6.0.2
│     ├─ @stryker-mutator/api@npm:6.0.2 → npm:6.0.2
│     ├─ @stryker-mutator/util@npm:6.0.2 → npm:6.0.2
```

```
+-- jest@28.1.0
```

**Additional context**

I am running this with Node 14, on a Docker container running the official image `node:14.19-bullseye`.
I have tried this through `ts-jest` and `swc`. Both encounter the same issue so it does not seem to originates from here.

Here is my `jest.config.cjs`:

```js
module.exports = {
  transform: {
    // '^.+\\.ts$': 'ts-jest',
    '^.+\\.ts$': '@swc/jest',
  },
  preset: '@honestica/jest-preset-lifen',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.jest.json',
      useESM: true,
    },
  },
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '(.+)\\.js': '$1',
  },
  coverageThreshold: {
    global: {
      statements: 75,
    },
  },
  fakeTimers: {
    enableGlobally: true,
    doNotFake: [
      'Date',
      'hrtime',
      'nextTick',
      'performance',
      'queueMicrotask',
      'requestAnimationFrame',
      'cancelAnimationFrame',
      'requestIdleCallback',
      'cancelIdleCallback',
      'setImmediate',
      'clearImmediate',
      // 'setInterval'
      'clearInterval',
      'setTimeout',
      'clearTimeout',
    ],
  },
};
```

Here is my `stryker.conf.cjs`:

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutate: ['src/**/*.ts'],
  ignorePatterns: [
    // '**/node_modules/**',
    '**/.github/**',
    '**/.husky/**',
    '**/.circleci/**',
    '**/.yarn/**',
    '**/stats/**',
    '**/docs/**',
    '**/documentations/**',
    '**/reports/**',
    '**/coverage/**',
    '**/build/**',
    '**/dist/**',
    '**/lib/**',
  ],
  testRunnerNodeArgs: ['--experimental-vm-modules'],
  packageManager: 'yarn',
  reporters: ['html', 'progress', 'json'],
  htmlReporter: {
    fileName: './reports/stryker/mutation.html',
  },
  jsonReporter: {
    fileName: './reports/stryker/mutation.json',
  },
  ignoreStatic: true,
  testRunner: 'jest',
  jest: {
    projectType: 'custom',
    configFile: './jest.config.cjs',
    enableFindRelatedTests: true,
  },
  coverageAnalysis: 'perTest',
  checkers: ['typescript'],
  tsconfigFile: './tsconfig.stryker.json',
  thresholds: { high: 80, low: 50, break: 40 },
  logLevel: 'trace',
  dryRunTimeoutMinutes: 1,
};
```

For reference, here is the Jest output when ran normally outside Stryker:
```
Test Suites: 36 passed, 36 total
Tests:       1006 passed, 1006 total
Snapshots:   0 total
Time:        11.744 s
Ran all test suites.
```

Thanks a lot! ❤️

**Comment by nicojs** [comment]
Hmm, interesting. This use case should be supported. Would it be possible for you to create a small reproduction project? That's probably the fastest way to figure out what's wrong

**Comment by SmashingQuasar** [comment]
Sure, I'm going to try to wrap something up to reproduce this. :)

**Comment by SmashingQuasar** [comment]
Well I could never reproduce it with a small testing environment, however I did manage to fix the issue.
I removed `testRunnerNodeArgs: ['--experimental-vm-modules']` from my `stryker.conf.cjs` and suddenly everything went smoothly and it is not running my tests against mutants. Should be done in a few hours! 👍 

I can't provide you with an access to the code base but I can try to give you as much info as you need if you want to debug this.
