### ISSUE TITLE
Invalid regular expression in initial test run on Node 18

### ISSUE THREAD

**Issue by ericcornelissen** [stryker-mutator/stryker-js#3579]
**Summary**

When running Stryker on [one of my projects](https://github.com/ericcornelissen/shescape) using Node 18 ([using this branch](https://github.com/ericcornelissen/shescape/tree/chore-285/upgrade-node-for-dev)) I'm getting an unexpected error during the initial test run. In particular, I'm getting the following error:

```
SyntaxError: Invalid regular expression: /\u/: Invalid Unicode escape
```

This error is related to the use of a regular expression of the form `/\u{0}/gu` in several places ([example](https://github.com/ericcornelissen/shescape/blob/5887c0930da57bd6d0f27f668d04282bda87be5a/src/unix.js#L43)). Inspecting the files in Stryker's temp directory does reveal regular expressions of the form `/\u/gu`, which is indeed invalid syntax. However, it is not clear to me how such an invalid regular expression ends up in the code generated by Stryker.

A notable detail, I'm encountering this bug only on Node 18 (I tried 18.0.0 and 18.13.0) but not earlier versions (I tried 16.13.1, but I've been using Stryker on Node 16 in this project for a while now).

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "coverageAnalysis": "perTest",
  "inPlace": false,
  "mutate": ["src/**/*.js"],
  "commandRunner": {
    "command": "npm run test:unit"
  },
  "timeoutMS": 10000,
  "reporters": ["clear-text", "dashboard", "html", "progress"],
  "htmlReporter": {
    "fileName": "_reports/mutation/index.html"
  },
  "thresholds": {
    "high": 100,
    "low": 100,
    "break": 100
  },
  "tempDirName": ".temp/stryker",
  "cleanTempDir": false
}

```

**Test runner config**

I'm using AVA without any configuration.

**Stryker environment**

```
├── @stryker-mutator/core@6.0.1
```

```
├── ava@4.3.0
```

**Test runner environment**

```shell
ava test/unit/**/*.test.js
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v18.3.0
| npm              | v8.11.0
| Operating System | Ubuntu 20.04.4 LTS (64 bit)

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/8913382/stryker.log)

**Comment by nicojs** [comment]
Hi  @ericcornelissen 🙋‍♂️ thanks for opening this issue.

This is a neat little bug. Apparently the Regex mutator we use ([⚔ weapon-regex](https://github.com/stryker-mutator/weapon-regex)) is mutating this incorrectly. I've opened [an issue](https://github.com/stryker-mutator/weapon-regex/issues/163) there.

In the meantime, you can workaround it by disabling mutating these regexes with a comment:

```js
export function escapeArgBash(arg) {
    // Stryker disable next-line Regex: Results in invalid mutant
    return arg.replace(/\u{0}/gu, "");
}
```

**Comment by ericcornelissen** [comment]
> In the meantime, you can workaround it by disabling mutating these regexes with a comment:
> 
> ```js
> export function escapeArgBash(arg) {
>     // Stryker disable next-line Regex: Results in invalid mutant
>     return arg.replace(/\u{0}/gu, "");
> }
> ```

After reading through https://github.com/stryker-mutator/weapon-regex/issues/163 I think a better alternative is to switch from a unicode regex to a "normal" regex and use `\u0000`:

```diff
  export function escapeArgBash(arg) {
-     // Stryker disable next-line Regex: Results in invalid mutant
-     return arg.replace(/\u{0}/gu, "");
+     return arg.replace(/\u0000/g, "");
  }
```
