### ISSUE TITLE
Testing transition values

### ISSUE THREAD

**Issue by ehcorrea** [stryker-mutator/stryker-js#3580]
**Summary**

Hello, I'm having some problems in testing transition values ​​with timing. My tests with jest and testing-library run smoothly, but inside the stryker sandbox, it shows a test break in the "Starting initial test run" phase.

Test Case
![image](https://user-images.githubusercontent.com/37821900/174196696-738c169d-f6b3-4c86-8119-93f41f80cc7a.png)

Test Case Coverage
![image](https://user-images.githubusercontent.com/37821900/174196766-5d2f9c53-01bb-4186-ae03-58a3ad11f9fa.png)

Stryker Test Error
![image](https://user-images.githubusercontent.com/37821900/174196915-6d049af3-1e59-4dce-aa84-5b3aa52d3b64.png)

**Stryker config**

```javaScript
// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  packageManager: 'yarn',
  reporters: ['html', 'clear-text', 'progress', 'dashboard'],
  testRunner: 'jest',
  jest: {
    projectType: 'custom',
    configFile: 'jest.config.js',
    enableFindRelatedTests: true,
  },
  commandRunner: { command: 'yarn test' },
  checkers: ['typescript'],
  tsconfigFile: 'tsconfig.json',
  coverageAnalysis: 'perTest',
  mutate: ['src/components/**/index.tsx'],
};
export default config;
```

**Test runner config**

```javaScript
module.exports = {
  preset: 'react-native',
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/components/**/*.tsx',
    '<rootDir>/src/view/**/*.tsx',
  ],
  modulePaths: ['<rootDir>/src/', '<rootDir>/.jest'],
  transform: {
    '^.+\\.js$': require.resolve('react-native/jest/preprocessor.js'),
  },
  transformIgnorePatterns: [],
  setupFilesAfterEnv: ['<rootDir>/.jest/setup.ts'],
};
```

**Stryker environment**

```
"@stryker-mutator/core": "^6.0.2",
"@stryker-mutator/jest-runner": "^6.0.2",
"@stryker-mutator/typescript-checker": "^6.0.2",
```

```
"jest": "^26.6.3",
```

**Test runner environment**

```shell
yarn test 
```
or
```shell
yarn jest --maxWorkers=50% 
```

**Comment by ehcorrea** [comment]
> Hmm very interesting. Would you mind creating a small reproduction project? Either as a zip here, or a git repo is fine.

Sure, I'll try on pure React Js project.

**Comment by ehcorrea** [comment]
> Hmm very interesting. Would you mind creating a small reproduction project? Either as a zip here, or a git repo is fine.

I did some tests using pure ReactJs and NextJs, I was successful in both, but I keep getting error in the React Native.

Here is the link to the repository [Stryker Async App](https://github.com/ehcorrea/stryker-async-app)

**Comment by nicojs** [comment]
Wow awesome, thanks for providing this great reproduction repo.

Apparently, the `jest` cli sets the `NODE_ENV` environment variable to `test`, which in turn disables the transition animation (or something like that). The `@stryker-mutator/jest-runner` isn't enabling the NODE_ENV, at least not fast enough.

Workaround:

Run 
```
NODE_ENV=test npx stryker run
```

Or to support windows:

```
cross-env NODE_ENV=test npx stryker run --checkers "" --concurrency 2
```

**Comment by ehcorrea** [comment]
Thx, this works for me, I made a script in package.json(  `stryker:run` ) to run in pipelines and that's it, thanks again
