### ISSUE TITLE
Issue setting up Stryker, Dry Run Fails on initial run

### ISSUE THREAD

**Issue by CommanderWulf** [stryker-mutator/stryker-js#3621]
Hi, I am running into an issue where the initial dry run keeps running into the "One or tests failed in the initial test run". Specifically the files that fail are one that the test file contains either .toHaveBeenCalledTImes() or  .toHaveBeenNthCalledWith().
If I comment those tests out then I am good to go, but I kinda need to keep those tests

I am currently on version 5.6.1 (highest version employer current allows). It is a typescript webservice, and I saw in a previous version there were issues with ts-jest with the recommendation being add disableTypeChecks, which I have done. Is there some other configuration I need to do/I am missing?

![image](https://user-images.githubusercontent.com/26092796/176966556-8c84f6c2-ed6e-4ee7-b6a8-8190da5a636c.png)

**Comment by nicojs** [comment]
Hi @CommanderWulf 


There seems to be something wrong in your project. What you're describing should work. However I need far more information to help you.

Please provide the following info:

- jest config file
- Stryker config file
- the command you usually use to run the unit tests
- the Stryker log file (`npx stryker run --fileLogLevel trace`)

Or better yet a small project that reproduces your issue

**Comment by CommanderWulf** [comment]
**jest config**:
![image](https://user-images.githubusercontent.com/26092796/177005591-41db894d-b28d-4974-8b29-353ae8432c20.png)

**jest unit config**:
![image](https://user-images.githubusercontent.com/26092796/177005630-58f0a4a3-e00d-4399-8b0a-4271fe638fa6.png)

**stryker config:**
![image](https://user-images.githubusercontent.com/26092796/177005654-35c901fb-198a-400a-b93e-645516b940a3.png)

**unit test command**: jest --coverage --config=jest.unit.config.js

**Stryker log file:** _(i uncommented one of the toHaveBeenCalledTimes test so that it would fail again, but usually there is about 25ish tests that all fail for the same reason)_
![image](https://user-images.githubusercontent.com/26092796/177005536-2b9f9cb8-be7e-48d4-8968-c67988d718c5.png)

**Comment by nicojs** [comment]
Hmm it looks like you're using `'./jest.config.js'` for your stryker runs, but using `'./jest.unit.config.js'` for unit testing. I would expect that you get the same error when you're running `jest --coverage --config=jest.onfig.js`.

Could you try this stryker.conf.js file?

```js
// stryker.conf.js 
module.exports = {
  packageManager: 'npm',
  reporters: ['clear-text', 'progress', 'html'],
  testRunner: 'jest',
  jest: {
    configFile: 'jest.unit.config.js',
  },
  checkers: ['typescript'],
  timeoutMS: 60000,
  thresholds: { high: 100, low: 100, break: null }
}
```

(simplified it a bit as well)

**Comment by CommanderWulf** [comment]
that seems to have caused more issues.... with the provided stryker conf (or just modifying my original one to use the jest.unit.config.js) i get the following error (with or without the original problem tests commented out:
![image](https://user-images.githubusercontent.com/26092796/177019219-040df00e-8c8a-43ed-83aa-0fb65d9e27ee.png)

**Comment by nicojs** [comment]
And if you add `tempDirName: 'stryker-tmp` to your Stryker configuration? Does that work?

**Comment by nicojs** [comment]
This sounds like one of our known issues.:
https://stryker-mutator.io/docs/stryker-js/troubleshooting/#no-tests-executed---jest-runner

What if you add `tempDirName: 'stryker-tmp` to your Stryker configuration? Does that work?

**Comment by CommanderWulf** [comment]
So there was some other configuration issue with adding tempDirName on the simplified conf:
09:31:42 (1296) ERROR DryRunExecutor One or more tests resulted in an error:
        undefinedClass extends value #<Object> is not a constructor or null TypeError: Class extends value #<Object> is not a constructor or null

but going back to my original conf file, but using the jest unit conf & the tempDirName  finally got everything to play nice and work! thank you so much for all your help!

**Comment by CommanderWulf** [comment]
I'm using jest 28.0.3
