### ISSUE TITLE
How to choose a test subset in Stryker JS

### ISSUE THREAD

**Issue by antoniogamizbadger** [stryker-mutator/stryker-js#3632]
**Question**

Hi,  is there a equivalent configuration for `test-filter` (existing on Stryker4s -> https://stryker-mutator.io/docs/stryker4s/configuration/#test-filter-string) for Stryker JS? I don't want to use all my tests in the mutation.

**Stryker environment**

```
        "@stryker-mutator/core": "^4.4.1",
        "@stryker-mutator/jest-runner": "^4.4.1",
```

```
    "jest": "26.6.3",
    "react": "^17.0.2",
```

**Comment by nicojs** [comment]
Hi @antoniogamizbadger configuring which tests to run is part of the [test runner configuration](https://stryker-mutator.io/docs/stryker-js/plugins/#test-runners). 

For example (mocha ☕):

```json
{
  "mochaOptions": {
    "spec": [ "test/components/*.js" ],
    "grep": "AppComponent.*"
  }
}
```

This would run only the tests found in the test/components directory with title starting with "AppComponent...".

**Comment by antoniogamizbadger** [comment]
Ah, I see, great, thanks! Not sure if opening another ticket, but when using the `ignoreStatic` flag in stryker JS it tells me that it's not valid. It appears as not deprecated on the docs -> https://stryker-mutator.io/docs/stryker-js/configuration/#ignorestatic-boolean

**Comment by antoniogamizbadger** [comment]
Oh I need stryker 6. Great :DDDD

**Comment by nicojs** [comment]
True, you may open an issue to improve our docs if you want. We should specify a "since" for every option.
