### ISSUE TITLE
expressionMutantPlacer could not place mutants with type(s): "MethodExpression".

### ISSUE THREAD

**Issue by pmcelhaney** [stryker-mutator/stryker-js#3647]
**Summary**

Stryker doesn't like this code:

```js
path[dynamicSegment.slice(1, -1)] = segment;
```

> Unexpected error occurred while running Stryker SyntaxError: src/registry.js:64:10 expressionMutantPlacer could not place mutants with type(s): "MethodExpression".

It was easy to work around.

```js
const variableName = dynamicSegment.slice(1, -1)
path[variableName] = segment;
```

If you give me a hint where to get started (could be as simple as "here's where the unit test would go") I may take a stab at fixing it myself. 

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information",
  "packageManager": "yarn",
  "reporters": [
    "html",
    "clear-text",
    "progress",
    "dashboard"
  ],
  "testRunner": "jest",
  "testRunnerNodeArgs": ["--experimental-vm-modules"],
  "coverageAnalysis": "perTest"
}
```

**Test runner config**

```json
{
  "testEnvironment": "node",
  "collectCoverage": true,

  "collectCoverageFrom": ["src/**/*.{js,jsx,ts,tsx}", "!**/node_modules/**"],

  "coverageThreshold": {
    "global": {
      "branches": 45,
      "functions": 49,
      "lines": 54,
      "statements": -170
    }
  }
}
```

**Stryker environment**

```
├── @stryker-mutator/core@6.1.2
├── @stryker-mutator/jest-runner@6.1.2
├── stryker-cli@1.0.2
```

```
+-- jest@28.1.3
```

**Test runner environment**

```shell
node --experimental-vm-modules $(yarn bin jest)
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16.14.2
| npm              | 8.5.0
| Operating System | OS X 

See the [log from CI](https://github.com/pmcelhaney/counterfact/runs/7398762479?check_suite_focus=true)

**Comment by nicojs** [comment]
Thanks for opening this issue! We should be able to fix it when we have some time. 

As a workaround, you can use a disable-comment or refactor your code as you suggested.

```diff
+ // Stryker disable next-line MethodExpression: This mutant cannot be placed in (as of StrykerJS 6.1)
path[dynamicSegment.slice(1, -1)] = segment;
```
