### ISSUE TITLE
Test files not found after renaming src folder of angular project

### ISSUE THREAD

**Issue by fmilke** [stryker-mutator/stryker-js#3655]
**Summary**

After renaming the src folder and changing all the paths in (angular.json, tsconfig.*.json, stryker.conf.mjs) stryker does not find test files anymore. Unit tests with karma still work fine. There is a reproduction example below. 

```
18:41:52 (3976) INFO ProjectReader Found 4 of 276 file(s) to be mutated.
18:41:52 (3976) INFO Instrumenter Instrumented 4 source file(s) with 5 mutant(s)
18:41:52 (3976) INFO ConcurrencyTokenProvider Creating 8 test runner process(es).
18:42:06 (3976) INFO DryRunExecutor Starting initial test run (karma test runner with "perTest" coverage analysis). This may take a while.
18:42:06 (3976) INFO DryRunExecutor Initial test run succeeded. Ran 0 tests in 0 seconds (net 0 ms, overhead 282 ms).
18:42:06 (3976) ERROR Stryker No tests were executed. Stryker will exit prematurely. Please check your configuration.
```

**Stryker config**

```json5
{
// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  _comment:
    "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/angular",
  mutate: [
    "renderer/**/*.ts",
    "!renderer/**/*.spec.ts",
    "!renderer/test.ts",
    "!renderer/environments/*.ts",
  ],
  testRunner: "karma",
  karma: {
    configFile: "karma.conf.js",
    projectType: "angular-cli",
    config: {
      browsers: ["ChromeHeadless"],
    },
  },
  reporters: ["progress", "clear-text", "html"],
  concurrency: 8,
  concurrency_comment:
    "Recommended to use about half of your available cores when running stryker with angular",
  coverageAnalysis: "perTest",
};
export default config;

}
```

**Test runner config**

**Stryker environment**
```
+-- @stryker-mutator/core@6.1.2
+-- @stryker-mutator/karma-runner@6.1.2
```

```
+-- karma@~6.4.0
+-- angular-cli@~14.1.0
```

**Test runner environment**

```shell
ng test
stryker run
```

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        // for example, you can disable the random execution with `random: false`
        // or set a specific seed with `seed: 4321`
      },
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    jasmineHtmlReporter: {
      suppressAll: true // removes the duplicated traces
    },
    coverageReporter: {
      dir: require('path').join(__dirname, './coverage/src-alt'),
      subdir: '.',
      reporters: [
        { type: 'html' },
        { type: 'text-summary' }
      ]
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true
  });
};

```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16.13.2
| npm              | 8.1.2
| Operating System | win 10

**Add stryker.log**
https://github.com/fmilke/stryker-bug-repro/blob/master/trace.log

**Reproduction example**
https://github.com/fmilke/stryker-bug-repro

Changes:
- ng new src-alt
- stryker init
- rename src/ -> renderer/

Breaking changes:
https://github.com/fmilke/stryker-bug-repro/commit/08c97ba97ad913f8fd1e74f0fed2cbfaa5c90d20

**Comment by nicojs** [comment]
Hi @fmilke 🙋‍♀️, thanks for reporting this issue with such a clear reproduction example 👌

The problem is actually not that no tests are run, but that the angular-cli has issues compiling the files. You can see that clearly when running `npx stryker run --logLevel trace`:

```
Error: renderer/app/app.component.ts:13:3 - error TS2630: Cannot assign to 'stryNS_9fa48' because it is a function.

13   stryNS_9fa48 = retrieveNS;
     ~~~~~~~~~~~~
```

(and a bunch more).

The karma plugin responsible for compiling the files doesn't handle this error correctly and the result is: 0 tests executed.

The reason why this error occurs is because Stryker inserts mutants into the TS files. This in turn causes compiler errors (no way around that, because of [mutation switching](https://stryker-mutator.io/blog/announcing-stryker-4-mutation-switching/)). In order to prevent that, Stryker has a mechanism to insert "// @ts-nocheck" comments on top of each file. However, it only does that for files included by `"disableTypeChecks"` glob expression in stryker config. By default, only TS files inside the `src` and `test` directories are included. 

Adding this to your stryker.conf.mjs file solves it:

```diff
{
// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  _comment:
    "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/angular",
  mutate: [
    "renderer/**/*.ts",
    "!renderer/**/*.spec.ts",
    "!renderer/test.ts",
    "!renderer/environments/*.ts",
  ],
  testRunner: "karma",
  karma: {
    configFile: "karma.conf.js",
    projectType: "angular-cli",
    config: {
      browsers: ["ChromeHeadless"],
    },
  },
  reporters: ["progress", "clear-text", "html"],
  concurrency: 8,
  concurrency_comment:
    "Recommended to use about half of your available cores when running stryker with angular",
  coverageAnalysis: "perTest",
+ disableTypeChecks: "{renderer,test,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}", 
};
export default config;
```

**Comment by fmilke** [comment]
I still have some issue with the typescript checker, reporting no watcher registered for certain files.
But without the checkter it works fine. Only sad thing is, that some of the mutations rely on javascript intrinsic type-casting, which I try to escape from by using typescript. Does the checker, that I disabled, help with that?

I was really happy yesterday seeing some areas, where I definitely can improve my unit tests and not just satisfy some code coverage counter. Thanks for your hard work and support with this issue.

**Comment by nicojs** [comment]
> Does the checker, that I disabled, help with that?

Yes. It will check every mutant to see if it would result in a type error for TypeScript. If it does, it will report that mutant as `CompileError`, which results in invalid. You can still find it in your report if you dig a bit, but it won't count in your mutation score. It does come with a performance overhead, so whether you want to enable it or not is up to you.

> reporting no watcher registered for certain files

This is actually a known issue that was missing from our troubleshooting guide, [so I've added it](docs/stryker-js/troubleshooting/#error-when-running-stryker-with-the-typescript-checker-no-watcher-is-registered). Please have a look and tell me if this solves your problem.

> Thanks for your hard work and support with this issue.

You're welcome! 😅

**Comment by fmilke** [comment]
Changing the base `tsconfig.json` did not work for me. But for the `tsconfig.spec.json` it worked. Although I did not change the `excluded` field as described in the troubleshooting guide. Now everything is fine.

Again, thank you very much.

PS. The link is broken

**Comment by nicojs** [comment]
Yes, good point. The tsconfig file used by the `@stryker-mutator/typescript-checker` is the file configured in the `tsconfig` property in your stryker config file.

PS. fixed the link
