### ISSUE TITLE
expressionMutantPlacer could not place mutants with type(s): "MethodExpression".

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-js#3702]
**Summary**

 Original error: TypeError: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ConditionalExpression"

```
filesByDirectory[directoryName].forEach((file) => (directoryFiles[file[0].substr(directoryName.length + 1)] = file[1]));
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
**Stryker config**

https://github.com/stryker-mutator/mutation-testing-elements/blob/master/stryker.parent.json
https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/metrics/stryker.conf.js

**Test runner config**

Nothing special

**Stryker environment**

```
├── @stryker-mutator/core@6.1.2
├── @stryker-mutator/karma-runner@6.1.2
├── @stryker-mutator/mocha-runner@6.1.2
├── @stryker-mutator/typescript-checker@6.1.2
```

```
├── mocha@10.0.0
```

**Test runner environment**

```shell
tsc -b
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16
| npm              | 8
| Operating System | Linux (WSL)

**Add stryker.log**

https://github.com/stryker-mutator/mutation-testing-elements/runs/8043057065?check_suite_focus=true

**Comment by sgtwilko** [comment]
I'm seeing the same issue on a newly installed StrykerJS project (using typescript)
I've had to exclude `MethodExpression` to get this to run.
