### ISSUE TITLE
Pass thresholds via command line

### ISSUE THREAD

**Issue by JoaoGFarias** [stryker-mutator/stryker-js#3756]
Currently, thresholds can only be configured via the configuration file.
However, when running Stryker in a building pipeline, it can be interesting to have the ability to dynamically inject
the thresholds, rather than having to change the code. E.g. in a hotfix situation, where we may choose to be less rigid in creating great tests, the mutation score may decrease, but we still may want the build to succeed - thus I can make my build with more relaxed thresholds.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/1585655/193017160-0c961156-828e-4dfc-9e1a-ab8b46128ff2.png">

**Describe the solution you'd like**
We have commands such as 

`stryker run --threshold. "90, 80, 60"` (high, low, break)

or 

`stryker run --threshold.high 90 --threshold.low 80 --threshold.break 60`

**Describe alternatives you've considered**
No alternative, we already have thresholds in the config file.

**Comment by JoaoGFarias** [comment]
Note: I would be interested in implementing this feature - just let me know if it's a good idea and the design of the command we should be going.

**Comment by nicojs** [comment]
Sure, feel free to take a shot at it. I would personally like `--threshold.high 99` etc.
