### ISSUE TITLE
Change link to point to correct schema

### ISSUE THREAD

**Issue by Giovds** [stryker-mutator/stryker-js#3831]
**Summary**

While attempting to work on another issue I noticed that a link to the schema in the [Reporter](https://github.com/stryker-mutator/stryker-js/blob/28706dbe660e3156bc775c3465cbd2ce91f2e23f/packages/api/src/report/reporter.ts#L39) does not exist anymore. 

**Proposal**
It probably has to link to: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/report-schema/src/mutation-testing-report-schema.json

**Comment by nicojs** [comment]
Yes, please. :)
