### ISSUE TITLE
Supply suggestions to ignored directives referencing unknown Mutators

### ISSUE THREAD

**Issue by Giovds** [stryker-mutator/stryker-js#3844]
**Is your feature request related to a problem? Please describe.**
As pointed out in [#3812](https://github.com/stryker-mutator/stryker-js/issues/3812#issuecomment-1304431865) it would be cool if we could get a suggestion if an unused directive with a unknown Mutator has a close match to an existing Mutator.

**Describe the solution you'd like**
Let's keep the same example as in the original issue.

```js
const compare = (a, b) => {
  // Stryker disable next-line Equality: Wrong Mutator name
  return a - b >= 0 ? 1 : -1;
}

module.exports = { compare };
```
Perhaps we can check if the unknown Mutator partly matches with an existing one and/or implement some sort of fuzziness when typo's are made. This way we can create suggestions for the user, instead of just warning them what directives where not used.

Example for the CLI:

```diff
[Ignored] Equality
sum.js:2:1
- // Stryker disable next-line Equality: Hard to test
+ // Stryker disable next-line EqualityOperator: Hard to test
```
Or use a `~` and/or make the addition another colour (yellow e.g.), since we are not entirely sure this suggestion is correct.

This way the HTML view, and other reporters, can also benefit from this and show the same suggestions. You might even be able to share code between mutation-testing-elements (or mutation-testing-metrics) and Stryker.

Html could show something like this when you click on the ignored mutator:

![image](https://user-images.githubusercontent.com/27761321/200124553-e49d342e-0861-4ef0-93b2-04aa362e9100.png)
(I've just edited the HTML on a local page for example purposes)

**Describe alternatives you've considered**
\-

**Additional context**
Might depend on #3813

**Comment by nicojs** [comment]
I'm sorry for the misunderstanding, but I thought it would be cool to enable _bg coloring for mutant diffs, the way the HTML report does it_. I did some experiments, and this was the best result I got:

![image](https://user-images.githubusercontent.com/1828233/200943961-d6eabf1d-f2f6-4953-ad9d-55947e25e0ee.png)


Code:

```js
import chalk from 'chalk';

console.log('[NoCoverage] StringLiteral');
console.log(`${chalk.cyanBright('src/platform.ts')}:${chalk.yellowBright(8)}:${chalk.yellowBright(32)}`);
console.log(`${chalk.red.dim("-       return process.platform != ")}${chalk.bgRed.dim.redBright("'win32'")}${chalk.red.dim('")')}`);
console.log(`${chalk.green.dim('+       return process.platform != ')}${chalk.bgGreen.dim.greenBright('""')}${chalk.green.dim(';')}`);
```

Not better readable so perhaps not 🤷‍♀️.

I don't feel much for adding these to the HTML report and console reporter ATM. I think the warning you're implementing in #3842 will be sufficient.

**Comment by Giovds** [comment]
Ah that was a misunderstanding indeed :). Seems cool though! In that case this feature request is invalid.
