### ISSUE TITLE
Use configuration values to the patterns that are always ignored (`ignorePatterns`)

### ISSUE THREAD

**Issue by regseb** [stryker-mutator/stryker-js#3872]
**Is your feature request related to a problem? Please describe.**
if you change a file use by stryker (eg. `tempDirName`), you must remove old file and add new file in `ignorePatterns`:

```JSON
{
    "tempDirName": ".tmp/stryker",
    "ignorePatterns": ["!.stryker-tmp", ".tmp/stryker"]
}
```

**Describe the solution you'd like**
Use configuration values to the patterns that are always ignored (`ignorePatterns`):
`['node_modules', '.git', incrementalFiles, htmlReporter.fileName, jsonReporter.fileName, '*.tsbuildinfo', '/stryker.log', tempDirName]`

You can use this configuration:

```JSON
{
    "tempDirName": ".tmp/stryker"
}
```

**Comment by nicojs** [comment]
Thanks for opening this issue. I moved it to a `bug` and added the "Good first issue" label.
