### ISSUE TITLE
Naming TS Checker performance strategy 💭

### ISSUE THREAD

**Issue by danny12321** [stryker-mutator/stryker-js#3899]
While implementing [#3496 Implement mutant grouping in the `@stryker-mutator/typescript-checker`](https://github.com/stryker-mutator/stryker-js/issues/3496) I noticed that while grouping mutants not all compile errors are detected. The better performance is probably preferred for most, but we want to make it configurable in the typescript checker options to choose between performance and quality. Therefor we need to add an option to select the way of checking.

A couple of suggestions I have are:
- `checking-strategy` 1️⃣
  - individual
  - group
- `performance-mode` 2️⃣
  - accurate
  - fast
- `performance-mode` 3️⃣
  - performanceOverAccuracy
  - accuracyOverPerformance

I would like to know your thoughts so please vote (via emoji's) for your preferred options or leave a suggestion in the comments.

**Comment by odinvanderlinden** [comment]
I would suggest 
`
{
"typescript-checker": {"strategy": "performanceOverAccuracy"}
}
`
`
{
"typescript-checker": {"strategy": "accuracyOverPerformance"}
}
`
as the possible options

**Comment by nicojs** [comment]
All StrykerJS options are `camelCase`, so they should be `"typescriptChecker"`.

@danny12321, which one do you prefer?

I agree with @odinvanderlinden in that using the `xOverY` naming scheme makes the consideration obvious here.

We've talked about an even faster strategy coming maybe in the future, at the cost of even more accuracy. What would the name be for that strategy? `"mostPerformanceOverLeastAccuracy"`? I'm not sure.

**Comment by danny12321** [comment]
I prefer the generic option `accurate`, `fast`, etc. This way it is easier to add a new option and a user doesn't need to know how it is implemented.

The only problem I see that when there comes a faster option then `fast` the name would be something like `superFast`? And if that `superFast` option is also more accurate then `fast` should it be the `superFastSuperAccurate` strategy?

Maybe we should use names of sweets (or something like it) like Android does with it versions (Nougat, Oreo, Pie) and refer to a table with the considerations. This way users have to read the considerations and can not assume that the `fast` option is the fastest. I don't necessarily think this is the best solution but maybe something to think about.

**Comment by odinvanderlinden** [comment]
Another option i have in mind is to just use `grouping ` and `noGrouping` as the strategy names. And write about the effects of the different strategies in the Typescript checker plugin section in the stryker docs

**Comment by danny12321** [comment]
The option `grouping` seems clear to me, but doesn't that make every other option `noGrouping` @odinvanderlinden? And if we named the current way `individual` or something like we get the same problem... 🤔

**Comment by nicojs** [comment]
Let's go for... 🥁

```json
{
  "typescriptChecker": {
      "prioritizePerformanceOverAccuracy": false
   }
}
```

So a boolean. Decided with @hugo-vrijswijk  @richardwerkman @rouke-broersma @danny12321
