### ISSUE TITLE
[Docs] Some properties aren't in the Configuration page

### ISSUE THREAD

**Issue by regseb** [stryker-mutator/stryker-js#3996]
Hello,

Some properties don't have a description in the [Configuration](https://stryker-mutator.io/docs/stryker-js/configuration/) page:

- [`eventReporter`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L303-L307)
- [`packageManager`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L377-L384)
- [`appendPlugins`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L395-L402)
- [`htmlReporter`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L415-L419)
- [`jsonReporter`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L420-L424)
- [`tsconfigFile`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L489-L493)
- [`warnings`](https://github.com/stryker-mutator/stryker-js/blob/79cc05f/packages/api/schema/stryker-core.json#L494-L505)

**Comment by nicojs** [comment]
Yes, indeed. This should be addressed.

 Feel free to create a PR to document all of them.
