### ISSUE TITLE
Error on running stryker on a React Native project

### ISSUE THREAD

**Issue by alvessteve** [stryker-mutator/stryker-js#4004]
**Is your feature request related to a problem? Please describe.**
StrykerJS supports React project (cf see [`there`](https://stryker-mutator.io/docs/stryker-js/guides/react/)), however it doesn't seems to support React Native ones. 
Adding mutation testing on a RN project could improve the quality of testing and code on mobile apps.

**Describe the solution you'd like**
When running `stryker run` on a RN project, no errors are thrown. Currently, here is the bug thrown:

![Capture d’écran 2023-03-01 à 18 03 59](https://user-images.githubusercontent.com/29439916/222211825-0e6f860f-f6a5-4c03-900c-df8398b0ff40.png)

**Comment by nicojs** [comment]
@alvessteve thanks for opening this issue. It seems an error to do with copying the file to the sandbox. This is unusual. Can you provide a reproduction repository ?

**Comment by alvessteve** [comment]
thank you for the quick response @nicojs. Here is the example i used: https://github.com/alvessteve/stryker-react-native

**Comment by nicojs** [comment]
Thanks, @alvessteve, and sorry it took so long for me to return to you.

Unfortunately, I can't reproduce your issue. With some minor changes, it works for me. See https://github.com/alvessteve/stryker-react-native/pull/1

**Comment by alvessteve** [comment]
no worries ! :) 
Thank you for having taken the time to check the issue and making the PR. I see much better what changed.
