### ISSUE TITLE
Progress reporter's "remaining" show too big value

### ISSUE THREAD

**Issue by mkizka** [stryker-mutator/stryker-js#4018]
**Summary**
Progress reporter's "remaining" show too big value when coverageAnalysis is "perTest" and ignoreStatic is false.
These are mutation test results in my project.

### coverageAnalysis: "perTest", ignoreStatic: false
Done in 10m 26s, **but remaining shows 12h 51m(max).**
PR: https://github.com/mkizka/soshal/pull/2
Action: https://github.com/mkizka/soshal/actions/runs/4365328140/jobs/7633794741
```
14:33:24 (1970) INFO DryRunExecutor Initial test run succeeded. Ran 38 tests in 4 seconds (net 334 ms, overhead 3985 ms).
14:33:24 (1970) WARN MutantTestPlanner Detected 165 static mutants (18% of total) that are estimated to take 79% of the time running the tests!
  You might want to enable "ignoreStatic" to ignore these static mutants for your next run. 
  For more information about static mutants visit: https://stryker-mutator.io/docs/mutation-testing-elements/static-mutants.
  (disable "warnings.slow" to ignore this warning)
Mutation testing 0% (elapsed: <1m, remaining: ~4h 11m) 497/913 tested (5 survived, 0 timed out)
Mutation testing 0% (elapsed: <1m, remaining: ~6h 23m) 507/913 tested (8 survived, 0 timed out)
.
.
.
Mutation testing 0% (elapsed: ~1m, remaining: ~12h 51m) 585/913 tested (13 survived, 0 timed out)
```

### coverageAnalysis: "perTest", ignoreStatic: true
Done in 5m 35s, remaining shows 10m(max)
PR: https://github.com/mkizka/soshal/pull/4
Action: https://github.com/mkizka/soshal/actions/runs/4365472509/jobs/7634136417
```
14:49:57 (2097) INFO DryRunExecutor Initial test run succeeded. Ran 38 tests in 3 seconds (net 237 ms, overhead 3011 ms).
Mutation testing 3% (elapsed: <1m, remaining: ~4m) 500/748 tested (6 survived, 0 timed out)
Mutation testing 5% (elapsed: <1m, remaining: ~6m) 513/748 tested (9 survived, 0 timed out)
.
.
.
Mutation testing 10% (elapsed: ~1m, remaining: ~10m) 572/748 tested (12 survived, 0 timed out)
```

### coverageAnalysis: "off"
Done in 13m 12s, remaining shows 4m(max)
PR: https://github.com/mkizka/soshal/pull/3
Action: https://github.com/mkizka/soshal/actions/runs/4365335825/jobs/7633813669
```
14:34:12 (1850) INFO DryRunExecutor Initial test run succeeded. Ran 38 tests in 4 seconds (net 353 ms, overhead 3975 ms).
Mutation testing 6% (elapsed: <1m, remaining: ~2m) 63/913 tested (58 survived, 0 timed out)
Mutation testing 22% (elapsed: <1m, remaining: ~1m) 205/913 tested (197 survived, 0 timed out)
Mutation testing 23% (elapsed: <1m, remaining: ~1m) 216/913 tested (203 survived, 0 timed out)
.
.
.
Mutation testing 32% (elapsed: ~2m, remaining: ~4m) 295/913 tested (219 survived, 0 timed out)
```

**Stryker config**
```js
const config = {
  packageManager: "pnpm",
  reporters: ["progress", "html"],
  testRunner: "jest",
  coverageAnalysis: "perTest",
  plugins: ["@stryker-mutator/jest-runner"],
};
```

**Test runner config**
https://github.com/mkizka/soshal/blob/013cb834524d55f5f369127cfac373d5884ef26c/jest.config.ts

**Stryker environment**
```
    "@stryker-mutator/core": "^6.4.1",
    "@stryker-mutator/jest-runner": "^6.4.1",
```
```
    "jest": "^29.3.1",
```

**Test runner environment**
```shell
$ jest
```

**Your Environment**
ubuntu-latest ( GitHub Actions )
https://github.com/mkizka/soshal/blob/09b0d7eab1a6ad15595440cd9e6fc2030be3edb6/.github/workflows/mutation-test.yml

**Add stryker.log**
- coverageAnalysis: "perTest", ignoreStatic: false ... [stryker.log](https://github.com/stryker-mutator/stryker-js/files/10932835/stryker.log)
- coverageAnalysis: "perTest", ignoreStatic: true ... [stryker.log](https://github.com/stryker-mutator/stryker-js/files/10932848/stryker.log)
- coverageAnalysis: "off" ... [stryker.log](https://github.com/stryker-mutator/stryker-js/files/10932858/stryker.log)

**Comment by nicojs** [comment]
Hi, @mkizka thanks for the detailed analysis. See also #3740

First, giving a 100% correct estimation is impossible for many reasons:
- A surviving mutant is much slower than a killed mutant
- A timeout mutant is much slower than a surviving or killed mutant 
- Other processes running on your machine

After the initial test run, the progress reporter tries to estimate the amount of _work_ (or `ticks`) it takes to run each mutant. This is part of the code that does that:

https://github.com/stryker-mutator/stryker-js/blob/master/packages/core/src/reporters/progress-keeper.ts#L29-L37

In short:
1. Mutants without coverage (without `runPlan`) are ignored (this is correct)
1. The net time it would take to run all tests for the mutant is used. So the reporter assumes the mutant will survive.
1. When a mutant is static (so `reloadEnvironment` is enabled), the `overhead` is added to the work. So the reporter assumes the test runner needs to reload the test environment.

The problem in this example is with step 3. You're using the jest test runner. This is a test runner that can run static mutants without having to reload the test environment. Adding that information to the progress reporter will help here.

**Comment by mkizka** [comment]
Sorry, I didn't check the existing issue. 
Thank you for the detailed explanation. I understand that correct estimate is difficult.

> This is a test runner that can run static mutants without having to reload the test environment.

Does this mean that there is no need to add overhead to the Jest runner?

```js
     if (runOptions.reloadEnvironment) { 
       ticks += this.timing.overhead; 
     } 
```

**Comment by nicojs** [comment]
Yes exactly. So I think that would solve this issue: 

> Done in 10m 26s, **but remaining shows 12h 51m(max).**

The other inconsistencies may be explained by having many surviving mutants initially, so the progress reporter gives a pessimistic outlook. What do you think?

**Comment by nicojs** [comment]
I've tested the fix locally with your project, and it seems to have improved the "coverageAnalysis: "perTest", ignoreStatic: false" scenario a lot. 

The progress reporter remains a bit pessimistic when `jest.enableFindRelatedTests: true`, because [find related tests](https://jestjs.io/docs/cli#--findrelatedtests-spaceseparatedlistofsourcefiles) is a jest (and vitest) specific performance optimization that Stryker ignores. 

Ultimately we could support improved progress reporting for `--findRelatedTests`, but time spent improving that cannot be spent implementing other things.

**Comment by mkizka** [comment]
It looks good.
Since we cannot make correct estimates, it would be better to focus on improvements that can be made with relatively little effort.
Also, I think it's better for the reporter to be pessimistic rather than optimistic.

**Comment by mkizka** [comment]
By the way, why doesn't the same issue occur when `coverageAnalysis: "all"`? It seems to be the same in terms of reloading the environment. 
What are the implementation differences between "perTest" and "all"? (I have read the [documentation](https://stryker-mutator.io/docs/stryker-js/configuration/#coverageanalysis-string))

```
Mutation testing 3% (elapsed: <1m, remaining: ~5m) 499/913 tested (5 survived, 0 timed out)
Mutation testing 6% (elapsed: <1m, remaining: ~4m) 513/913 tested (9 survived, 0 timed out)
Mutation testing 9% (elapsed: <1m, remaining: ~4m) 525/913 tested (12 survived, 0 timed out)
```
https://github.com/mkizka/soshal/pull/5
https://github.com/mkizka/soshal/actions/runs/4392357369/jobs/7692079166
