### ISSUE TITLE
Mutation: project is not really sandboxed: mutliple mutants are executed within the same sandbox

### ISSUE THREAD

**Issue by homersimpsons** [stryker-mutator/stryker-js#4034]
**Summary**

Using jest runner with globalSetup and globalTeardown seems to "break" the test runner.

In fact it looks like the runner does not (always?) trigger globalTeardown.

**Stryker project**

Here is a test project to showcase the behavior: https://github.com/homersimpsons/stryker-jest-async

On one run I have 5  "Runtime errors" (about half of all the mutants) due to a `file.txt` not deleted

Note that the `odd.js` function has 3 `else if` just to generate mutants.

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v18.15.0
| npm              | 9.5.0
| Operating System | Ubuntu 22.04.2 LTS

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/11001851/stryker.log)

If you need anymore details feel free to ask.

If you have any reduction, feel free to open a Pull request to help diagnose the issue.

**Comment by homersimpsons** [comment]
I just reduced a lot the test case.

The issue does not involve async. I think the issue is that the globalTeardown is not (always?) called

**Comment by nicojs** [comment]
Hi @homersimpsons (😍 love the username!)

This is a classic case of shared resources across multiple workers. Stryker runs jest multiple times in parallel in _the same sandbox directory_. So it is probable that the file was created by one worker, and another worker is also trying to create it. 

To solve this issue you can either run with `--concurrency 1`, or use the `process.env.STRYKER_MUTATOR_WORKER` to create a file per worker..

See also https://stryker-mutator.io/docs/stryker-js/parallel-workers/

**Comment by homersimpsons** [comment]
> This is a classic case of shared resources across multiple workers. Stryker runs jest multiple times in parallel in _the same sandbox directory_. So it is probable that the file was created by one worker, and another worker is also trying to create it.

Okay, this is exactly the cause. Because there were multiple sandbox directories I thought that Stryker was running one mutation per sandbox.

Maybe this should be clarified somewhere in the documentation ? I cannot seem to remember reading this.

> To solve this issue you can either run with `--concurrency 1`, or use the `process.env.STRYKER_MUTATOR_WORKER` to create a file per worker..

Thank you for the approaches suggestions. I will try with the `--concurrency 1` flag, if this is too long I will update the tests to use the `process.env.STRYKER_MUTATOR_WORKER` environment variable.

> See also https://stryker-mutator.io/docs/stryker-js/parallel-workers/

Yes I did check that, but as this was mentioning the database use case I thought this was not applicable to my use case, because of course all the test will use the same database. But to me the test directories were isolated one from the other (thanks to the sandboxing).
