### ISSUE TITLE
Error in tap runner: `Error: EBUSY: resource busy or locked`

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#4122]
Our pipeline is flaky because of the recently added tap-runner package:
> Error: EBUSY: resource busy or locked, rmdir 'D:\a\stryker-js\stryker-js\packages\tap-runner\testResources\tmp\workDir-5612723'

This indicates that the actual child process that runs the tests isn't fully closed when the tap runner plugin resolves. This might lead to bad things, because the next mutant might be started, which might cause high CPU load --> process starvation --> false timeouts.. 

I've investigated this a bit, and I think the `complete` callback provided to `tap-runner` gets executed before the child process is completed:

https://github.com/tapjs/tap-parser/blob/a46c1a01e3bb308ff97a93f13b7cca3f782e0e14/src/index.ts#L477

See also for an example: https://github.com/stryker-mutator/stryker-js/actions/runs/4724456135/jobs/8381692413?pr=4121#step:5:3413

It might be best to convert both the [spawn](https://github.com/stryker-mutator/stryker-js/blob/master/packages/tap-runner/src/tap-test-runner.ts#L131) and [the parser complete callback](https://github.com/stryker-mutator/stryker-js/blob/master/packages/tap-runner/src/tap-test-runner.ts#L136) to promises that you can then wait on with `Promise.all`.

**Comment by nicojs** [comment]
@danny12321 would you mind picking this one up?

**Comment by danny12321** [comment]
Yes I will look into it.

**Comment by danny12321** [comment]
@nicojs I have added a test that ensures that the process has exit before resolving the result, but I am not very happy about the way the `spawn`  method and `TapParser` class are mocked. My experience isn't that great with Sinon and ran into some weird problems so could we please sit together to make it a bit prettier?

**Comment by nicojs** [comment]
Sure. For now feel free to merge it. We'll look at it later 👍

**Comment by danny12321** [comment]
#4123 is merged. Closing this issue.
