### ISSUE TITLE
Process not exiting with expected code (Failure : 1)

### ISSUE THREAD

**Issue by antoinezanardi** [stryker-mutator/stryker-js#4160]
**Summary**

When setting `threshold.break` in the stryker config file and final score doesn't reach the value, the exit code is not `1` as expected but `0`.  Here is the output that Stryker gave me : 

```bash
13:57:39 (2527) ERROR MutationTestReportHelper Final mutation score 99.90 under breaking threshold 100, setting exit code to 1 (failure).
13:57:39 (2527) INFO MutationTestReportHelper (improve mutation score or set `thresholds.break = null` to prevent this error in the future)
13:57:39 (2527) INFO MutationTestExecutor Done in 2 minutes 3 seconds.

Process finished with exit code 0
``` 

As you can see, I'm under the `break` set to `100`, but the program exit with `0`.

**Stryker config**

```json
{
  "$schema": "../../node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "cleanTempDir": true,
  "incremental": true,
  "incrementalFile": "tests/stryker/incremental.json",
  "checkers": ["typescript"],
  "tsconfigFile": "tsconfig.json",
  "testRunner": "jest",
  "ignoreStatic": true,
  "mutate": [
    "src/**/*.ts",
    "!**/*.dto.ts",
    "!**/*.schema.ts",
    "!**/*.constant.ts"
  ],
  "jest": {
    "configFile": "config/jest/jest-global.ts"
  },
  "reporters": [
    "clear-text", "progress", "html", "json"
  ],
  "htmlReporter": {
    "fileName": "tests/stryker/coverage/index.html"
  },
  "jsonReporter": {
    "fileName": "tests/stryker/coverage/mutation.json"
  },
  "thresholds": {
    "high": 100,
    "low": 100,
    "break": 100
  }
}
```

**Test runner config**

```typescript
import type { Config } from "jest";

const config: Config = {
  moduleFileExtensions: ["js", "ts"],
  rootDir: "../../",
  testEnvironment: "node",
  testRegex: ["tests/unit/.+.spec.ts", "tests/e2e/.+.e2e-spec.ts"],
  transform: { "^.+\\.(t|j)s$": "ts-jest" },
  verbose: true,
  resetMocks: true,
  restoreMocks: true,
  clearMocks: true,
  setupFiles: ["<rootDir>/tests/global-setup.ts"],
  setupFilesAfterEnv: ["jest-extended/all"],
  coverageReporters: ["clover", "json", "lcov", "text", "text-summary"],
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/main.ts",
    "!src/**/*dto.ts",
    "!src/**/*.schema.ts",
  ],
  coverageDirectory: "tests/coverage",
  coverageThreshold: {
    global: {
      statements: 100,
      lines: 100,
      branches: 100,
      functions: 100,
    },
  },
};

export default config;
```

**Stryker environment**

```bash
├── @stryker-mutator/core@6.4.2
├── @stryker-mutator/jest-runner@6.4.2
├── @stryker-mutator/typescript-checker@6.4.2
```

```bash
├── @stryker-mutator/jest-runner@6.4.2
├── @types/jest-when@3.5.2
├── @types/jest@29.5.1
├── jest-extended@3.2.4
├── jest-when@3.5.2
├── jest@29.5.0
├── ts-jest@29.1.0
```

**Test runner environment**

```shell
# Test command
NODE_ENV=test jest --config config/jest/jest-global.ts
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v20.0.0
| npm              | 9.6.6
| Operating System | MacOS

**Log file**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/11397293/stryker.log)

**Comment by nicojs** [comment]
Hi @antoinezanardi thanks for opening this issue. 

> Process finished with exit code 0

What exactly is printing that message? 

I can't reproduce this. When I for example set `thresholds.break` to `100` and run this on Stryker's core: `npm run stryker -- --incremental --concurrency 2 || echo 'FAILED'` it prints "FAILED" at the end (indeed, Stryker itself doesn't have 100% mutation score 😅).

Could you try running Stryker directly locally: `npx stryker run` and print the last exit code? On bash or git bash, you can use `echo $?`. In Powershell, you should be able to use `echo $LASTEXITCODE`.

**Comment by antoinezanardi** [comment]
Hi @nicojs ! Thanks for the fast reply.

> Process finished with exit code 0

Is the message printed by the WebStorm IDE, so I can easily check the exit code.

While following your instructions, I found that the problem was my `package.json` command :

```bash
NODE_ENV=test rimraf tests/stryker/coverage && stryker run config/stryker/stryker.conf.json || rimraf .stryker-tmp/
```

Even if the first part (stryker) was falling, it was backed up by `|| rimraf .stryker-tmp/`. I'll change it to `|| rimraf .stryker-tmp/ && exit 1`.

However, I added the second part because if one test fails in the initial test run before the stryker process, the `.stryker-tmp/` is not deleted, even if it's defined in the config file. Is there a way to get around this behavior and delete the folder anyway ?

Thanks again for your help and sorry for the false issue.

**Comment by nicojs** [comment]
Ah of course. We leave the `.stryker-temp` dir when Stryker is not successful because you might want to debug the error. You can [configure `cleanTempDir`](https://stryker-mutator.io/docs/stryker-js/configuration/#cleantempdir-boolean), but it is a boolean and `true` means "clean on success". 

We could add an option `'always'`.

**Comment by antoinezanardi** [comment]
It would be great ! Do you want me to create another issue related to this possible feature or do we keep this one open ?

**Comment by nicojs** [comment]
Opening a new feature request is probably better; yes, feel free to do so 👐.

**Comment by adeelpm** [comment]
@nicojs @antoinezanardi Hi I would like to work on this Good first issue

**Comment by antoinezanardi** [comment]
I created an issue for this use-case, I'm closing this one ! 

Thanks for your help.
