### ISSUE TITLE
Always remove `stryker-tmp` folder, even if stryker is failing

### ISSUE THREAD

**Issue by antoinezanardi** [stryker-mutator/stryker-js#4173]
**Is your feature request related to a problem? Please describe.**

When running `stryker`, `stryker-tmp` folder is created. In the config file, you can set the `cleanTempDir` to `true` to delete it after the process. But, if the process fail, `stryker-tmp` folder is not deleted for debugging purposes. I would like it to be deleted anyway. 
 
**Describe the solution you'd like**

In config file, a new option could be added to *always* delete the folder. Could be named `alwaysCleanTempDir`. Or, if it doesn't make a breaking change, adapt the existing `cleanTempDir` to accept both a `boolean` or one of the following options :

```typescript
type cleanTempDirValues = boolean | "always" | "on-success" | "never"
```

**Describe alternatives you've considered**

For the moment, in order to always delete this folder, I run stryker like this : 

```bash
stryker run config/stryker/stryker.conf.json || (rimraf .stryker-tmp/ && exit 1)
```

In that way, the folder is deleted if the first command fail (`exit code 1`).

**Additional context**

This feature request is related to another issue I created #4160.

**Comment by ArnaudBuchholz** [comment]
I use a `pretest` command to rimraf .stryker-tmp ;-)
