### ISSUE TITLE
Add additional config options to clear-text reporter 

### ISSUE THREAD

**Issue by C-Klug** [stryker-mutator/stryker-js#4209]
**Describe the solution you'd like**
Currently, the user, when using clear-text, does not have any options when it comes to the amount of information that is logged. Additional options (boolean controls) to control the three 'functions' (reportAllTests, reportAllMutants, ClearTextScoreTable) would give the user much more flexibility and control when using the clear-text reporter.

**Additional context**
Although I don't have the most amount of time on my hands, I did throw together a branch with the related changes included within it. It is very bare bones and does not dive into changing/implementing tests for this change of functionality, but I wanted to give a solid example of the new feature I am describing.  Link to the branch can be found: [here](https://github.com/C-Klug/stryker-js/commit/8c2a8ef96ea3e0e7465d9effcfa300f76fad91c1)

**Comment by nicojs** [comment]
Sure, sounds good. If someone wants to pick it up, feel free to do so ☺️
