### ISSUE TITLE
missing vitest option in `stryker init` command

### ISSUE THREAD

**Issue by rluvaton** [stryker-mutator/stryker-js#4288]
**Summary**

The vitest runner was released: in v7.0.0 
- https://github.com/stryker-mutator/stryker-js/issues/3465#issuecomment-1574091212

but using the `stryker init` the vitest test runner is not one of the options

**Stryker environment**

```
@stryker-mutator/core@7.0.2
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16.18.1
| npm              | 8.19.2
| Operating System | macOS

**Comment by nicojs** [comment]
Yep, true. We're querying https://npms.io during `stryker init` to get the list of test runners. That way, any community plugins would also be suggested (although they don't exist yet)

This is the query we use: https://api.npms.io/v2/search?q=keywords:@stryker-mutator/test-runner-plugin

`@stryker-mutator/vitest-runner` and `@stryker-mutator/tap-runner` apparently didn't reach the cache of npms.io yet. Unsure if we should hardcode the list or wait for their cache to update 🤷‍♂️

**Comment by nicojs** [comment]
Hmm I think it is safe to switch to `npm search --json 'keywords:@stryker-mutator/test-runner-plugin'` instead of this API call. There seem to be more issues regarding caching: https://github.com/npms-io/npms/issues/58

**Comment by nicojs** [comment]
Finally found the api docs: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md

Keyword search is explicitly mentioned. Let's migrate to that endpoint.

In the meantime, the workaround is to choose the "command" test runner, change it to `"vitest"` and install `@stryker-mutator/vitest-runner` manually.

**Comment by rluvaton** [comment]
Thanks for the quick resolve

**Comment by nicojs** [comment]
You're welcome. ❤️ Will be released in a week or two

**Comment by nicojs** [comment]
Released in 7.1
