### ISSUE TITLE
@stryker-mutator/core peerDependency is still on v6.4.2

### ISSUE THREAD

**Issue by antoinezanardi** [stryker-mutator/stryker-js#4311]
**Question**

Is it normal that `@stryker-mutator/jest-runner` and `@stryker-mutator/typescript-checker` has a peerDependency `@stryker-mutator/core` set to `v^6.4.0` ? 

Because of that, dependabot won't update `@stryker-mutator/core`… Is it intended ?

**Stryker environment**

```
"@stryker-mutator/core": "^6.4.2",
"@stryker-mutator/jest-runner": "^7.0.0",
"@stryker-mutator/typescript-checker": "^7.0.0",
```

**Additional context**

Here is for example the `package.json` file of `@stryker-mutator/typescript-checker@7.0.0` :

```json
"dependencies": {
    "@stryker-mutator/api": "7.0.0",
    "@stryker-mutator/util": "7.0.0",
    "semver": "~7.5.0"
  },
  "devDependencies": {
    "@stryker-mutator/test-helpers": "7.0.0",
    "@types/semver": "7.5.0"
  },
  "peerDependencies": {
    "@stryker-mutator/core": "^6.4.0", // <-- Why is it not set to 7.0.0 ?
    "typescript": ">=3.6"
  },
```

**Comment by nicojs** [comment]
Nope, it's a bug. You should upgrade to `7.0.1`.

Updating peer deps was a manual task. I've added a script to prevent these fuckups in the future: https://github.com/stryker-mutator/stryker-js/commit/b159f73a9b8327c6cc1694a4c1b76b58d7701430
