### ISSUE TITLE
Tap runner should correctly report time spent when tap output lacks time

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#4331]
**Summary**

The tap-runner currently relies on test reporting from the `timeSpentMs`. However, time reporting in TAP output is optional.

<details>
<summary>With timing</summary>

```
nicojs@NicoJ01 ~/github/stryker-js/packages/tap-runner/testResources/example (master)$ node tests/math.spec.js
TAP version 13
# Subtest: Adding two numbers
    ok 1 - Adding 10 and 5 equal to 15
    ok 2 - Adding 100 and 200 equal to 300
    1..2
ok 1 - Adding two numbers # time=3.708ms

# Subtest: Slow adding two numbers
    ok 1 - Adding 10 and 5 equal to 15
    ok 2 - Adding 100 and 200 equal to 300
    1..2
ok 2 - Slow adding two numbers # time=0.604ms

1..2
# time=8.128ms
```

</details>

<details>
<summary>Without timing</summary>

```
nicojs@NicoJ01 ~/github/stryker-js/packages/tap-runner/testResources/ava (master)$ npx ava --tap tests/math.spec.js
TAP version 13

1..0
# tests 0
# pass 0
# fail 0
```

</details>

The code that grabs timing info from tap output is here: https://github.com/stryker-mutator/stryker-js/blob/master/packages/tap-runner/src/tap-test-runner.ts#L156

This has 2 consequences:

1. The timeout calculation doesn't work correctly, which can result in unexpected false positives regarding mutants that are reported as `timout` 
2. The progress reporter reports `NaN` as progress because it relies on the net time to report progress (and net time is always `0`). See https://github.com/ericcornelissen/shescape/pull/991#issuecomment-1605494916

To solve this issue, I think we should use our own timeout calculation based on elapsed time when the timing is not provided in TAP output. 

```ts
const now = () => new Date();
const before = now();
// Run file
const elapsedMs = now().getTime() - before.getTime();
```

**Comment by danny12321** [comment]
Shouldn't we always use our own time calculation, because than we can also encounter for the time it takes to start the child process?
