### ISSUE TITLE
Using stryker & vitest runner & JSDOM in UI test cannot PASS dry run

### ISSUE THREAD

**Issue by InfiniteXyy** [stryker-mutator/stryker-js#4336]
**Summary**

When using vitest to test UI components, run with `npx vitest run` will PASS, but `npx stryker run` will FAIL in dry run.

The root cause is **the global jsdom environment was shared in stryker testing, while isolated in vitest unit test.**

I found that it was because of this setting:
https://github.com/stryker-mutator/stryker-js/blob/master/packages/vitest-runner/src/vitest-test-runner.ts#L46C24-L46C24

```js
this.ctx = await vitestWrapper.createVitest('test', {
  config: this.options.vitest?.configFile,
  threads: true,
  coverage: { enabled: false },
  singleThread: true, // <----- This single thread causing issue
  watch: false,
  dir: this.options.vitest.dir,
  bail: this.options.disableBail ? 0 : 1,
  onConsoleLog: () => false,
});
```
This issue was also introduced in `vitest` [document](https://vitest.dev/config/#singlethread)

I use `patch-package` and set `singleThread` to `false`, seems everything works fine for me. Is it OK to use `false` here, and what's the side effect?

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/react",
  "tempDirName": "stryker-tmp",
  "mutate": ["src/**/*.{j,t}s?(x)", "!src/**/*.test.tsx", "!src/setupTests.ts"],
  "ignorePatterns": [
    "node_modules",
    "build",
    "coverage",
    ".git",
    "/reports",
    "*.tsbuildinfo",
    "/stryker.log",
    ".stryker-tmp"
  ],
  "testRunner": "vitest",
  "vitest": {
    "configFile": "./vite.config.ts"
  },
  "reporters": ["progress", "clear-text", "html"],
  "symlinkNodeModules": true,
  "coverageAnalysis": "off",
  "tsconfigFile": "tsconfig.json",
  "dryRunTimeoutMinutes": 20,
  "timeoutMS": 60000,
  "timeoutFactor": 4
}
```

**Stryker environment**

```
+-- @stryker-mutator/core@7.1.0
+-- @stryker-mutator/vitest-runner@7.1.0
```

```
+-- vitest@0.32.2
```

**Test runner environment**

```shell
# Test command
vitest run
# Mutation test command
stryker run
```

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import "vitest/config";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    setupFiles: ["./src/setupTests.ts"],
    environment: "jsdom",
    singleThread: true,
  },
});

```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 18.8.0
| npm              | 9.7.1
| Operating System | MacOS 13.4 (M1 Pro)

**Demo Project**
It's really easy to reproduce this issue in the demo project
https://github.com/InfiniteXyy/stryker-vitest-issue

**Comment by nicojs** [comment]
Thanks for opening this issue. I believe `singleThread` might not be strictly needed. We started with `singleThread` as requirement because we tried to communicate with the test environment via the global object, but we have since moved away from using the global object for this.

We might be facing issues with concurrency. Vitest must run with concurrency 1, since Stryker is already running mutation testing in parallel (1 worker per core). As long as we can force that ([maxConcurrency](https://vitest.dev/config/#maxconcurrency) to 1?), it should be fine.

@odinvanderlinden, what are your thoughts?

**Comment by odinvanderlinden** [comment]
Ah yes that makes sense `maxConcurrency = 1` it is

**Comment by InfiniteXyy** [comment]
Thank you for the updating!

But when I tried to use `singleThread = false` and `maxConcurrency  = 1`, seems the mutation score is very slow (most files 0%) Don't know what happened

**Comment by odinvanderlinden** [comment]
When i set `singleThead = false` and `maxConcurrency = 1` on your demo project it seems to work fine. Can you confirm this? If so, what is the difference with your real project?

**Comment by InfiniteXyy** [comment]
> When i set `singleThead = false` and `maxConcurrency = 1` on your demo project it seems to work fine. Can you confirm this? If so, what is the difference with your real project?

**This issue only happens when there are multiple mutated files.**

Sometimes, the `App.tsx` has 100 score, sometimes, the `App2.tsx` has 100 score

I pushed a new commit to the demo project. Maybe you could have a try, not sure 

<img width="793" alt="image" src="https://github.com/stryker-mutator/stryker-js/assets/26314308/7092e0a0-557c-4dc5-9528-8bb21731e104">
<img width="815" alt="image" src="https://github.com/stryker-mutator/stryker-js/assets/26314308/f9b16149-10d5-47ed-84ff-6bcbcac2ab94">

**Comment by odinvanderlinden** [comment]
Thanks for the quick reply, i will further investigate this issue this afternoon!

**Comment by danny12321** [comment]
I think I found the problem. The so called `projectName` of the vitest suites are `undefined`. Before iterating all the test suites the duplicates are filtered out by the value of the project name. So one of the two test suites will always be filtered out. The solution will be simple by checking for the filename for duplicates, but I don't really know the reason behind the decision to use the project name.

https://github.com/stryker-mutator/stryker-js/blob/cf5d4d04ee24a1e2b65c1f7ae35dbc840edbd48a/packages/vitest-runner/src/vitest-test-runner.ts#L168

@odinvanderlinden can you fix this?
