### ISSUE TITLE
Humans and mutants are friends, not enemies!

### ISSUE THREAD

**Issue by limonte** [stryker-mutator/stryker-js#4374]
First of all, thank you so much for this super useful tool 🙌 🙌 🙌 

I've recently discovered it and it's extremely helpful in the project I'm working on.

---

I disagree with the slogan on the logo

<img width="511" alt="CleanShot 2023-07-20 at 16 07 44@2x" src="https://github.com/stryker-mutator/stryker-js/assets/6059356/9b0bf2c7-c1fd-443a-b726-3978b280050d">

We're not killing mutants! Mutants are our best friends to find and kill our true enemy which is bugs!

Mutants probably have families, it's not cool to kill 'em. I'd change the slogan to represent friendship and partnership between humans and mutants, something like humans and mutant are best friends ☺️

**Comment by odinvanderlinden** [comment]
Hi @limonte, this is not the place for these kind of messages 😉. You should join our [Slack](https://join.slack.com/t/stryker-mutator/shared_invite/enQtOTUyMTYyNTg1NDQ0LTU4ODNmZDlmN2I3MmEyMTVhYjZlYmJkOThlNTY3NTM1M2QxYmM5YTM3ODQxYmJjY2YyYzllM2RkMmM1NjNjZjM) channel for discussing this. I'm closing this issue
