### ISSUE TITLE
stryker init option missing

### ISSUE THREAD

**Issue by Tarun-k-Gupta** [stryker-mutator/stryker-js#4613]
Not sure if any framework is required since I am not using any framework. And simply I have HTML, CSS and JS files. 
Which option should be chosen in this naive case?

**Comment by Tarun-k-Gupta** [comment]
Got it! Thanks for the clarification.

**Comment by nicojs** [comment]
Great, if you have any other issues, don't hesitate to ask.

If you think we could clarify this, don't hesitate to suggest an improvement 🤗
