### ISSUE TITLE
Coverage reporting in vitest browser mode doesn't always work

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#4634]
**Summary**

Running stryker on [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements) reports a score that is _far to low_. The reason is that coverage reporting isn't working correctly (it underreports coverage).

I'm investigating is https://github.com/stryker-mutator/mutation-testing-elements/pull/2882.

**Comment by hugo-vrijswijk** [comment]
I think this works since vitest v2. I've enabled mutation testing in the elements package again and it seems to report accurately

**Comment by nicojs** [comment]
True
