### ISSUE TITLE
Does stryker.js have a feature to take advantage of Jest sharding?

### ISSUE THREAD

**Issue by JasonShin** [stryker-mutator/stryker-js#4806]
**Question**

Hello, I am trying out stryker-js in my project. The project is quite large and stryker.js can create up to 20k mutants to test.

I'm wondering, in this scenario, is there any feature provided in stryker.js that can work together with [Jest sharding?](https://medium.com/@mfreundlich1/speed-up-your-jest-tests-with-shards-776e9f02f637). Jest sharding can take the current CI [worker index of the parallel workers](https://buildkite.com/docs/tutorials/parallel-builds), and evenly split up tests based on the current worker index.

Please let me know if there's anything in Stryker.js to
- take advantage of the CI parallel worker feature
- if it's possible to gather up mutation reports from multiple agents and consolidate the reports into a single report

**Stryker environment**

```
"@stryker-mutator/core": "^8.2.6",
"@stryker-mutator/jest-runner": "^8.2.6",
"@stryker-mutator/typescript": "^4.0.0",
"@stryker-mutator/typescript-checker": "^8.2.6",
```

```
jest: ^29.4.1
```

**Additional context**

**Comment by nicojs** [comment]
We currently don't have a feature like jest sharding. How would such a feature work together with Jest Sharding? As I see it, mutants should be sharded, not tests. So we should implement our own sharding, right?

Have you looked at implementing `--incremental` mode in CI? As explained in this blog article: https://stryker-mutator.io/blog/announcing-incremental-mode/#-continuous-integration-ci. Would that also solve your problem?

**Comment by JasonShin** [comment]
@nicojs thanks for the reply. I think you are right, Jest sharding wouldn't bring much value as you've highlighted stryker.js already supported the incremental mode (thanks).

It has been a while since I tried to integrate styker.js with the project that I am working on. The project has a lot of integration tests, mostly needs a lot of database calls. It was quite hard to simply pass the initial text matrix calculation phase due to timing out.

I might try stryker.js again soon
