### ISSUE TITLE
Example of a Unary operator mutator?

### ISSUE THREAD

**Issue by adjstreams** [stryker-mutator/stryker-js#4808]
**Question**

I'm trying to create a test project that demonstrates the different types of mutators that StrykerJS will detect, but I can't seem to recreate an example method and test which results in a potential positive Unary operator mutator result.

**Stryker environment**

```
+-- @stryker-mutator/core@8.2.6
+-- @stryker-mutator/jest-runner@8.2.6
```

```
+-- jest@29.7.0
```

**Additional context**

**Comment by nicojs** [comment]
See: 
https://github.com/stryker-mutator/stryker-js/blob/master/packages/instrumenter/src/mutators/unary-operator-mutator.ts#L9-L14

Input:

```js
const a = ~1;
const b = +1;
const c = -1;
```

Output:

```
[Survived] UnaryOperator
src/main.js:1:11
-   const a = ~1;
+   const a = 1;

[Survived] UnaryOperator
src/main.js:2:11
-   const b = +1;
+   const b = -1;

[Survived] UnaryOperator
src/main.js:3:11
-   const c = -1;
+   const c = +1;
```
