### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by why-this-code-works** [stryker-mutator/stryker-js#4881]
**Question**

Is this project still maintained? Latest activity by humans in the master branch was several months ago, CI status is 🔴, reported issues are left unanswered.

Not to blame anyone or anything like that, just a quick update on the project status would be welcome for devs like myself to decide either to rely on this tool for new projects or not 🙌 

Is it a pause in the maintenance or stryker-js is 💀?

**Comment by why-this-code-works** [comment]
cc @hugo-vrijswijk @jaspervdveen @nicojs

**Comment by nicojs** [comment]
It is still maintained. I was busy for a while, but coming back to it this summer. I'm now doing some much-needed life cycle management stuff and then going through the list of issues.

That said, I'm currently the only active maintainer. It would be better to have more maintainers.
