### ISSUE TITLE
expressionMutantPlacer could not place mutants with type(s): "MethodExpression"

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-js#4884]
**Summary**

Stryker could not mutate the following statement and fully exits:

```js
initialNodes.filter((n) => n.id === "tiptilt")[0].className = tiptiltState
```

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information.",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "vitest",
  "testRunner_comment": "Take a look at https://stryker-mutator.io/docs/stryker-js/vitest-runner for information about the vitest plugin.",
  "coverageAnalysis": "perTest"
}
```

**Test runner config**

Nothing special here

**Stryker environment**

```
@stryker-mutator/vitest-runner@8.2.6
```

```
vitest@1.6.0
```

**Test runner environment**

```shell
# vitest
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v20.13.1
| npm              | 10.8.0
| Operating System | macos 14.5

**Add stryker.log**
[stryker.log](https://github.com/user-attachments/files/16011351/stryker.log)

**Comment by nicojs** [comment]
Thanks for reporting! This should be an easy fix.
