### ISSUE TITLE
glob 11 doesn't support node 18

### ISSUE THREAD

**Issue by romainmenke** [stryker-mutator/stryker-js#4930]
This change was introduced in: https://github.com/stryker-mutator/stryker-js/pull/4894

Resulting in:

```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: glob@11.0.0
npm error notsup Not compatible with your version of node/npm: glob@11.0.0
npm error notsup Required: {"node":"20 || >=22"}
npm error notsup Actual:   {"npm":"10.7.0","node":"v18.20.4"}
```

While stryker itself still claims to support node 18: https://github.com/stryker-mutator/stryker-js/blob/7b4b9b178325c703d0d61b4fbca867ad814a5a9b/package.json#L71

Would it be possible to revert the glob update?

**Comment by nicojs** [comment]
Thanks for reporting. Will fix asap

**Comment by nicojs** [comment]
F.y.i. found this issue with an explanation on why the latest major release of glob and others don't support node 18 anymore. https://github.com/isaacs/node-lru-cache/issues/343

**Comment by romainmenke** [comment]
Yup, I have no strong opinion on any of that :)
I slightly prefer keeping support for node 18 around a bit longer, but these are short term pains.

I am also fine with bumping the minimum node version in stryker and doing a semver major.
Stryker is a dev tool and can assume to be used mostly on more recent node versions. 

The only real issue is that stryker advertises node 18 support, while having a dependency that requires a higher version.

**Comment by nicojs** [comment]
>  Stryker is a dev tool and can assume to be used mostly on more recent node versions.

I've worked on big enterprise projects where developers couldn't choose to upgrade, requiring weeks of work. I like the clarity of the NodeJS release schedule.

**Comment by romainmenke** [comment]
Thank you @nicojs for the speedy updates here 🙇
